import { Router } from "express";
import jwt from "jsonwebtoken";
import { getPool } from "../db.js";
import { agentSurfaceCatalog, normalizeAgentSurfaceKey } from "../agentSurfacePolicy.js";
import { assessTenantAgentSurfaceReadiness, upsertTenantAgentSurfaceDeployment, upsertUserAgentSurfacePreferences } from "../agentSurfaceRuntimeService.js";
function requireUserJwt(req, res, next) { if (req.auth?.mode === "user_jwt") return next(); try { const token = String(req.headers.authorization || "").replace(/^Bearer\s+/i, ""); const payload = jwt.verify(token, process.env.JWT_SECRET || "dev-secret"); if (!payload?.user_id) throw new Error("missing user"); req.auth = { mode: "user_jwt", user_id: payload.user_id, tenant_id: payload.tenant_id || null, is_admin: false }; return next(); } catch { return res.status(401).json({ ok: false, error: { code: "user_jwt_required", message: "Sign in required." }, secrets_included: false }); } }
async function membership(pool, req) { const params = [req.auth.user_id]; let tenant = ""; if (req.auth.tenant_id) { tenant = " AND m.tenant_id=?"; params.push(req.auth.tenant_id); } const [rows] = await pool.query(`SELECT m.tenant_id,m.user_id,m.role,m.status,t.display_name FROM memberships m JOIN tenants t ON t.tenant_id=m.tenant_id WHERE m.user_id=? AND m.status='active'${tenant} ORDER BY m.granted_at ASC LIMIT 1`, params); if (!rows[0]) { const error = new Error("No active tenant membership was found."); error.status = 403; error.code = "agent_surface_membership_required"; throw error; } return rows[0]; }
function sendError(res, error, code) { return res.status(error.status || 500).json({ ok: false, error: { code: error.code || code, message: error.message, ...(error.details !== undefined ? { details: error.details } : {}) }, secrets_included: false }); }
export function buildAgentSurfaceRoutes(deps = {}) {
  const router = Router(); const pool = deps.pool || getPool();
  router.get("/me/agent-surfaces/catalog", requireUserJwt, async (req, res) => { try { const member = await membership(pool, req); return res.json({ ok: true, tenant_id: member.tenant_id, user_id: req.auth.user_id, catalog: agentSurfaceCatalog(), secrets_included: false }); } catch (error) { return sendError(res, error, "agent_surface_catalog_failed"); } });
  router.get("/me/agent-surfaces", requireUserJwt, async (req, res) => { try { const member = await membership(pool, req); return res.json({ ok: true, catalog: agentSurfaceCatalog(), ...await assessTenantAgentSurfaceReadiness({ tenantId: member.tenant_id, userId: req.auth.user_id, pool }), secrets_included: false }); } catch (error) { return sendError(res, error, "agent_surfaces_read_failed"); } });
  router.get("/me/agent-surfaces/readiness", requireUserJwt, async (req, res) => { try { const member = await membership(pool, req); return res.json({ ok: true, ...await assessTenantAgentSurfaceReadiness({ tenantId: member.tenant_id, userId: req.auth.user_id, pool }), secrets_included: false }); } catch (error) { return sendError(res, error, "agent_surface_readiness_failed"); } });
  router.put("/me/agent-surfaces/:surface_key/preferences", requireUserJwt, async (req, res) => { try { const member = await membership(pool, req); const preference = await upsertUserAgentSurfacePreferences({ tenantId: member.tenant_id, userId: req.auth.user_id, surfaceKey: normalizeAgentSurfaceKey(req.params.surface_key), preferences: req.body || {}, pool }); return res.json({ ok: true, preference, ownership: "authenticated_user_only", execution_policy: "High-risk capabilities remain approval-gated.", secrets_included: false }); } catch (error) { return sendError(res, error, "agent_surface_preferences_update_failed"); } });
  router.put("/me/agent-surfaces/:surface_key/deployment", requireUserJwt, async (req, res) => { try { const member = await membership(pool, req); if (!["owner", "workspace_owner", "admin"].includes(String(member.role || "").toLowerCase())) { const error = new Error("Tenant owner or admin role is required."); error.status = 403; error.code = "agent_surface_deployment_role_required"; throw error; } const deployment = await upsertTenantAgentSurfaceDeployment({ tenantId: member.tenant_id, actorUserId: req.auth.user_id, surfaceKey: normalizeAgentSurfaceKey(req.params.surface_key), activationMode: req.body?.activation_mode || req.body?.mode, enabled: req.body?.enabled !== false, dedicatedTargetType: req.body?.dedicated_target_type, dedicatedTargetId: req.body?.dedicated_target_id, pool }); return res.json({ ok: true, deployment, deployment_scope: "tenant", preferences_scope: "per_user", automatic_fallback: false, secrets_included: false }); } catch (error) { return sendError(res, error, "agent_surface_deployment_update_failed"); } });
  return router;
}
