import { Router } from "express";
import { getPool } from "../db.js";
import { randomUUID } from "node:crypto";

const DEFAULT_WINDOWS_ALIASES = [
  { alias: "node_ver",       cmd: "node",     args: ["--version"],             allow_extra_args: false, description: "Node.js version" },
  { alias: "git_status",     cmd: "git",      args: ["status"],                allow_extra_args: false, description: "Git status" },
  { alias: "list_processes", cmd: "tasklist", args: ["/FO", "CSV", "/NH"],     allow_extra_args: false, description: "Running processes (CSV)" },
  { alias: "disk_usage",     cmd: "wmic",     args: ["logicaldisk", "get", "size,freespace,caption"], allow_extra_args: false, description: "Disk usage" },
];

function buildAllowlistEnvValue(aliases) {
  const obj = {};
  for (const a of aliases) {
    obj[a.alias] = {
      command: a.cmd,
      args: a.args || [],
      display_name: a.description || a.alias,
      allow_extra_args: !!a.allow_extra_args,
    };
  }
  return JSON.stringify(obj);
}

function buildStartBat(port = 7070) {
  return [
    "@echo off",
    "REM Mad4B Local Connector Agent — generated by /local-connector/install",
    "REM 1. Set BACKEND_API_KEY to the connector_secret returned by /install",
    "REM 2. Set the same value as CONNECTOR_LOCAL_API_KEY in Cloud Run env vars",
    `set CONNECTOR_PORT=${port}`,
    "set BACKEND_API_KEY=PASTE_CONNECTOR_SECRET_HERE",
    "set MAIN_API_URL=https://api.mad4b.com",
    "set CONNECTOR_SHELL_ENABLED=true",
    "set CONNECTOR_FILES_ENABLED=false",
    "set CONNECTOR_FETCH_UPLOAD_ENABLED=true",
    `node "%~dp0server.mjs" >> "%~dp0connector.log" 2>&1`,
  ].join("\r\n");
}

export function buildLocalConnectorInstallRoutes(deps) {
  const { requireBackendApiKey } = deps;
  const router = Router();

  // ── POST /local-connector/install ─────────────────────────────────────────
  // Governed installation — idempotent, returns the full setup bundle.
  router.post("/local-connector/install", requireBackendApiKey, async (req, res) => {
    try {
      const { user_id, tenant_id, device_id, tunnel_url, connector_port = 7070, custom_aliases = [] } = req.body || {};
      if (!user_id || !tenant_id || !device_id || !tunnel_url) {
        return res.status(400).json({ ok: false, error: { code: "missing_fields", message: "user_id, tenant_id, device_id, tunnel_url required." } });
      }

      const pool = getPool();

      const [[tenant]] = await pool.query("SELECT tenant_id FROM `tenants` WHERE tenant_id = ? LIMIT 1", [tenant_id]);
      if (!tenant) return res.status(404).json({ ok: false, error: { code: "tenant_not_found" } });

      const normalizedUrl = tunnel_url.replace(/\/$/, "");
      const newConfigId = randomUUID();
      const connectorSecret = randomUUID().replace(/-/g, "") + randomUUID().replace(/-/g, "");

      await pool.query(
        `INSERT INTO \`local_connector_user_configs\`
           (config_id, user_id, tenant_id, device_id, tunnel_url, connector_secret, is_enabled)
         VALUES (?, ?, ?, ?, ?, ?, 1)
         ON DUPLICATE KEY UPDATE
           tunnel_url = VALUES(tunnel_url),
           connector_secret = VALUES(connector_secret),
           is_enabled = 1`,
        [newConfigId, user_id, tenant_id, device_id, normalizedUrl, connectorSecret]
      );

      const [[config]] = await pool.query(
        "SELECT config_id, connector_secret FROM `local_connector_user_configs` WHERE user_id = ? AND tenant_id = ? AND device_id = ? LIMIT 1",
        [user_id, tenant_id, device_id]
      );
      const finalConfigId = config.config_id;
      const finalSecret = config.connector_secret;

      const allAliases = [...DEFAULT_WINDOWS_ALIASES, ...custom_aliases];
      for (const entry of allAliases) {
        const cmdTemplate = [entry.cmd, ...(entry.args || [])].join(" ");
        await pool.query(
          `INSERT IGNORE INTO \`local_connector_shell_allowlists\`
             (config_id, alias, command_template, allow_extra_args, description)
           VALUES (?, ?, ?, ?, ?)`,
          [finalConfigId, entry.alias, cmdTemplate, entry.allow_extra_args ? 1 : 0, entry.description || null]
        );
      }

      const allowlistEnvValue = buildAllowlistEnvValue(allAliases);
      const startBat = buildStartBat(connector_port);

      return res.status(200).json({
        ok: true,
        config_id: finalConfigId,
        device_id,
        tunnel_url: normalizedUrl,
        connector_secret: finalSecret,
        cloud_run_env: {
          CONNECTOR_LOCAL_API_KEY: finalSecret,
          instruction: "Run: gcloud run services update http-generic-api --region=europe-west1 --update-env-vars=CONNECTOR_LOCAL_API_KEY=<connector_secret>",
        },
        installation: {
          connector_port,
          aliases: allAliases.map((a) => a.alias),
          files: {
            "start.bat": startBat,
            "CONNECTOR_SHELL_ALLOWLIST env value": allowlistEnvValue,
          },
          steps: [
            "1. Copy connector_secret to start.bat BACKEND_API_KEY line.",
            "2. Set CONNECTOR_SHELL_ALLOWLIST in start.bat from the 'CONNECTOR_SHELL_ALLOWLIST env value' field.",
            "3. Update Cloud Run with CONNECTOR_LOCAL_API_KEY=<connector_secret> (see cloud_run_env.instruction).",
            `4. Ensure Cloudflare tunnel routes ${normalizedUrl} → http://localhost:${connector_port}.`,
            "5. Run start.bat. Verify with GET /local-connector/health.",
          ],
        },
      });
    } catch (err) {
      return res.status(500).json({ ok: false, error: { code: "install_failed", message: err.message } });
    }
  });

  // ── GET /local-connector/install/status ───────────────────────────────────
  router.get("/local-connector/install/status", requireBackendApiKey, async (req, res) => {
    try {
      const { user_id, tenant_id, device_id } = req.query;
      if (!user_id || !tenant_id || !device_id) {
        return res.status(400).json({ ok: false, error: { code: "missing_fields", message: "user_id, tenant_id, device_id required." } });
      }
      const [[config]] = await getPool().query(
        "SELECT config_id, tunnel_url, is_enabled, created_at, updated_at FROM `local_connector_user_configs` WHERE user_id = ? AND tenant_id = ? AND device_id = ? LIMIT 1",
        [user_id, tenant_id, device_id]
      );
      if (!config) return res.status(200).json({ ok: true, installed: false });

      const [aliases] = await getPool().query(
        "SELECT alias, command_template, allow_extra_args, description FROM `local_connector_shell_allowlists` WHERE config_id = ?",
        [config.config_id]
      );
      return res.status(200).json({ ok: true, installed: true, config, aliases });
    } catch (err) {
      return res.status(500).json({ ok: false, error: { code: "status_failed", message: err.message } });
    }
  });

  // ── DELETE /local-connector/uninstall ─────────────────────────────────────
  router.delete("/local-connector/uninstall", requireBackendApiKey, async (req, res) => {
    try {
      const { user_id, tenant_id, device_id } = req.body || {};
      if (!user_id || !tenant_id || !device_id) {
        return res.status(400).json({ ok: false, error: { code: "missing_fields", message: "user_id, tenant_id, device_id required." } });
      }
      const [result] = await getPool().query(
        "UPDATE `local_connector_user_configs` SET is_enabled = 0 WHERE user_id = ? AND tenant_id = ? AND device_id = ?",
        [user_id, tenant_id, device_id]
      );
      if (result.affectedRows === 0) {
        return res.status(404).json({ ok: false, error: { code: "config_not_found" } });
      }
      return res.status(200).json({ ok: true, message: "Local connector disabled for this device." });
    } catch (err) {
      return res.status(500).json({ ok: false, error: { code: "uninstall_failed", message: err.message } });
    }
  });

  return router;
}
