import { Router } from "express";
import { buildTenantGrowthDashboard, buildTenantDashboardDigest, buildTenantDashboardActionPreview, readTenantDashboardPreferences, upsertTenantDashboardPreferences, recordTenantGrowthRecommendationEvent } from "../tenantGrowthDashboardService.js";

function requireTenantPrincipal(req,res,next){if(req.auth?.mode!=="user_jwt"||req.auth?.is_admin===true||!req.auth?.tenant_id||!req.auth?.user_id)return res.status(401).json({ok:false,error:{code:"tenant_user_jwt_required",message:"A signed tenant user JWT with tenant_id and user_id is required."}});return next();}
function parseJsonQuery(value,fallback={}){if(!value)return fallback;if(typeof value==="object")return value;try{const parsed=JSON.parse(String(value));return parsed&&typeof parsed==="object"?parsed:fallback;}catch{return fallback;}}
function errorResponse(res,error,fallback="tenant_growth_dashboard_failed"){return res.status(error?.status||500).json({ok:false,error:{code:error?.code||fallback,message:error?.message||String(error||fallback)},secrets_included:false});}

export function buildTenantGrowthDashboardRoutes({requireBackendApiKey}={}){
  const router=Router();const guards=[requireBackendApiKey,requireTenantPrincipal].filter(Boolean);
  router.get("/tenant/dashboard",...guards,async(req,res)=>{try{return res.status(200).json(await buildTenantGrowthDashboard({tenantId:req.auth.tenant_id,userId:req.auth.user_id,containerKey:req.query.container_key||null,tabKey:req.query.tab||req.query.tab_key||null,dateRange:req.query.date_range||null,filters:parseJsonQuery(req.query.filters,{}),mode:"dashboard"}));}catch(error){return errorResponse(res,error);}});
  router.get("/tenant/dashboard/tabs/:tabKey",...guards,async(req,res)=>{try{return res.status(200).json(await buildTenantGrowthDashboard({tenantId:req.auth.tenant_id,userId:req.auth.user_id,containerKey:req.query.container_key||null,tabKey:req.params.tabKey,dateRange:req.query.date_range||null,filters:parseJsonQuery(req.query.filters,{}),mode:"dashboard"}));}catch(error){return errorResponse(res,error,"tenant_growth_dashboard_tab_failed");}});
  router.get("/tenant/dashboard/preferences",...guards,async(req,res)=>{try{return res.status(200).json({...await readTenantDashboardPreferences({tenantId:req.auth.tenant_id,userId:req.auth.user_id}),secrets_included:false});}catch(error){return errorResponse(res,error,"tenant_dashboard_preferences_read_failed");}});
  router.put("/tenant/dashboard/preferences",...guards,async(req,res)=>{try{return res.status(200).json(await upsertTenantDashboardPreferences({tenantId:req.auth.tenant_id,userId:req.auth.user_id,preferences:req.body||{}}));}catch(error){return errorResponse(res,error,"tenant_dashboard_preferences_write_failed");}});
  router.get("/tenant/dashboard/digest",...guards,async(req,res)=>{try{return res.status(200).json(await buildTenantDashboardDigest({tenantId:req.auth.tenant_id,userId:req.auth.user_id,containerKey:req.query.container_key||null}));}catch(error){return errorResponse(res,error,"tenant_dashboard_digest_failed");}});
  router.get("/tenant/dashboard/actions/:actionRefKey/preview",...guards,async(req,res)=>{try{return res.status(200).json(await buildTenantDashboardActionPreview({tenantId:req.auth.tenant_id,userId:req.auth.user_id,actionRefKey:req.params.actionRefKey,containerKey:req.query.container_key||null}));}catch(error){return errorResponse(res,error,"tenant_dashboard_action_preview_failed");}});
  router.post("/tenant/dashboard/recommendations/:recommendationId/feedback",...guards,async(req,res)=>{try{return res.status(201).json(await recordTenantGrowthRecommendationEvent({tenantId:req.auth.tenant_id,userId:req.auth.user_id,recommendationId:req.params.recommendationId,eventType:req.body?.event_type,reasonCode:req.body?.reason_code||null,workspaceId:req.body?.workspace_id||null,recommendationKey:req.body?.recommendation_key||null,tabKey:req.body?.tab_key||null,cardId:req.body?.card_id||null,resultMetricKey:req.body?.result_metric_key||null,resultValue:req.body?.result_value??null,context:req.body?.context||{}}));}catch(error){return errorResponse(res,error,"tenant_dashboard_feedback_failed");}});
  return router;
}
