import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const registry = JSON.parse(read(".github/derived-state-governance.json"));
const verifierRegistry = JSON.parse(read(".github/governance/verifier-registry.json"));
const constitution = JSON.parse(read("http-generic-api/config/repository-governance-constitution.json"));
const workflow = read(".github/workflows/derived-state-closure.yml");
const policyObjectionWorkflow = read(".github/workflows/policy-objection-ci.yml");
const finalReadbackWorkflow = read(".github/workflows/hostinger-storage-final-work-map-readback-guard.yml");
const fixedPoint = read("scripts/repository-governance-fixed-point.mjs");
const repair = read(".github/workflows/derived-state-repair-dispatch.yml");
const finalizer = read(".github/workflows/derived-state-converged-automerge.yml");
const script = read("scripts/derived-state-closure.mjs");
const inventoryGate = read("scripts/repository-inventory-verification-gate.mjs");
assert.equal(registry.contract, "mad4b.repository-derived-state-governance.v1");
assert.equal(registry.policy.required_evidence_identity, "source_base_merge_candidate_executed_sha");
assert.equal(registry.repository_governance.verifier_registry, ".github/governance/verifier-registry.json");
assert.equal(registry.repository_governance.verifier_execution_registry_only, true);
assert.equal(registry.repository_governance.derived_dependency_execution_topological, true);
assert.equal(registry.repository_governance.inverse_deletion_dependency_required, true);
assert.ok(constitution.control_plane_paths.includes(".github/workflows/hostinger-storage-final-work-map-readback-guard.yml"));
assert.ok(registry.convergence.automation_control_paths.includes(".github/workflows/hostinger-storage-final-work-map-readback-guard.yml"));
assert.equal(registry.convergence.automation_control_surface_changes_require_manual_merge, true);
assert.equal(verifierRegistry.contract, "mad4b.repository-verifier-registry.v1");
assert.equal(verifierRegistry.shell_execution_forbidden, true);
assert.deepEqual(new Set(verifierRegistry.allowed_step_types), new Set(["node", "npm", "work_map_dynamic"]));
const verifierIds = new Set(verifierRegistry.verifiers.map((entry) => entry.id));
for (const artifact of registry.artifacts) {
  assert.equal(verifierIds.has(artifact.verifier_id), true, `unregistered verifier ${artifact.verifier_id}`);
  assert.ok(["semantic", "observability"].includes(artifact.artifact_class));
  if (artifact.artifact_class === "observability") assert.equal(artifact.merge_blocking, false);
  if (artifact.artifact_class === "semantic") assert.equal(artifact.merge_blocking, true);
}
const frontendProjection = registry.artifacts.find((artifact) => artifact.artifact_id === "frontend_openapi_projection");
assert.ok(frontendProjection, "frontend/OpenAPI projection must remain registered");
for (const output of [
  "specs/020-platform-resource-identity-brand-governance/openapi-detail-gap-classification.json",
  "specs/020-platform-resource-identity-brand-governance/openapi-gap-closure-plan.json",
]) {
  assert.ok(frontendProjection.outputs.includes(output), `frontend/OpenAPI projection omits downstream output ${output}`);
}
const frontendVerifier = verifierRegistry.verifiers.find((verifier) => verifier.id === "frontend_openapi_currentness");
const frontendVerifierScripts = frontendVerifier.steps.map((step) => step.script).filter(Boolean);
assert.ok(frontendVerifierScripts.indexOf("frontend:dispatch:check") < frontendVerifierScripts.indexOf("openapi:detail-gaps:check"));
assert.ok(frontendVerifierScripts.indexOf("openapi:detail-gaps:check") < frontendVerifierScripts.indexOf("openapi:gap-closure-plan:check"));
assert.match(script, /loadVerifierRegistry/u);
assert.match(script, /work_map_dynamic/u);
assert.match(script, /registeredWorkMapFeatures/u);
assert.match(script, /topologicalArtifacts/u);
assert.doesNotMatch(script, /const\s+VERIFIERS\s*=/u);
assert.doesNotMatch(script, /014-retail/u);
assert.doesNotMatch(script, /git\s+push/u);
assert.match(workflow, /name:\s*Derived State Closure Detector/u);
assert.match(workflow, /Checkout exact GitHub merge candidate|Checkout exact candidate/u);
assert.match(workflow, /canonical-producer-evidence\.json/u);
assert.match(workflow, /node - "\$OUT\/repository-governance\.json" <<'NODE'[\s\S]*process\.argv\[2\]/u);
assert.doesNotMatch(workflow, /readFileSync\(process\.argv\[1\], 'utf8'\)/u);
assert.equal((finalReadbackWorkflow.match(/process\.argv\[2\]/gu) || []).length, 2);
assert.doesNotMatch(finalReadbackWorkflow, /process\.argv\[1\]/u);
assert.match(fixedPoint, /converged:\s*report\.converged\s*===\s*true\s*&&\s*report\.fixed_point\.converged\s*===\s*true/u);
assert.match(fixedPoint, /blocking_failure_policy_ids:\s*report\.blocking_failure_policy_ids/u);
assert.match(workflow, /merge_candidate_sha/u);
assert.match(workflow, /executed_sha/u);
assert.match(workflow, /repository-governance-evidence-finalizer\.mjs/u);
assert.match(workflow, /select\(\.status=="completed" and \(\.conclusion=="success" or \.conclusion=="failure"\)\)/u);
assert.match(policyObjectionWorkflow, /producer-evidence\.json[\s\S]*?NODE[\s\S]*?node scripts\/repository-governance-objection-gate\.mjs/u);
assert.match(policyObjectionWorkflow, /if: always\(\)[\s\S]*?name: repository-governance-producer-evidence-\$\{\{ github\.run_id \}\}/u);
assert.doesNotMatch(workflow, /\n\s*paths:/u);
assert.match(finalizer, /Trusted GitHub App exact-candidate attestation/u);
assert.match(finalizer, /ATTEST_DERIVED_STATE_CLOSURE/u);
assert.match(finalizer, /ATTEST_GOVERNED_PRODUCTION_PROMOTION/u);
assert.match(finalizer, /merge_commit_sha/u);
assert.match(finalizer, /--match-head-commit/u);
assert.match(repair, /draft_repair_allowed=true/u);
assert.match(repair, /delegated_work_map_writer/u);
assert.doesNotMatch(repair, /git\s+push/u);
assert.match(inventoryGate, /artifact_class === "observability"/u);
assert.match(inventoryGate, /merge_blocking === false/u);
console.log(JSON.stringify({ ok: true, contract: registry.contract, dynamic_verifier_registry: true, dynamic_work_map_discovery: true, exact_candidate_detector: true, trusted_app_finalizer: true }));
