-- Sprint 26: Developer Agent Growth Loop
-- Adds: session summarisation, dev-agent proposal engine, AI discussion threads,
--       and Make.com / n8n app catalog entries.
-- All statements are idempotent.

-- ─── Session summaries ────────────────────────────────────────────────────────
-- One LLM-generated summary per completed customer_session.
-- Populated by the dev agent sweep — consumed by the proposal extractor.

CREATE TABLE IF NOT EXISTS `session_summaries` (
  `id`                   INT UNSIGNED  AUTO_INCREMENT PRIMARY KEY,
  `summary_id`           VARCHAR(36)   NOT NULL UNIQUE,
  `session_id`           VARCHAR(128)  NOT NULL,
  `tenant_id`            VARCHAR(36)   NOT NULL,
  `user_id`              VARCHAR(36)   NULL,
  `workspace_key`        VARCHAR(128)  NULL,
  `summary_text`         TEXT          NOT NULL    COMMENT 'Narrative prose summary',
  `tasks_completed`      JSON          NULL        COMMENT 'Array of completed task strings',
  `blockers`             JSON          NULL        COMMENT 'Array of blocker/friction strings',
  `feature_requests`     JSON          NULL        COMMENT 'Array of explicit feature requests',
  `integration_needs`    JSON          NULL        COMMENT 'Array of integration gaps mentioned',
  `complexity`           ENUM('low','medium','high') NULL,
  `session_model`        VARCHAR(128)  NULL        COMMENT 'Model used in the session',
  `turn_count`           SMALLINT UNSIGNED NULL,
  `analyzed`             TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '1 = included in a proposal sweep',
  `analyzed_at`          DATETIME      NULL,
  `dev_agent_run_id`     VARCHAR(36)   NULL,
  `created_at`           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_ss_session`   (`session_id`),
  INDEX `idx_ss_tenant`    (`tenant_id`),
  INDEX `idx_ss_analyzed`  (`analyzed`),
  INDEX `idx_ss_workspace` (`workspace_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── Dev-agent runs ───────────────────────────────────────────────────────────
-- Audit log for each background sweep.

CREATE TABLE IF NOT EXISTS `dev_agent_runs` (
  `run_id`              VARCHAR(36)   NOT NULL PRIMARY KEY,
  `sessions_analyzed`   INT UNSIGNED  NOT NULL DEFAULT 0,
  `summaries_created`   INT UNSIGNED  NOT NULL DEFAULT 0,
  `proposals_created`   INT UNSIGNED  NOT NULL DEFAULT 0,
  `proposals_updated`   INT UNSIGNED  NOT NULL DEFAULT 0,
  `run_summary`         TEXT          NULL,
  `status`              ENUM('running','completed','failed') NOT NULL DEFAULT 'running',
  `error_msg`           VARCHAR(512)  NULL,
  `started_at`          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at`        DATETIME      NULL,
  INDEX `idx_dar_status` (`status`),
  INDEX `idx_dar_started` (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── Dev-agent proposals ─────────────────────────────────────────────────────
-- Platform improvement proposals generated by the dev agent from session patterns.
-- scope: which system layer the proposal targets.
-- layer: specific file / module / table within that scope.

CREATE TABLE IF NOT EXISTS `dev_agent_proposals` (
  `proposal_id`          VARCHAR(36)   NOT NULL PRIMARY KEY,
  `tenant_id`            VARCHAR(36)   NULL        COMMENT 'NULL = platform-wide proposal',
  `scope`                ENUM('code','db','workflow','integration','agent','ux') NOT NULL,
  `layer`                VARCHAR(255)  NULL        COMMENT 'e.g. appAdapters, migrations/workspaces, agentLoopRunner',
  `title`                VARCHAR(255)  NOT NULL,
  `description`          TEXT          NOT NULL,
  `rationale`            TEXT          NULL,
  `evidence_session_ids` JSON          NULL        COMMENT 'Array of session_ids that triggered this',
  `evidence_summary`     TEXT          NULL        COMMENT 'Compressed cross-session evidence',
  `priority`             ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `status`               ENUM('pending','confirmed','dismissed','in_discussion','implemented')
                                       NOT NULL DEFAULT 'pending',
  `confirmed_by`         VARCHAR(36)   NULL,
  `confirmed_at`         DATETIME      NULL,
  `dismissed_by`         VARCHAR(36)   NULL,
  `dismissed_at`         DATETIME      NULL,
  `implementation_notes` TEXT          NULL,
  `source_run_id`        VARCHAR(36)   NULL        COMMENT 'dev_agent_runs.run_id that created this',
  `created_at`           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_dap_tenant`    (`tenant_id`),
  INDEX `idx_dap_status`    (`status`),
  INDEX `idx_dap_scope`     (`scope`),
  INDEX `idx_dap_priority`  (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── Proposal discussions ─────────────────────────────────────────────────────
-- Threaded AI chat on individual proposals. The AI has full user context so it
-- can explain rationale, refine scope, and help the user decide.

CREATE TABLE IF NOT EXISTS `proposal_discussions` (
  `message_id`        VARCHAR(36)   NOT NULL PRIMARY KEY,
  `proposal_id`       VARCHAR(36)   NOT NULL,
  `tenant_id`         VARCHAR(36)   NULL,
  `user_id`           VARCHAR(36)   NULL         COMMENT 'NULL for AI messages',
  `role`              ENUM('user','assistant')  NOT NULL,
  `content`           TEXT          NOT NULL,
  `context_snapshot`  JSON          NULL         COMMENT 'Proposal + user context at message time',
  `model_used`        VARCHAR(128)  NULL         COMMENT 'Model that generated assistant reply',
  `created_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_pd_proposal` (`proposal_id`),
  INDEX `idx_pd_tenant`   (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── App catalog: Make.com + n8n ─────────────────────────────────────────────

INSERT INTO `app_integrations`
  (app_key, display_name, category, auth_type, description, docs_url, status)
VALUES
  ('makecom', 'Make.com', 'automation', 'api_key',
   'Trigger Make.com scenarios and webhooks from the platform',
   'https://www.make.com/en/api-documentation', 'active'),
  ('n8n', 'n8n', 'automation', 'api_key',
   'Execute n8n workflows and webhooks from the platform',
   'https://docs.n8n.io/api/', 'active')
ON DUPLICATE KEY UPDATE
  display_name  = VALUES(display_name),
  status        = VALUES(status);
