-- Sprint 54: Register expanded local connector capabilities in the GPT tool registries.
--
-- The custom GPT auth dispatcher is intentionally MCP-like: /gpt/tools lists
-- rows from the DB registry and /gpt/tools/call dispatches by tool_key. These
-- rows make the newer local connector endpoints discoverable without adding
-- one dispatcher path per device capability.
--
-- Admin receives dependency recovery plus broad workaround surfaces because
-- they can mutate local or provider state. Tenant receives browser and app
-- control only, scoped by the existing connector proxy and auth guards.
--
-- Important: this file contains no semicolons inside any string literal,
-- per the migrator parser constraint recorded in migration 055.

INSERT INTO `admin_platform_endpoint_tools`
  (tool_key, display_name, description, http_method, http_path,
   path_param_keys, input_schema, fixed_body, tags, sort_order, is_enabled)
VALUES
('connector_files',
 'Device Files',
 'Explore allowlisted device paths, list drives, locate repo roots, and read or write allowlisted files. Repo location is bounded by connector file policy.',
 'POST', '/connector/{device_id}/files',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["list","list_drives","locate_repo","read","write"]},"path":{"type":"string"},"content":{"type":"string"},"markers":{"type":"array","items":{"type":"string"},"description":"Repo marker names for locate_repo."},"max_depth":{"type":"integer","minimum":0,"maximum":8},"max_matches":{"type":"integer","minimum":1,"maximum":50},"max_entries":{"type":"integer","minimum":1,"maximum":500},"user_id":{"type":"string"}}}',
 NULL,
 'device,filesystem,repo_discovery',
 260,
 1),
('connector_dependencies',
 'Device Dependencies',
 'Inspect or install allowlisted recovery dependencies on the local device. The connector controls the package allowlist and blocks arbitrary package names.',
 'POST', '/connector/{device_id}/dependencies',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["status","list","install"]},"package_key":{"type":"string","enum":["gh","googlecloudsdk"]},"timeout_ms":{"type":"integer","minimum":1000,"maximum":600000},"user_id":{"type":"string"}}}',
 NULL,
 'device,dependency_recovery,state_changing',
 262,
 1),
('connector_apps',
 'Device Apps',
 'List, launch, inspect, or close allowlisted desktop applications on the local device. Each app returns capability and risk classification metadata.',
 'POST', '/connector/{device_id}/apps',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["status","list","launch","status_app","close"]},"app_alias":{"type":"string"},"timeout_ms":{"type":"integer","minimum":1000,"maximum":120000},"user_id":{"type":"string"}}}',
 NULL,
 'device,desktop_app,interactive,classified',
 264,
 1),
('connector_browser',
 'Device Browser',
 'Use an allowlisted browser on the local device for URL opening and screenshots. URLs are restricted to absolute http or https values by the connector.',
 'POST', '/connector/{device_id}/browser',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["list","open_url","screenshot"]},"browser_alias":{"type":"string"},"url":{"type":"string","format":"uri"},"scale":{"type":"number","minimum":0.1,"maximum":1.0},"timeout_ms":{"type":"integer","minimum":1000,"maximum":120000},"user_id":{"type":"string"}}}',
 NULL,
 'device,browser,interactive,classified',
 266,
 1),
('connector_ps',
 'Device PowerShell',
 'Admin-only workaround surface for recovery scripts when narrower tools cannot complete the task. Requires connector PowerShell enablement and current user intent.',
 'POST', '/connector/{device_id}/ps',
 '["device_id"]',
 '{"type":"object","required":["device_id","script"],"properties":{"device_id":{"type":"string"},"script":{"type":"string","maxLength":10000},"timeout_ms":{"type":"integer","minimum":1000,"maximum":600000},"user_id":{"type":"string"}}}',
 NULL,
 'device,powershell,state_changing,admin_only,workaround',
 267,
 1),
('connector_win',
 'Device Windows Control',
 'Admin-only Windows workaround surface for screenshots, services, processes, notifications, and controlled UI recovery when narrower tools are unavailable.',
 'POST', '/connector/{device_id}/win',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["open_url","open_vscode","screenshot","process_list","process_kill","notify","service_list","service_action","disk_list","dir_list","file_search"]},"url":{"type":"string"},"path":{"type":"string"},"pattern":{"type":"string"},"recurse":{"type":"boolean"},"limit":{"type":"integer","maximum":200},"scale":{"type":"number","minimum":0.1,"maximum":1.0},"filter":{"type":"string"},"top":{"type":"integer"},"name":{"type":"string"},"pid":{"type":"integer"},"title":{"type":"string"},"message":{"type":"string"},"service_name":{"type":"string"},"service_action":{"type":"string","enum":["start","stop","restart"]},"user_id":{"type":"string"}}}',
 NULL,
 'device,windows_control,interactive,state_changing,admin_only,workaround',
 268,
 1),
('connector_n8n',
 'Device n8n Control',
 'Admin-only local n8n workaround for workflow inspection, activation, deactivation, execution, and execution-history recovery.',
 'POST', '/connector/{device_id}/n8n',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["health","list_workflows","get_workflow","activate_workflow","deactivate_workflow","run_workflow","list_executions"]},"workflow_id":{"type":"string"},"input_data":{"type":"object","additionalProperties":true},"limit":{"type":"integer"},"user_id":{"type":"string"}}}',
 NULL,
 'device,n8n,state_changing,admin_only,workaround',
 269,
 1),
('connector_cf',
 'Device Cloudflare Control',
 'Admin-only Cloudflare workaround for tunnel, DNS, zone, and cache recovery when primary cloud control-plane paths are degraded.',
 'POST', '/connector/{device_id}/cf',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["list_zones","list_dns","create_dns","delete_dns","list_tunnels","tunnel_status","purge_cache"]},"zone_id":{"type":"string"},"record_id":{"type":"string"},"tunnel_id":{"type":"string"},"type":{"type":"string"},"name":{"type":"string"},"content":{"type":"string"},"proxied":{"type":"boolean"},"files":{"type":"array","items":{"type":"string"}},"user_id":{"type":"string"}}}',
 NULL,
 'device,cloudflare,dns,state_changing,admin_only,workaround',
 270,
 1)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  description  = VALUES(description),
  http_method  = VALUES(http_method),
  http_path    = VALUES(http_path),
  path_param_keys = VALUES(path_param_keys),
  input_schema = VALUES(input_schema),
  fixed_body   = VALUES(fixed_body),
  tags         = VALUES(tags),
  sort_order   = VALUES(sort_order),
  is_enabled   = VALUES(is_enabled);

INSERT INTO `tenant_platform_endpoint_tools`
  (tool_key, display_name, description, http_method, http_path,
   path_param_keys, input_schema, fixed_body, tags, sort_order, is_enabled)
VALUES
('connector_files',
 'Device Files',
 'Explore allowlisted device paths, list drives, locate repo roots, and read or write allowlisted files. Repo location is bounded by connector file policy.',
 'POST', '/connector/{device_id}/files',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["list","list_drives","locate_repo","read","write"]},"path":{"type":"string"},"content":{"type":"string"},"markers":{"type":"array","items":{"type":"string"},"description":"Repo marker names for locate_repo."},"max_depth":{"type":"integer","minimum":0,"maximum":8},"max_matches":{"type":"integer","minimum":1,"maximum":50},"max_entries":{"type":"integer","minimum":1,"maximum":500}}}',
 NULL,
 'device,filesystem,repo_discovery',
 150,
 1),
('connector_apps',
 'Device Apps',
 'List, launch, inspect, or close allowlisted desktop applications on the local device. Each app returns capability and risk classification metadata.',
 'POST', '/connector/{device_id}/apps',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["status","list","launch","status_app","close"]},"app_alias":{"type":"string"},"timeout_ms":{"type":"integer","minimum":1000,"maximum":120000}}}',
 NULL,
 'device,desktop_app,interactive,classified',
 155,
 1),
('connector_browser',
 'Device Browser',
 'Use an allowlisted browser on the local device for URL opening and screenshots. URLs are restricted to absolute http or https values by the connector.',
 'POST', '/connector/{device_id}/browser',
 '["device_id"]',
 '{"type":"object","required":["device_id","action"],"properties":{"device_id":{"type":"string"},"action":{"type":"string","enum":["list","open_url","screenshot"]},"browser_alias":{"type":"string"},"url":{"type":"string","format":"uri"},"scale":{"type":"number","minimum":0.1,"maximum":1.0},"timeout_ms":{"type":"integer","minimum":1000,"maximum":120000}}}',
 NULL,
 'device,browser,interactive,classified',
 158,
 1)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  description  = VALUES(description),
  http_method  = VALUES(http_method),
  http_path    = VALUES(http_path),
  path_param_keys = VALUES(path_param_keys),
  input_schema = VALUES(input_schema),
  fixed_body   = VALUES(fixed_body),
  tags         = VALUES(tags),
  sort_order   = VALUES(sort_order),
  is_enabled   = VALUES(is_enabled);
