-- Sprint 58: Cloudflare first-class read-only runtime capability.
--
-- Adds Cloudflare as a formal actions/endpoints provider capability while
-- preserving connector_cf as the break-glass device workaround.
-- Only read-only operations are exported in this migration.

INSERT INTO `connector_family_registry`
  (`connector_family`, `provider_family`, `display_name`, `protocol_type`, `provider_domain_mode`, `connection_scope`, `runtime_layer`, `default_auth_mode`, `status`, `source`, `notes`)
VALUES
  ('cloudflare_api_connector', 'cloudflare_api_connector', 'Cloudflare REST API connector', 'rest_api', 'fixed_domain', 'platform', 'provider_http', 'bearer_token', 'active', 'migration_068', 'First-class Cloudflare REST capability for read-only DNS, zone, and tunnel diagnostics')
ON DUPLICATE KEY UPDATE
  provider_family = VALUES(provider_family), display_name = VALUES(display_name), protocol_type = VALUES(protocol_type),
  provider_domain_mode = VALUES(provider_domain_mode), connection_scope = VALUES(connection_scope), runtime_layer = VALUES(runtime_layer),
  default_auth_mode = VALUES(default_auth_mode), status = VALUES(status), source = VALUES(source), notes = VALUES(notes), updated_at = CURRENT_TIMESTAMP;

INSERT INTO `actions`
  (`action_key`, `status`, `module_binding`, `connector_family`, `api_key_mode`, `runtime_capability_class`, `runtime_callable`, `primary_executor`, `notes`, `action_id`, `action_title`, `action_class`, `action_scope`, `route_target`, `execution_layer`, `logging_target`, `inventory_role`, `endpoint_group`, `admin_only`, `client_allowed`, `team_allowed`, `created_at`, `updated_at`)
VALUES
  ('cloudflare_api', 'active', 'http_client_backend', 'cloudflare_api_connector', 'bearer_token', 'external_action_only', 'TRUE', 'http_client_backend', 'Cloudflare REST API read-only capability seeded by migration 068. State-changing operations remain gated behind connector_cf until runtime credential validation is complete', 'act_cloudflare_api', 'Cloudflare REST API', 'tool', 'connector_family', 'http_client_backend', 'http_client_backend', 'execution_log', 'runtime_inventory', 'cloudflare', 'TRUE', 'FALSE', 'TRUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
  status = VALUES(status), module_binding = VALUES(module_binding), connector_family = VALUES(connector_family), api_key_mode = VALUES(api_key_mode),
  runtime_capability_class = VALUES(runtime_capability_class), runtime_callable = VALUES(runtime_callable), primary_executor = VALUES(primary_executor),
  notes = VALUES(notes), action_id = VALUES(action_id), action_title = VALUES(action_title), action_class = VALUES(action_class), action_scope = VALUES(action_scope),
  route_target = VALUES(route_target), execution_layer = VALUES(execution_layer), logging_target = VALUES(logging_target), inventory_role = VALUES(inventory_role),
  endpoint_group = VALUES(endpoint_group), admin_only = VALUES(admin_only), client_allowed = VALUES(client_allowed), team_allowed = VALUES(team_allowed), updated_at = CURRENT_TIMESTAMP;

INSERT INTO `endpoints`
  (`endpoint_id`, `parent_action_key`, `endpoint_key`, `endpoint_operation`, `provider_domain`, `method`, `endpoint_path_or_function`, `route_target`, `openai_action_name`, `connector_family`, `status`, `spec_validation_status`, `auth_validation_status`, `privacy_validation_status`, `execution_readiness`, `endpoint_role`, `execution_mode`, `transport_required`, `fallback_allowed`, `inventory_role`, `notes`, `endpoint_title`, `provider_family`, `execution_layer`, `category_group`, `category_detail`, `last_reviewed_at`, `legacy_status`, `client_interface_agnostic`, `request_envelope_required`, `structured_api_supported`, `conversational_trigger_supported`, `writeback_scope`, `schema_json`)
VALUES
  ('ep_cloudflare_api_cf_list_zones', 'cloudflare_api', 'cf_list_zones', 'cloudflareListZones', 'https://api.cloudflare.com/client/v4', 'GET', '/zones', 'cloudflareListZones', 'cloudflare_api__cf_list_zones', 'cloudflare_api_connector', 'active', 'validated', 'validating', 'validated', 'ready', 'primary', 'http_delegated', 'TRUE', 'FALSE', 'runtime_inventory', 'migration_068 Cloudflare read-only endpoint', 'Cloudflare List Zones', 'cloudflare_api', 'http_client_backend', 'cloudflare', 'read_only', '2026-05-17', 'active', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'admin', '{"operationId":"cloudflareListZones","summary":"Cloudflare List Zones","method":"get","path":"/zones","parameters":[{"name":"name","in":"query","required":false,"schema":{"type":"string"}},{"name":"status","in":"query","required":false,"schema":{"type":"string"}}],"responses":{"200":{"description":"Cloudflare API response","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"401":{"description":"Unauthorized","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"403":{"description":"Forbidden","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}}}}'),
  ('ep_cloudflare_api_cf_list_dns_records', 'cloudflare_api', 'cf_list_dns_records', 'cloudflareListDnsRecords', 'https://api.cloudflare.com/client/v4', 'GET', '/zones/{zone_id}/dns_records', 'cloudflareListDnsRecords', 'cloudflare_api__cf_list_dns_records', 'cloudflare_api_connector', 'active', 'validated', 'validating', 'validated', 'ready', 'primary', 'http_delegated', 'TRUE', 'FALSE', 'runtime_inventory', 'migration_068 Cloudflare read-only endpoint', 'Cloudflare List DNS Records', 'cloudflare_api', 'http_client_backend', 'cloudflare', 'read_only', '2026-05-17', 'active', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'admin', '{"operationId":"cloudflareListDnsRecords","summary":"Cloudflare List DNS Records","method":"get","path":"/zones/{zone_id}/dns_records","parameters":[{"name":"zone_id","in":"path","required":true,"schema":{"type":"string"}},{"name":"type","in":"query","required":false,"schema":{"type":"string"}},{"name":"name","in":"query","required":false,"schema":{"type":"string"}}],"responses":{"200":{"description":"Cloudflare API response","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"401":{"description":"Unauthorized","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"403":{"description":"Forbidden","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}}}}'),
  ('ep_cloudflare_api_cf_list_tunnels', 'cloudflare_api', 'cf_list_tunnels', 'cloudflareListTunnels', 'https://api.cloudflare.com/client/v4', 'GET', '/accounts/{account_id}/cfd_tunnel', 'cloudflareListTunnels', 'cloudflare_api__cf_list_tunnels', 'cloudflare_api_connector', 'active', 'validated', 'validating', 'validated', 'ready', 'primary', 'http_delegated', 'TRUE', 'FALSE', 'runtime_inventory', 'migration_068 Cloudflare read-only endpoint', 'Cloudflare List Tunnels', 'cloudflare_api', 'http_client_backend', 'cloudflare', 'read_only', '2026-05-17', 'active', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'admin', '{"operationId":"cloudflareListTunnels","summary":"Cloudflare List Tunnels","method":"get","path":"/accounts/{account_id}/cfd_tunnel","parameters":[{"name":"account_id","in":"path","required":true,"schema":{"type":"string"}},{"name":"name","in":"query","required":false,"schema":{"type":"string"}}],"responses":{"200":{"description":"Cloudflare API response","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"401":{"description":"Unauthorized","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"403":{"description":"Forbidden","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}}}}'),
  ('ep_cloudflare_api_cf_get_tunnel', 'cloudflare_api', 'cf_get_tunnel', 'cloudflareGetTunnel', 'https://api.cloudflare.com/client/v4', 'GET', '/accounts/{account_id}/cfd_tunnel/{tunnel_id}', 'cloudflareGetTunnel', 'cloudflare_api__cf_get_tunnel', 'cloudflare_api_connector', 'active', 'validated', 'validating', 'validated', 'ready', 'primary', 'http_delegated', 'TRUE', 'FALSE', 'runtime_inventory', 'migration_068 Cloudflare read-only endpoint', 'Cloudflare Get Tunnel', 'cloudflare_api', 'http_client_backend', 'cloudflare', 'read_only', '2026-05-17', 'active', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'admin', '{"operationId":"cloudflareGetTunnel","summary":"Cloudflare Get Tunnel","method":"get","path":"/accounts/{account_id}/cfd_tunnel/{tunnel_id}","parameters":[{"name":"account_id","in":"path","required":true,"schema":{"type":"string"}},{"name":"tunnel_id","in":"path","required":true,"schema":{"type":"string"}}],"responses":{"200":{"description":"Cloudflare API response","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"401":{"description":"Unauthorized","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}},"403":{"description":"Forbidden","content":{"application/json":{"schema":{"type":"object","additionalProperties":true}}}}}}')
ON DUPLICATE KEY UPDATE
  parent_action_key = VALUES(parent_action_key), endpoint_key = VALUES(endpoint_key), endpoint_operation = VALUES(endpoint_operation), provider_domain = VALUES(provider_domain), method = VALUES(method), endpoint_path_or_function = VALUES(endpoint_path_or_function), route_target = VALUES(route_target), openai_action_name = VALUES(openai_action_name), connector_family = VALUES(connector_family), status = VALUES(status), spec_validation_status = VALUES(spec_validation_status), auth_validation_status = VALUES(auth_validation_status), privacy_validation_status = VALUES(privacy_validation_status), execution_readiness = VALUES(execution_readiness), endpoint_role = VALUES(endpoint_role), execution_mode = VALUES(execution_mode), transport_required = VALUES(transport_required), fallback_allowed = VALUES(fallback_allowed), inventory_role = VALUES(inventory_role), notes = VALUES(notes), endpoint_title = VALUES(endpoint_title), provider_family = VALUES(provider_family), execution_layer = VALUES(execution_layer), category_group = VALUES(category_group), category_detail = VALUES(category_detail), last_reviewed_at = VALUES(last_reviewed_at), legacy_status = VALUES(legacy_status), client_interface_agnostic = VALUES(client_interface_agnostic), request_envelope_required = VALUES(request_envelope_required), structured_api_supported = VALUES(structured_api_supported), conversational_trigger_supported = VALUES(conversational_trigger_supported), writeback_scope = VALUES(writeback_scope), schema_json = VALUES(schema_json), updated_at = CURRENT_TIMESTAMP;

INSERT INTO `app_integration_action_bindings`
  (`binding_id`, `app_key`, `action_key`, `binding_role`, `credential_source`, `exposure_default`, `status`, `notes`)
VALUES
  ('bind_cloudflare_api', 'cloudflare', 'cloudflare_api', 'primary_api', 'platform_managed', 'curated_exports', 'active', 'Cloudflare app now has first-class read-only REST capability in addition to connector_cf workaround tooling')
ON DUPLICATE KEY UPDATE
  app_key = VALUES(app_key), action_key = VALUES(action_key), binding_role = VALUES(binding_role), credential_source = VALUES(credential_source), exposure_default = VALUES(exposure_default), status = VALUES(status), notes = VALUES(notes), updated_at = CURRENT_TIMESTAMP;

INSERT INTO `platform_endpoint_tool_exports`
  (`export_key`, `parent_action_key`, `endpoint_key`, `tool_name`, `scope_class`, `status`, `import_policy_json`, `input_schema_json`, `output_schema_json`, `auth_policy_json`, `execution_policy_json`, `notes`)
VALUES
  ('cloudflare_api__cf_list_zones', 'cloudflare_api', 'cf_list_zones', 'cloudflare_api__cf_list_zones', 'admin', 'active', '{"source":"migration_068","read_only":true}', '{"type":"object","properties":{"path_params":{"type":"object","additionalProperties":true},"query":{"type":"object","additionalProperties":true},"body":{"type":"object","additionalProperties":true},"headers":{"type":"object","additionalProperties":true},"timeout_seconds":{"type":"integer","minimum":1,"maximum":120},"readback":{"type":"object","additionalProperties":true}},"required":[]}', '{"type":"object","additionalProperties":true}', '{"requires_admin":true,"auth_source":"registry","parent_action_key":"cloudflare_api","provider_domain":"https://api.cloudflare.com/client/v4"}', '{"runtime_callable":true,"read_only":true,"method":"GET","execution_mode":"http_delegated","transport_required":"TRUE"}', 'Cloudflare read-only export'),
  ('cloudflare_api__cf_list_dns_records', 'cloudflare_api', 'cf_list_dns_records', 'cloudflare_api__cf_list_dns_records', 'admin', 'active', '{"source":"migration_068","read_only":true}', '{"type":"object","properties":{"path_params":{"type":"object","additionalProperties":true},"query":{"type":"object","additionalProperties":true},"body":{"type":"object","additionalProperties":true},"headers":{"type":"object","additionalProperties":true},"timeout_seconds":{"type":"integer","minimum":1,"maximum":120},"readback":{"type":"object","additionalProperties":true}},"required":[]}', '{"type":"object","additionalProperties":true}', '{"requires_admin":true,"auth_source":"registry","parent_action_key":"cloudflare_api","provider_domain":"https://api.cloudflare.com/client/v4"}', '{"runtime_callable":true,"read_only":true,"method":"GET","execution_mode":"http_delegated","transport_required":"TRUE"}', 'Cloudflare read-only export'),
  ('cloudflare_api__cf_list_tunnels', 'cloudflare_api', 'cf_list_tunnels', 'cloudflare_api__cf_list_tunnels', 'admin', 'active', '{"source":"migration_068","read_only":true}', '{"type":"object","properties":{"path_params":{"type":"object","additionalProperties":true},"query":{"type":"object","additionalProperties":true},"body":{"type":"object","additionalProperties":true},"headers":{"type":"object","additionalProperties":true},"timeout_seconds":{"type":"integer","minimum":1,"maximum":120},"readback":{"type":"object","additionalProperties":true}},"required":[]}', '{"type":"object","additionalProperties":true}', '{"requires_admin":true,"auth_source":"registry","parent_action_key":"cloudflare_api","provider_domain":"https://api.cloudflare.com/client/v4"}', '{"runtime_callable":true,"read_only":true,"method":"GET","execution_mode":"http_delegated","transport_required":"TRUE"}', 'Cloudflare read-only export'),
  ('cloudflare_api__cf_get_tunnel', 'cloudflare_api', 'cf_get_tunnel', 'cloudflare_api__cf_get_tunnel', 'admin', 'active', '{"source":"migration_068","read_only":true}', '{"type":"object","properties":{"path_params":{"type":"object","additionalProperties":true},"query":{"type":"object","additionalProperties":true},"body":{"type":"object","additionalProperties":true},"headers":{"type":"object","additionalProperties":true},"timeout_seconds":{"type":"integer","minimum":1,"maximum":120},"readback":{"type":"object","additionalProperties":true}},"required":[]}', '{"type":"object","additionalProperties":true}', '{"requires_admin":true,"auth_source":"registry","parent_action_key":"cloudflare_api","provider_domain":"https://api.cloudflare.com/client/v4"}', '{"runtime_callable":true,"read_only":true,"method":"GET","execution_mode":"http_delegated","transport_required":"TRUE"}', 'Cloudflare read-only export')
ON DUPLICATE KEY UPDATE
  parent_action_key = VALUES(parent_action_key), endpoint_key = VALUES(endpoint_key), tool_name = VALUES(tool_name), scope_class = VALUES(scope_class), status = VALUES(status), import_policy_json = VALUES(import_policy_json), input_schema_json = VALUES(input_schema_json), output_schema_json = VALUES(output_schema_json), auth_policy_json = VALUES(auth_policy_json), execution_policy_json = VALUES(execution_policy_json), notes = VALUES(notes), updated_at = CURRENT_TIMESTAMP;
