INSERT INTO runtime_dispatch_certification_registry (
  certification_key,
  surface_key,
  surface_family,
  tool_or_action_key,
  risk_class,
  certification_status,
  smoke_strategy,
  dispatch_allowed,
  apply_allowed,
  requires_resource_authority,
  requires_dry_run,
  requires_audit_evidence,
  requires_readback,
  last_evidence_ref,
  last_certified_at,
  expires_at,
  notes
)
VALUES (
  'remote_runtime_hostinger_deploy_release',
  'remote_runtime_hostinger_deploy_release',
  'remote_runtime_hostinger_deploy',
  'remote_runtime_hostinger_deploy_release',
  'high',
  'positive_dry_run_passed_execution_gated_certified',
  'bounded_evidence_readback',
  1,
  0,
  1,
  1,
  1,
  1,
  'release_readiness_55cff305_ebe6_4616_88a0_4e19040937f4_runtime_verification_ea0a81a9_ssh_probe_dry_run_dispatch_ready_true',
  NOW(),
  DATE_ADD(NOW(), INTERVAL 30 DAY),
  'Renewed after Spec 006 post-merge readiness pass and production parity gap evidence. Dispatch only; actual deploy still requires capability envelope, approval, audit, and readback.'
)
ON DUPLICATE KEY UPDATE
  surface_key = VALUES(surface_key),
  surface_family = VALUES(surface_family),
  tool_or_action_key = VALUES(tool_or_action_key),
  risk_class = VALUES(risk_class),
  certification_status = VALUES(certification_status),
  smoke_strategy = VALUES(smoke_strategy),
  dispatch_allowed = VALUES(dispatch_allowed),
  apply_allowed = VALUES(apply_allowed),
  requires_resource_authority = VALUES(requires_resource_authority),
  requires_dry_run = VALUES(requires_dry_run),
  requires_audit_evidence = VALUES(requires_audit_evidence),
  requires_readback = VALUES(requires_readback),
  last_evidence_ref = VALUES(last_evidence_ref),
  last_certified_at = VALUES(last_certified_at),
  expires_at = VALUES(expires_at),
  notes = VALUES(notes);
