-- Sprint 62p: Platform Knowledge Graph Runtime foundation
-- Canonical SQL-primary graph tables with advisory-first runtime projection.

CREATE TABLE IF NOT EXISTS `platform_graph_taxonomy` (
  `taxonomy_key` VARCHAR(160) NOT NULL,
  `taxonomy_type` ENUM('node_type','edge_type','scope_type','authority_status','lifecycle_status','visibility_scope','sensitivity','evidence_level','runtime_role') NOT NULL,
  `taxonomy_value` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `runtime_enforced` TINYINT(1) NOT NULL DEFAULT 0,
  `validation_rule_json` JSON NULL,
  `status` ENUM('active','archived') NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`taxonomy_key`),
  UNIQUE KEY `uq_platform_graph_taxonomy_type_value` (`taxonomy_type`, `taxonomy_value`),
  KEY `idx_platform_graph_taxonomy_status` (`taxonomy_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_nodes` (
  `node_id` VARCHAR(255) NOT NULL,
  `node_type` VARCHAR(120) NOT NULL,
  `node_label` VARCHAR(500) NULL,
  `scope_type` VARCHAR(80) NOT NULL DEFAULT 'platform',
  `subject_ref` VARCHAR(255) NULL,
  `source_table` VARCHAR(120) NULL,
  `source_pk` VARCHAR(255) NULL,
  `authority_status` VARCHAR(80) NOT NULL DEFAULT 'candidate',
  `lifecycle_status` VARCHAR(80) NOT NULL DEFAULT 'active',
  `visibility_scope` VARCHAR(120) NOT NULL DEFAULT 'platform_admin',
  `sensitivity` VARCHAR(80) NOT NULL DEFAULT 'internal',
  `evidence_level` VARCHAR(80) NOT NULL DEFAULT 'declared',
  `runtime_role` VARCHAR(80) NOT NULL DEFAULT 'advisory',
  `source_system` VARCHAR(80) NOT NULL DEFAULT 'sql',
  `metadata_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`node_id`),
  KEY `idx_platform_graph_nodes_type` (`node_type`, `lifecycle_status`),
  KEY `idx_platform_graph_nodes_scope` (`scope_type`, `subject_ref`),
  KEY `idx_platform_graph_nodes_source` (`source_table`, `source_pk`),
  KEY `idx_platform_graph_nodes_runtime` (`runtime_role`, `authority_status`, `lifecycle_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_edges` (
  `edge_id` VARCHAR(255) NOT NULL,
  `source_node_id` VARCHAR(255) NOT NULL,
  `edge_type` VARCHAR(120) NOT NULL,
  `target_node_id` VARCHAR(255) NOT NULL,
  `scope_type` VARCHAR(80) NOT NULL DEFAULT 'platform',
  `authority_status` VARCHAR(80) NOT NULL DEFAULT 'candidate',
  `lifecycle_status` VARCHAR(80) NOT NULL DEFAULT 'active',
  `visibility_scope` VARCHAR(120) NOT NULL DEFAULT 'platform_admin',
  `sensitivity` VARCHAR(80) NOT NULL DEFAULT 'internal',
  `evidence_level` VARCHAR(80) NOT NULL DEFAULT 'declared',
  `runtime_role` VARCHAR(80) NOT NULL DEFAULT 'advisory',
  `runtime_enforced` TINYINT(1) NOT NULL DEFAULT 0,
  `source_table` VARCHAR(120) NULL,
  `source_pk` VARCHAR(255) NULL,
  `metadata_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`edge_id`),
  KEY `idx_platform_graph_edges_source` (`source_node_id`, `edge_type`, `lifecycle_status`),
  KEY `idx_platform_graph_edges_target` (`target_node_id`, `edge_type`, `lifecycle_status`),
  KEY `idx_platform_graph_edges_type` (`edge_type`, `runtime_enforced`, `lifecycle_status`),
  KEY `idx_platform_graph_edges_source_table` (`source_table`, `source_pk`),
  CONSTRAINT `fk_platform_graph_edges_source` FOREIGN KEY (`source_node_id`) REFERENCES `platform_graph_nodes` (`node_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_platform_graph_edges_target` FOREIGN KEY (`target_node_id`) REFERENCES `platform_graph_nodes` (`node_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_edge_evidence` (
  `evidence_id` VARCHAR(64) NOT NULL,
  `edge_id` VARCHAR(255) NOT NULL,
  `evidence_type` VARCHAR(80) NOT NULL DEFAULT 'source_row',
  `source_table` VARCHAR(120) NULL,
  `source_pk` VARCHAR(255) NULL,
  `source_ref` VARCHAR(500) NULL,
  `confidence` DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
  `evidence_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`evidence_id`),
  KEY `idx_platform_graph_edge_evidence_edge` (`edge_id`),
  CONSTRAINT `fk_platform_graph_edge_evidence_edge` FOREIGN KEY (`edge_id`) REFERENCES `platform_graph_edges` (`edge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_projection_runs` (
  `run_id` VARCHAR(64) NOT NULL,
  `projection_key` VARCHAR(160) NOT NULL,
  `projection_mode` VARCHAR(80) NOT NULL DEFAULT 'advisory_projection',
  `status` ENUM('running','completed','failed') NOT NULL DEFAULT 'running',
  `source_counts_json` JSON NULL,
  `result_counts_json` JSON NULL,
  `warnings_json` JSON NULL,
  `error_json` JSON NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`run_id`),
  KEY `idx_platform_graph_projection_runs_key` (`projection_key`, `status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_validation_runs` (
  `run_id` VARCHAR(64) NOT NULL,
  `validation_key` VARCHAR(160) NOT NULL,
  `status` ENUM('running','passed','failed','warning') NOT NULL DEFAULT 'running',
  `checked_nodes` INT NOT NULL DEFAULT 0,
  `checked_edges` INT NOT NULL DEFAULT 0,
  `failure_count` INT NOT NULL DEFAULT 0,
  `warning_count` INT NOT NULL DEFAULT 0,
  `results_json` JSON NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`run_id`),
  KEY `idx_platform_graph_validation_runs_key` (`validation_key`, `status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `platform_graph_query_log` (
  `query_id` VARCHAR(64) NOT NULL,
  `query_type` VARCHAR(120) NOT NULL,
  `subject_type` VARCHAR(120) NULL,
  `subject_ref` VARCHAR(255) NULL,
  `input_json` JSON NULL,
  `result_summary_json` JSON NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`query_id`),
  KEY `idx_platform_graph_query_log_subject` (`subject_type`, `subject_ref`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `platform_graph_taxonomy` (`taxonomy_key`, `taxonomy_type`, `taxonomy_value`, `description`, `runtime_enforced`) VALUES
('node_type.platform','node_type','platform','Platform-global node',1),
('node_type.tenant','node_type','tenant','Tenant or organization node',1),
('node_type.user','node_type','user','User identity node',1),
('node_type.membership','node_type','membership','User-to-tenant membership node',1),
('node_type.device','node_type','device','Local device or installed app device node',1),
('node_type.local_app','node_type','local_app','Installed/public local app catalog node',1),
('node_type.release','node_type','release','Application release node',1),
('node_type.json_asset','node_type','json_asset','Governed JSON asset or memory artifact',1),
('node_type.business_type','node_type','business_type','Business type/profile node',1),
('node_type.knowledge_profile','node_type','knowledge_profile','Business or logic knowledge profile node',1),
('node_type.knowledge_surface','node_type','knowledge_surface','Drive/file/db knowledge surface node',1),
('node_type.intent','node_type','intent','User intent or task intent node',1),
('node_type.task_route','node_type','task_route','Task route registry node',1),
('node_type.workflow','node_type','workflow','Workflow registry node',1),
('node_type.module','node_type','module','Target module node',1),
('node_type.action','node_type','action','Action registry node',1),
('node_type.endpoint','node_type','endpoint','Endpoint registry node',1),
('node_type.execution_trace','node_type','execution_trace','Execution trace/log node',1),
('node_type.contract','node_type','contract','Legacy platform contract graph node',0),
('edge_type.owns','edge_type','owns','Ownership edge',1),
('edge_type.member_of','edge_type','member_of','Membership edge',1),
('edge_type.attached_to','edge_type','attached_to','Asset or memory attachment edge',1),
('edge_type.linked_to','edge_type','linked_to','Device/session/user/tenant link edge',1),
('edge_type.released_as','edge_type','released_as','App-to-release edge',1),
('edge_type.routes_to','edge_type','routes_to','Intent-to-route edge',1),
('edge_type.triggers','edge_type','triggers','Route/workflow trigger edge',1),
('edge_type.uses','edge_type','uses','Dependency/use edge',1),
('edge_type.exposes','edge_type','exposes','Action exposes endpoint edge',1),
('edge_type.activates','edge_type','activates','Business type activates profile/surface edge',1),
('edge_type.produced','edge_type','produced','Execution produced artifact edge',1),
('edge_type.maps_to','edge_type','maps_to','Contract or route mapping edge',0),
('scope_type.platform','scope_type','platform','Platform scoped',1),
('scope_type.tenant','scope_type','tenant','Tenant scoped',1),
('scope_type.user','scope_type','user','User scoped',1),
('scope_type.device','scope_type','device','Device scoped',1),
('scope_type.brand','scope_type','brand','Brand scoped',1),
('scope_type.workflow','scope_type','workflow','Workflow scoped',1),
('authority_status.authoritative','authority_status','authoritative','Authoritative graph fact',1),
('authority_status.candidate','authority_status','candidate','Candidate graph fact',1),
('authority_status.advisory','authority_status','advisory','Advisory graph fact',1),
('lifecycle_status.active','lifecycle_status','active','Active row/node/edge',1),
('lifecycle_status.archived','lifecycle_status','archived','Archived row/node/edge',1),
('sensitivity.public','sensitivity','public','Public-safe',1),
('sensitivity.internal','sensitivity','internal','Internal platform metadata',1),
('sensitivity.tenant_private','sensitivity','tenant_private','Tenant-private metadata',1),
('sensitivity.user_private','sensitivity','user_private','User-private metadata',1),
('sensitivity.secret_reference','sensitivity','secret_reference','Secret reference only, never raw secret',1),
('evidence_level.declared','evidence_level','declared','Declared by registry/source row',1),
('evidence_level.verified','evidence_level','verified','Verified by live validation/probe',1),
('runtime_role.authority','runtime_role','authority','Runtime authority',1),
('runtime_role.resolver_input','runtime_role','resolver_input','Resolver input',1),
('runtime_role.advisory','runtime_role','advisory','Advisory graph fact',1),
('runtime_role.audit_only','runtime_role','audit_only','Audit-only graph fact',1)
ON DUPLICATE KEY UPDATE
  `description` = VALUES(`description`),
  `runtime_enforced` = VALUES(`runtime_enforced`),
  `status` = 'active',
  `updated_at` = CURRENT_TIMESTAMP;
