-- Sprint 65: register Platform Tool Manifest as an execution authority surface.
-- The manifest resolver reads admin_platform_endpoint_tools plus plugin tool bindings
-- to explain available governed tools without exposing raw credential material.

INSERT INTO registry_surfaces_catalog
  (surface_id, logical_surface_key, surface_name, surface_type, surface_scope,
   storage_type, worksheet_name, active_status, authority_status,
   required_for_execution, resolution_rule, owner_layer, schema_ref,
   schema_version, binding_mode, sheet_role, audit_mode, backend_type,
   backend_adapter, authority_model, portability_class,
   repair_candidate_types, repair_priority, notes)
VALUES
  ('surface.platform_tool_manifest',
   'surface.platform_tool_manifest',
   'Platform Tool Manifest',
   'registry',
   'runtime',
   'sql_table',
   'Platform Tool Manifest',
   'active',
   'authoritative',
   'TRUE',
   'sql_primary',
   'governed_context_resolution',
   'admin_platform_endpoint_tools',
   'v1',
   'sql_runtime_authority',
   'runtime_tool_manifest',
   'exact_header_match',
   'sql',
   'governed_context_resolution.admin_platform_endpoint_tools',
   'sql_runtime_authority',
   'runtime_tool_manifest_authority',
   'surface_authority|tool_readback|plugin_tool_binding_integrity|schema_contract_integrity',
   'high',
   'Runtime tool manifest surface. Plugin tool bindings live in app_integration_tool_bindings; tool definitions live in admin_platform_endpoint_tools.')
ON DUPLICATE KEY UPDATE
  logical_surface_key = VALUES(logical_surface_key),
  surface_name = VALUES(surface_name),
  surface_type = VALUES(surface_type),
  surface_scope = VALUES(surface_scope),
  storage_type = VALUES(storage_type),
  worksheet_name = VALUES(worksheet_name),
  active_status = VALUES(active_status),
  authority_status = VALUES(authority_status),
  required_for_execution = VALUES(required_for_execution),
  resolution_rule = VALUES(resolution_rule),
  owner_layer = VALUES(owner_layer),
  schema_ref = VALUES(schema_ref),
  schema_version = VALUES(schema_version),
  binding_mode = VALUES(binding_mode),
  sheet_role = VALUES(sheet_role),
  audit_mode = VALUES(audit_mode),
  backend_type = VALUES(backend_type),
  backend_adapter = VALUES(backend_adapter),
  authority_model = VALUES(authority_model),
  portability_class = VALUES(portability_class),
  repair_candidate_types = VALUES(repair_candidate_types),
  repair_priority = VALUES(repair_priority),
  notes = VALUES(notes),
  updated_at = CURRENT_TIMESTAMP;
