-- Sprint 65: document guarded dispatch context and provider smoke controls.
-- This updates the registered admin tool schema only. Actual provider calls remain
-- guarded by execution readiness, action grants, HTTPS/private-network checks, and
-- explicit provider_smoke_expected_origin when provider_smoke=true.

UPDATE `admin_platform_endpoint_tools`
   SET `description` = 'Execute a promoted or tenant-installed Platform Plugin REST action only after full execution readiness passes. Supports dry_run and controlled provider_smoke for GET-only transport verification with explicit expected origin. Credentials remain server-side and secrets are never returned.',
       `input_schema` = '{"type":"object","required":["plugin_key","action_key","tenant_id","user_id"],"properties":{"plugin_key":{"type":"string"},"action_key":{"type":"string"},"tenant_id":{"type":"string"},"user_id":{"type":"string"},"agent_id":{"type":"string"},"requested_credential_scope":{"type":"string","default":"tenant_connection"},"input":{"type":"object","additionalProperties":true},"dry_run":{"type":"boolean","default":false},"timeout_ms":{"type":"integer","minimum":1000,"maximum":30000,"default":10000},"enforce_execution_readiness":{"type":"boolean","default":true},"brand_key":{"type":"string"},"target_key":{"type":"string"},"business_type_key":{"type":"string"},"business_activity_type_key":{"type":"string"},"workflow_key":{"type":"string"},"logic_key":{"type":"string"},"logic_pack_key":{"type":"string"},"skill_key":{"type":"string"},"actor_role":{"type":"string"},"governance_level":{"type":"string"},"graph_depth":{"type":"integer","minimum":0,"maximum":3,"default":1},"graph_limit":{"type":"integer","minimum":1,"maximum":250,"default":120},"detail_limit":{"type":"integer","minimum":1,"maximum":50,"default":10},"edge_detail_limit":{"type":"integer","minimum":1,"maximum":80,"default":10},"provider_smoke":{"type":"boolean","default":false},"provider_smoke_expected_origin":{"type":"string"}},"additionalProperties":false}',
       `tags` = 'admin,platform-plugin,platform-plugins,dispatch,rest,state_changing,audited,no_secrets,approval_gate,execution_readiness,provider_smoke,origin_guard',
       `updated_at` = CURRENT_TIMESTAMP
 WHERE `tool_key` = 'platform_plugin_dispatch_rest';
