-- Sprint 65: WordPress blog publish credential recovery orchestrator
-- Additive/idempotent registry seed. Keeps WordPress publishing platform-native;
-- n8n remains auxiliary only through governed workflow_runtime_bindings.

INSERT INTO `workflows` (
  `workflow_id`, `workflow_key`, `workflow_name`, `module_mode`, `trigger_source`,
  `input_type`, `primary_objective`, `mapped_engines`, `engine_order`, `workflow_type`,
  `primary_output`, `input_detection_rules`, `output_template`, `priority`, `route_key`,
  `execution_mode`, `user_facing`, `parent_layer`, `status`, `linked_workflows`,
  `linked_engines`, `notes`, `entry_priority_weight`, `dependency_type`,
  `output_artifact_type`, `active`, `target_module`, `execution_class`, `lifecycle_mode`,
  `route_compatibility`, `memory_required`, `logging_required`, `review_required`,
  `allowed_states`, `degraded_action`, `blocked_action`, `registry_source`,
  `last_validated_at`, `required_variable_profile`, `input_contract_profile`,
  `supported_ingress_channels`, `supports_structured_api_calls`,
  `supported_model_providers`, `model_adapter_required`, `allowed_actor_roles`,
  `allowed_governance_levels`, `client_allowed`, `team_allowed`, `admin_only`,
  `brand_scope_enforced`, `supported_languages`, `translation_step_required`,
  `locale_sensitive`
) VALUES (
  'wf_wordpress_blog_publish_or_recover_credentials',
  'wordpress_blog_publish_or_recover_credentials_workflow',
  'WordPress Blog Publish or Recover Credentials',
  'platform_native',
  'user_intent',
  'brand_scoped_publish_request',
  'Resolve brand/target, verify WordPress credentials, create secure credential intake when missing, resume the preserved publish request, create the WordPress post, and return readback evidence.',
  'content_generation_workflow; seo_strategy_workflow; publish_preflight_validation_workflow; credential_effective_status; credential_intake_session_create; wf_wordpress_content_ops; wordpress_publish_approval_workflow; repair_resume_draft_publish_workflow',
  '1 brand_target_resolve > 2 publish_preflight > 3 credential_effective_status > 4 credential_intake_if_missing > 5 resume_original_request > 6 wordpress_create_post > 7 readback_verification > 8 execution_log',
  'Chain',
  'WordPress draft or published post with credential resolution evidence, post_id, link, and readback status',
  'Arabic/English requests to publish a blog/article/post to a resolved brand WordPress site, especially when credential recovery may be required.',
  'Return compact execution evidence: brand, target_key, credential_status, intake_url_if_created, post_status, post_id, link, readback_status.',
  'high',
  'wordpress_blog_publish_or_recover_credentials',
  'Chain',
  'TRUE',
  'wordpress_publish_contract',
  'Active',
  'content_generation_workflow; seo_strategy_workflow; publish_preflight_validation_workflow; wf_wordpress_content_ops; wordpress_publish_approval_workflow; repair_resume_draft_publish_workflow',
  'credential_effective_status; credential_intake_session_create; wordpress_create_post; wordpress_get_post',
  'Platform-native orchestration is authoritative for WordPress publishing. n8n may only be auxiliary for notifications or post-publish automation and must not bypass platform auth, registry scope, credential resolver, readback, or logging.',
  '100',
  'credential_or_publish_dependency',
  'wordpress_blog_post',
  'TRUE',
  'wordpress_blog_publish_orchestrator',
  'governed',
  'resume_aware',
  'wordpress_content_ops; publish_preflight_validation; wordpress_publish_approval_gate; repair_failed_draft_publish',
  'TRUE',
  'TRUE',
  'TRUE',
  'credential_missing:intake_required; credential_resolved:resume_publish; preflight_blocked:block; draft_created:verify; publish_requested:approval_gate; readback_failed:repair_resume',
  'create_credential_intake_and_hold_original_publish_request',
  'block_if_brand_target_preflight_or_credential_resolution_unavailable',
  'sql_registry',
  '2026-05-28T00:00:00Z',
  'brand_key,target_key,title,content,status,language,seo_fields,credential_role,connection_id',
  'Requires brand or target_key; title/content or content_generation_request; publish_status draft|publish; credential role wordpress_rest; never accepts raw secrets.',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'TRUE',
  'governed_default',
  'FALSE',
  'admin; tenant_owner; brand_operator',
  'governed; brand_scoped; credential_safe',
  'TRUE',
  'TRUE',
  'FALSE',
  'TRUE',
  'ar; en',
  'conditional',
  'TRUE'
) ON DUPLICATE KEY UPDATE
  `workflow_name` = VALUES(`workflow_name`),
  `primary_objective` = VALUES(`primary_objective`),
  `mapped_engines` = VALUES(`mapped_engines`),
  `engine_order` = VALUES(`engine_order`),
  `primary_output` = VALUES(`primary_output`),
  `notes` = VALUES(`notes`),
  `active` = VALUES(`active`),
  `status` = VALUES(`status`),
  `target_module` = VALUES(`target_module`),
  `execution_class` = VALUES(`execution_class`),
  `updated_at` = CURRENT_TIMESTAMP;

INSERT INTO `task_routes` (
  `task_key`, `trigger_terms`, `route_modules`, `execution_layer`, `priority`,
  `enabled`, `output_focus`, `notes`, `entry_sources`, `linked_starter_titles`,
  `active_starter_count`, `route_key_match_status`, `row_id`, `route_id`, `active`,
  `intent_key`, `brand_scope`, `request_type`, `route_mode`, `target_module`,
  `workflow_key`, `lifecycle_mode`, `memory_required`, `logging_required`,
  `review_required`, `allowed_states`, `degraded_action`, `blocked_action`,
  `match_rule`, `route_source`, `last_validated_at`, `required_variable_profile`,
  `variable_contract_group`, `supported_ingress_channels`,
  `requires_conversational_inference`, `supports_structured_api_calls`,
  `supported_model_providers`, `allowed_actor_roles`, `allowed_governance_levels`,
  `client_allowed`, `team_allowed`, `admin_only`, `brand_scope_enforced`,
  `supported_languages`, `translation_step_required`, `locale_sensitive`
) VALUES (
  'wordpress_blog_publish_or_recover_credentials',
  'انشر موضوع بلوج; انشر المقال; انشر الموضوع; publish blog; publish article; wordpress blog publish; create blog post; credential intake then publish; recover credential and resume publish',
  'prompt_router; module_loader; system_bootstrap; credential_resolver; wordpress_publish_contract',
  'platform_native',
  'high',
  'TRUE',
  'Seamless WordPress blog publish with credential recovery, original-request resume, post create, and readback link.',
  'Routes brand-scoped WordPress blog publishing to platform-native orchestration. n8n is auxiliary only unless a governed workflow_runtime_binding authorizes non-authoritative side effects.',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'Publish a blog post; Publish article to WordPress; Resume WordPress publish after credential intake',
  '0',
  'matched_to_active_workflow',
  'route.wordpress_blog_publish_or_recover_credentials.global.v1',
  'route.wordpress_blog_publish_or_recover_credentials.global.v1',
  'TRUE',
  'wordpress_blog_publish_or_recover_credentials',
  'brand_required',
  'publish',
  'governed',
  'wordpress_blog_publish_orchestrator',
  'wordpress_blog_publish_or_recover_credentials_workflow',
  'resume_aware',
  'TRUE',
  'TRUE',
  'TRUE',
  'credential_missing:intake_required; credential_resolved:resume_publish; draft_created:verify; publish_requested:approval_gate; readback_failed:repair_resume',
  'create_credential_intake_and_hold_original_publish_request',
  'block_if_brand_core_target_preflight_or_credential_resolution_unavailable',
  'keyword_trigger_match + brand_scope_required + wordpress_target_required',
  'sql_registry',
  '2026-05-28T00:00:00Z',
  'brand_key,target_key,title,content,status,language,seo_fields,credential_role,connection_id',
  'wordpress_blog_publish_v1',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'TRUE',
  'TRUE',
  'governed_default',
  'admin; tenant_owner; brand_operator',
  'governed; brand_scoped; credential_safe',
  'TRUE',
  'TRUE',
  'FALSE',
  'TRUE',
  'ar; en',
  'conditional',
  'TRUE'
) ON DUPLICATE KEY UPDATE
  `trigger_terms` = VALUES(`trigger_terms`),
  `route_modules` = VALUES(`route_modules`),
  `enabled` = VALUES(`enabled`),
  `output_focus` = VALUES(`output_focus`),
  `notes` = VALUES(`notes`),
  `active` = VALUES(`active`),
  `workflow_key` = VALUES(`workflow_key`),
  `updated_at` = CURRENT_TIMESTAMP;
