-- Sprint 65: WordPress blog publish orchestrator
-- Purpose: make brand-scoped blog publishing seamless by routing publish intent
-- through platform-native credential resolution, secure credential intake when
-- required, same-request resume, draft-first WordPress create, approval-aware
-- publish promotion, and readback verification.

INSERT INTO `workflows` (
  `workflow_id`, `workflow_key`, `workflow_name`, `module_mode`, `trigger_source`,
  `input_type`, `primary_objective`, `mapped_engines`, `engine_order`,
  `workflow_type`, `primary_output`, `input_detection_rules`, `output_template`,
  `priority`, `route_key`, `execution_mode`, `user_facing`, `parent_layer`,
  `status`, `linked_workflows`, `linked_engines`, `notes`, `entry_priority_weight`,
  `dependency_type`, `output_artifact_type`, `active`, `target_module`,
  `execution_class`, `lifecycle_mode`, `route_compatibility`, `memory_required`,
  `logging_required`, `review_required`, `allowed_states`, `degraded_action`,
  `blocked_action`, `registry_source`, `last_validated_at`,
  `required_variable_profile`, `input_contract_profile`, `supported_ingress_channels`,
  `supports_structured_api_calls`, `supported_model_providers`, `model_adapter_required`,
  `allowed_actor_roles`, `allowed_governance_levels`, `client_allowed`, `team_allowed`,
  `admin_only`, `brand_scope_enforced`, `supported_languages`,
  `translation_step_required`, `locale_sensitive`
) VALUES (
  'wf_wordpress_blog_publish_or_recover_credentials',
  'wordpress_blog_publish_or_recover_credentials_workflow',
  'WordPress Blog Publish or Recover Credentials',
  'platform_native',
  'user_intent',
  'brand_scoped_publish_request',
  'Orchestrate a seamless brand-resolved WordPress blog publishing flow: resolve brand and target, verify Brand Core and publish preflight, check effective WordPress credential, create secure credential-intake and hold original request when missing, resume same publish request after credential resolution, create draft-first post through governed WordPress content operations, run approval-aware publish promotion when requested, and verify readback/link output.',
  'content_generation_workflow; seo_strategy_workflow; publish_preflight_validation_workflow; credential_effective_status; credential_intake_session_create; wf_wordpress_content_ops; wordpress_publish_approval_workflow; repair_resume_draft_publish_workflow',
  '1 brand_target_resolve > 2 content_and_seo_prepare > 3 publish_preflight > 4 credential_effective_status > 5 credential_intake_if_missing > 6 resume_original_request > 7 wordpress_create_post_draft_first > 8 approval_or_publish_promotion > 9 readback_verification > 10 execution_log',
  'Chain',
  'WordPress draft or published post with post_id, link, credential resolution evidence, and readback status',
  'Arabic/English requests to publish a blog/article/post to a resolved brand WordPress site, especially when credential recovery or credential intake may be required.',
  'Return compact execution evidence: brand, target_key, credential_status, intake_url_if_created, resumed_from_intake, post_status, post_id, link, readback_status.',
  'high',
  'wordpress_blog_publish_or_recover_credentials',
  'Chain',
  'TRUE',
  'wordpress_publish_contract',
  'Active',
  'content_generation_workflow; seo_strategy_workflow; publish_preflight_validation_workflow; wf_wordpress_content_ops; wordpress_publish_approval_workflow; repair_resume_draft_publish_workflow',
  'credential_effective_status; credential_intake_session_create; wordpress_create_post; wordpress_get_post',
  'Platform-native orchestration is authoritative for WordPress publishing. n8n may be used only as an auxiliary governed workflow_runtime binding for notifications or post-publish automation; it must not bypass platform auth, registry scope, credential resolver, WordPress publish contract, readback, or execution logging.',
  '100',
  'credential_or_publish_dependency',
  'wordpress_blog_post',
  'TRUE',
  'wordpress_blog_publish_orchestrator',
  'governed',
  'resume_aware',
  'wordpress_content_ops; publish_preflight_validation; wordpress_publish_approval_gate; repair_failed_draft_publish',
  'TRUE',
  'TRUE',
  'TRUE',
  'credential_missing:intake_required; credential_resolved:resume_publish; preflight_blocked:block; draft_created:verify; publish_requested:approval_gate; readback_failed:repair_resume',
  'create_credential_intake_and_hold_original_publish_request',
  'block_if_brand_target_preflight_or_credential_resolution_unavailable',
  'sql_registry',
  '2026-05-27T00:00:00Z',
  'brand_key,target_key,title,content,status,language,seo_fields,credential_role,connection_id',
  'Requires brand or target_key; title/content or content_generation_request; publish_status draft|publish; credential role wordpress_rest; never accepts raw secrets.',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'TRUE',
  'governed_default',
  'FALSE',
  'admin; tenant_owner; brand_operator',
  'governed; brand_scoped; credential_safe',
  'TRUE',
  'TRUE',
  'FALSE',
  'TRUE',
  'ar; en',
  'conditional',
  'TRUE'
) ON DUPLICATE KEY UPDATE
  `workflow_name` = VALUES(`workflow_name`),
  `primary_objective` = VALUES(`primary_objective`),
  `mapped_engines` = VALUES(`mapped_engines`),
  `engine_order` = VALUES(`engine_order`),
  `primary_output` = VALUES(`primary_output`),
  `input_detection_rules` = VALUES(`input_detection_rules`),
  `output_template` = VALUES(`output_template`),
  `priority` = VALUES(`priority`),
  `route_key` = VALUES(`route_key`),
  `execution_mode` = VALUES(`execution_mode`),
  `user_facing` = VALUES(`user_facing`),
  `status` = VALUES(`status`),
  `linked_workflows` = VALUES(`linked_workflows`),
  `linked_engines` = VALUES(`linked_engines`),
  `notes` = VALUES(`notes`),
  `active` = VALUES(`active`),
  `target_module` = VALUES(`target_module`),
  `execution_class` = VALUES(`execution_class`),
  `lifecycle_mode` = VALUES(`lifecycle_mode`),
  `route_compatibility` = VALUES(`route_compatibility`),
  `memory_required` = VALUES(`memory_required`),
  `logging_required` = VALUES(`logging_required`),
  `review_required` = VALUES(`review_required`),
  `allowed_states` = VALUES(`allowed_states`),
  `degraded_action` = VALUES(`degraded_action`),
  `blocked_action` = VALUES(`blocked_action`),
  `registry_source` = VALUES(`registry_source`),
  `last_validated_at` = VALUES(`last_validated_at`),
  `required_variable_profile` = VALUES(`required_variable_profile`),
  `input_contract_profile` = VALUES(`input_contract_profile`),
  `supported_ingress_channels` = VALUES(`supported_ingress_channels`),
  `supports_structured_api_calls` = VALUES(`supports_structured_api_calls`),
  `allowed_actor_roles` = VALUES(`allowed_actor_roles`),
  `allowed_governance_levels` = VALUES(`allowed_governance_levels`),
  `client_allowed` = VALUES(`client_allowed`),
  `team_allowed` = VALUES(`team_allowed`),
  `admin_only` = VALUES(`admin_only`),
  `brand_scope_enforced` = VALUES(`brand_scope_enforced`),
  `supported_languages` = VALUES(`supported_languages`),
  `translation_step_required` = VALUES(`translation_step_required`),
  `locale_sensitive` = VALUES(`locale_sensitive`),
  `updated_at` = CURRENT_TIMESTAMP;

INSERT INTO `task_routes` (
  `task_key`, `trigger_terms`, `route_modules`, `execution_layer`, `priority`,
  `enabled`, `output_focus`, `notes`, `entry_sources`, `linked_starter_titles`,
  `active_starter_count`, `route_key_match_status`, `row_id`, `route_id`,
  `active`, `intent_key`, `brand_scope`, `request_type`, `route_mode`,
  `target_module`, `workflow_key`, `lifecycle_mode`, `memory_required`,
  `logging_required`, `review_required`, `allowed_states`, `degraded_action`,
  `blocked_action`, `match_rule`, `route_source`, `last_validated_at`,
  `required_variable_profile`, `variable_contract_group`, `supported_ingress_channels`,
  `requires_conversational_inference`, `supports_structured_api_calls`,
  `supported_model_providers`, `allowed_actor_roles`, `allowed_governance_levels`,
  `client_allowed`, `team_allowed`, `admin_only`, `brand_scope_enforced`,
  `supported_languages`, `translation_step_required`, `locale_sensitive`
) VALUES (
  'wordpress_blog_publish_or_recover_credentials',
  'انشر موضوع بلوج; انشر المقال; انشر الموضوع; publish blog; publish article; wordpress blog publish; create blog post; credential intake then publish; recover credential and resume publish',
  'prompt_router; module_loader; system_bootstrap; credential_resolver; wordpress_publish_contract',
  'platform_native',
  'high',
  'TRUE',
  'Seamless WordPress blog publish with credential recovery, original-request resume, draft-first create, optional publish promotion, and readback link.',
  'Routes brand-scoped WordPress blog publishing to platform-native orchestration. n8n is auxiliary only unless a governed workflow_runtime_binding is explicitly added for non-authoritative side effects.',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'Publish a blog post; Publish article to WordPress; Resume WordPress publish after credential intake',
  '0',
  'matched_to_active_workflow',
  'route.wordpress_blog_publish_or_recover_credentials.global.v1',
  'route.wordpress_blog_publish_or_recover_credentials.global.v1',
  'TRUE',
  'wordpress_blog_publish_or_recover_credentials',
  'brand_required',
  'publish',
  'governed',
  'wordpress_blog_publish_orchestrator',
  'wordpress_blog_publish_or_recover_credentials_workflow',
  'resume_aware',
  'TRUE',
  'TRUE',
  'TRUE',
  'credential_missing:intake_required; credential_resolved:resume_publish; draft_created:verify; publish_requested:approval_gate; readback_failed:repair_resume',
  'create_credential_intake_and_hold_original_publish_request',
  'block_if_brand_core_target_preflight_or_credential_resolution_unavailable',
  'keyword_trigger_match + brand_scope_required + wordpress_target_required',
  'sql_registry',
  '2026-05-27T00:00:00Z',
  'brand_key,target_key,title,content,status,language,seo_fields,credential_role,connection_id',
  'wordpress_blog_publish_v1',
  'chat; structured_api; admin_gpt; tenant_gpt',
  'TRUE',
  'TRUE',
  'governed_default',
  'admin; tenant_owner; brand_operator',
  'governed; brand_scoped; credential_safe',
  'TRUE',
  'TRUE',
  'FALSE',
  'TRUE',
  'ar; en',
  'conditional',
  'TRUE'
) ON DUPLICATE KEY UPDATE
  `task_key` = VALUES(`task_key`),
  `trigger_terms` = VALUES(`trigger_terms`),
  `route_modules` = VALUES(`route_modules`),
  `execution_layer` = VALUES(`execution_layer`),
  `priority` = VALUES(`priority`),
  `enabled` = VALUES(`enabled`),
  `output_focus` = VALUES(`output_focus`),
  `notes` = VALUES(`notes`),
  `entry_sources` = VALUES(`entry_sources`),
  `active` = VALUES(`active`),
  `intent_key` = VALUES(`intent_key`),
  `brand_scope` = VALUES(`brand_scope`),
  `request_type` = VALUES(`request_type`),
  `route_mode` = VALUES(`route_mode`),
  `target_module` = VALUES(`target_module`),
  `workflow_key` = VALUES(`workflow_key`),
  `lifecycle_mode` = VALUES(`lifecycle_mode`),
  `memory_required` = VALUES(`memory_required`),
  `logging_required` = VALUES(`logging_required`),
  `review_required` = VALUES(`review_required`),
  `allowed_states` = VALUES(`allowed_states`),
  `degraded_action` = VALUES(`degraded_action`),
  `blocked_action` = VALUES(`blocked_action`),
  `match_rule` = VALUES(`match_rule`),
  `route_source` = VALUES(`route_source`),
  `last_validated_at` = VALUES(`last_validated_at`),
  `required_variable_profile` = VALUES(`required_variable_profile`),
  `variable_contract_group` = VALUES(`variable_contract_group`),
  `supported_ingress_channels` = VALUES(`supported_ingress_channels`),
  `requires_conversational_inference` = VALUES(`requires_conversational_inference`),
  `supports_structured_api_calls` = VALUES(`supports_structured_api_calls`),
  `allowed_actor_roles` = VALUES(`allowed_actor_roles`),
  `allowed_governance_levels` = VALUES(`allowed_governance_levels`),
  `client_allowed` = VALUES(`client_allowed`),
  `team_allowed` = VALUES(`team_allowed`),
  `admin_only` = VALUES(`admin_only`),
  `brand_scope_enforced` = VALUES(`brand_scope_enforced`),
  `supported_languages` = VALUES(`supported_languages`),
  `translation_step_required` = VALUES(`translation_step_required`),
  `locale_sensitive` = VALUES(`locale_sensitive`),
  `updated_at` = CURRENT_TIMESTAMP;
