-- 2026-07-08: DB-backed Resource API surface registry and OpenAPI automation seeds.
-- SQL-primary registry seed only. Runtime source authority is platform_data_table_registry.
-- no_provider_call
-- no_credential_payload_read
-- no_raw_secrets
-- no_external_send
-- no_external_write
-- secrets_included=false
INSERT INTO platform_data_table_registry
(table_key,display_name,description,physical_table_name,scope_mode,tenant_column,workspace_column,primary_key_columns_json,readable_columns_json,writable_columns_json,creatable_columns_json,patchable_columns_json,filterable_columns_json,required_create_columns_json,json_columns_json,default_values_json,allowed_operations_json,enabled_surfaces_json,soft_delete_column,soft_delete_value,max_limit,sort_order,status,metadata_json)
VALUES
('system_endpoints','System Endpoints','Governed read/patch surface for endpoint readiness, transport and schema contract repair.','endpoints','platform',NULL,NULL,CAST('["endpoint_key"]' AS JSON),CAST('["endpoint_key","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["endpoint_key","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","patch"]' AS JSON),CAST('["admin"]' AS JSON),NULL,NULL,100,10,'active',CAST('{"resource_family":"registry","requires_typed_approval":true,"same_cycle_readback":true,"mutation_scope":"contract_repair_only"}' AS JSON)),
('admin_platform_endpoint_tools','Admin Platform Endpoint Tools','Governed resource surface for admin tool export metadata.','admin_platform_endpoint_tools','platform',NULL,NULL,CAST('["tool_key"]' AS JSON),CAST('["tool_key"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["tool_key"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin"]' AS JSON),'is_enabled','0',100,20,'active',CAST('{"resource_family":"registry","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('platform_data_table_registry','Platform Data Table Registry','Self-hosted governance surface for DB-backed resource surfaces.','platform_data_table_registry','platform',NULL,NULL,CAST('["table_key"]' AS JSON),CAST('["table_key","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["table_key","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin"]' AS JSON),'status','archived',100,30,'active',CAST('{"resource_family":"registry","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('platform_resource_operation_registry','Platform Resource Operation Registry','Governed resource operation definitions that bind DB resources to HTTP paths and tool keys.','platform_resource_operation_registry','platform',NULL,NULL,CAST('["operation_id"]' AS JSON),CAST('["operation_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["operation_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin"]' AS JSON),'status','archived',100,40,'active',CAST('{"resource_family":"registry","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('capability_resolution_envelopes','Capability Resolution Envelopes','Read-only governed inspection surface for capability envelope blockers/readiness.','capability_resolution_envelope_ledger','platform',NULL,NULL,CAST('["envelope_id"]' AS JSON),CAST('["envelope_id"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["envelope_id"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read"]' AS JSON),CAST('["admin"]' AS JSON),NULL,NULL,100,50,'active',CAST('{"resource_family":"capability","read_only":true}' AS JSON)),
('user_app_connections','User App Connections','Tenant-scoped, safe connection status surface. Sensitive material is excluded.','user_app_connections','tenant','tenant_id',NULL,CAST('["connection_id"]' AS JSON),CAST('["connection_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["connection_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","patch","archive"]' AS JSON),CAST('["admin","tenant"]' AS JSON),'status','revoked',100,60,'active',CAST('{"resource_family":"user_connection","sensitive_material_excluded":true}' AS JSON)),
('app_action_grants','App Action Grants','Admin-governed action grant surface. Uses connection/workspace fields; no sensitive material exposed.','app_action_grants','platform',NULL,'workspace_id',CAST('["grant_id"]' AS JSON),CAST('["grant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["grant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin"]' AS JSON),'status','revoked',100,70,'active',CAST('{"resource_family":"grant","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('cms_site_access_grants','CMS Site Access Grants','Tenant-scoped CMS grant surface for WordPress/CMS repair and readback.','cms_site_access_grants','tenant','tenant_id','workspace_id',CAST('["grant_id"]' AS JSON),CAST('["grant_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["grant_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin","tenant"]' AS JSON),'status','revoked',100,80,'active',CAST('{"resource_family":"cms_grant","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('agent_skill_grants','Agent Skill Grants','Tenant-aware agent skill grant surface.','agent_skill_grants','tenant','tenant_id',NULL,CAST('["grant_id"]' AS JSON),CAST('["grant_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["grant_id","tenant_id","status"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch","archive","restore"]' AS JSON),CAST('["admin","tenant"]' AS JSON),'status','revoked',100,90,'active',CAST('{"resource_family":"agent_grant","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON)),
('permission_grants','Permission Grants','Tenant-scoped permission grant surface.','permission_grants','tenant','tenant_id',NULL,CAST('["grant_id"]' AS JSON),CAST('["grant_id","tenant_id"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('["grant_id","tenant_id"]' AS JSON),CAST('[]' AS JSON),CAST('[]' AS JSON),CAST('{}' AS JSON),CAST('["list","read","create","patch"]' AS JSON),CAST('["admin","tenant"]' AS JSON),NULL,NULL,100,100,'active',CAST('{"resource_family":"permission","requires_typed_approval":true,"same_cycle_readback":true}' AS JSON))
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),description=VALUES(description),physical_table_name=VALUES(physical_table_name),scope_mode=VALUES(scope_mode),tenant_column=VALUES(tenant_column),workspace_column=VALUES(workspace_column),primary_key_columns_json=VALUES(primary_key_columns_json),readable_columns_json=VALUES(readable_columns_json),writable_columns_json=VALUES(writable_columns_json),creatable_columns_json=VALUES(creatable_columns_json),patchable_columns_json=VALUES(patchable_columns_json),filterable_columns_json=VALUES(filterable_columns_json),allowed_operations_json=VALUES(allowed_operations_json),enabled_surfaces_json=VALUES(enabled_surfaces_json),soft_delete_column=VALUES(soft_delete_column),soft_delete_value=VALUES(soft_delete_value),max_limit=VALUES(max_limit),sort_order=VALUES(sort_order),status=VALUES(status),metadata_json=VALUES(metadata_json),updated_at=UTC_TIMESTAMP();
