-- User Dashboard Dynamic Tabs aliases.
-- Purpose: make the existing tenant growth dashboard product layer explicit as the
-- user-facing dashboard contract. The dashboard remains backed by Activation
-- Dynamic Tabs, growth dashboard profile registries, and cursor-loaded details.
-- Additive only: registers tenant-safe endpoint tools and does not expose SQL or secrets.

INSERT INTO `tenant_platform_endpoint_tools`
(`tool_key`, `display_name`, `description`, `http_method`, `http_path`, `path_param_keys`, `input_schema`, `tags`, `is_enabled`, `sort_order`)
VALUES
('user_dashboard_get','User Dashboard Get','Read the signed-in user dashboard manifest and typed cards. Backed by Dynamic Tabs and tenant growth dashboard projections.','GET','/me/dashboard',JSON_ARRAY(),JSON_OBJECT('type','object','properties',JSON_OBJECT('container_key',JSON_OBJECT('type','string'),'tab',JSON_OBJECT('type','string'),'tab_key',JSON_OBJECT('type','string'),'date_range',JSON_OBJECT('type','string'),'filters',JSON_OBJECT('type','object','additionalProperties',TRUE)),'additionalProperties',FALSE),'tenant,user_dashboard,dynamic_tabs,read_only,projection,no_secrets',1,650),
('workspace_dashboard_get','Workspace Dashboard Get','Read the signed-in user dashboard for one tenant workspace scope. The path tenant_id must match the signed JWT tenant_id.','GET','/me/workspaces/{tenant_id}/dashboard',JSON_ARRAY('tenant_id'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'container_key',JSON_OBJECT('type','string'),'tab',JSON_OBJECT('type','string'),'tab_key',JSON_OBJECT('type','string'),'date_range',JSON_OBJECT('type','string'),'filters',JSON_OBJECT('type','object','additionalProperties',TRUE)),'additionalProperties',FALSE),'tenant,user_dashboard,dynamic_tabs,workspace_scoped,read_only,projection,no_secrets',1,651),
('workspace_dashboard_tab_get','Workspace Dashboard Tab Get','Read one dashboard tab projection for the signed-in tenant workspace scope.','GET','/me/workspaces/{tenant_id}/dashboard/tabs/{tabKey}',JSON_ARRAY('tenant_id','tabKey'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id','tabKey'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'tabKey',JSON_OBJECT('type','string'),'container_key',JSON_OBJECT('type','string'),'date_range',JSON_OBJECT('type','string'),'filters',JSON_OBJECT('type','object','additionalProperties',TRUE)),'additionalProperties',FALSE),'tenant,user_dashboard,dynamic_tabs,tab,workspace_scoped,read_only,projection,no_secrets',1,652),
('workspace_dashboard_preferences_get','Workspace Dashboard Preferences Get','Read signed-in user dashboard preferences for one tenant workspace scope.','GET','/me/workspaces/{tenant_id}/dashboard/preferences',JSON_ARRAY('tenant_id'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string')),'additionalProperties',FALSE),'tenant,user_dashboard,preferences,workspace_scoped,read_only,no_secrets',1,653),
('workspace_dashboard_preferences_put','Workspace Dashboard Preferences Put','Update signed-in user dashboard preferences. Payload is normalized by the dashboard service and scoped to the JWT tenant and user.','PUT','/me/workspaces/{tenant_id}/dashboard/preferences',JSON_ARRAY('tenant_id'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'active_container_key',JSON_OBJECT('type','string'),'active_tab_key',JSON_OBJECT('type','string'),'pinned_tabs',JSON_OBJECT('type','array','items',JSON_OBJECT('type','string')),'hidden_tabs',JSON_OBJECT('type','array','items',JSON_OBJECT('type','string')),'preferred_date_range',JSON_OBJECT('type','string'),'saved_filters',JSON_OBJECT('type','object','additionalProperties',TRUE),'dashboard_density',JSON_OBJECT('type','string','enum',JSON_ARRAY('compact','comfortable','detailed'))),'additionalProperties',TRUE),'tenant,user_dashboard,preferences,workspace_scoped,state_changing,readback,no_secrets',1,654),
('workspace_dashboard_digest_get','Workspace Dashboard Digest Get','Read a compact dashboard digest for notification or summary surfaces.','GET','/me/workspaces/{tenant_id}/dashboard/digest',JSON_ARRAY('tenant_id'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'container_key',JSON_OBJECT('type','string')),'additionalProperties',FALSE),'tenant,user_dashboard,digest,dynamic_tabs,workspace_scoped,read_only,no_secrets',1,655),
('workspace_dashboard_action_preview_get','Workspace Dashboard Action Preview Get','Read a preview-only dashboard action. No provider call, external write, or live execution occurs.','GET','/me/workspaces/{tenant_id}/dashboard/actions/{actionRefKey}/preview',JSON_ARRAY('tenant_id','actionRefKey'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id','actionRefKey'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'actionRefKey',JSON_OBJECT('type','string'),'container_key',JSON_OBJECT('type','string')),'additionalProperties',FALSE),'tenant,user_dashboard,actions,preview_only,workspace_scoped,read_only,no_provider_call,no_secrets',1,656),
('workspace_dashboard_feedback_post','Workspace Dashboard Feedback Post','Record signed-in user feedback for one dashboard recommendation event. Internal ledger write only.','POST','/me/workspaces/{tenant_id}/dashboard/recommendations/{recommendationId}/feedback',JSON_ARRAY('tenant_id','recommendationId'),JSON_OBJECT('type','object','required',JSON_ARRAY('tenant_id','recommendationId','event_type'),'properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'recommendationId',JSON_OBJECT('type','string'),'event_type',JSON_OBJECT('type','string','enum',JSON_ARRAY('shown','opened','accepted','dismissed','executed','failed','result_observed')),'reason_code',JSON_OBJECT('type','string'),'workspace_id',JSON_OBJECT('type','string'),'recommendation_key',JSON_OBJECT('type','string'),'tab_key',JSON_OBJECT('type','string'),'card_id',JSON_OBJECT('type','string'),'result_metric_key',JSON_OBJECT('type','string'),'result_value',JSON_OBJECT('type','object','additionalProperties',TRUE),'context',JSON_OBJECT('type','object','additionalProperties',TRUE)),'additionalProperties',FALSE),'tenant,user_dashboard,recommendation_feedback,workspace_scoped,state_changing,internal_registry,readback,no_secrets',1,657)
ON DUPLICATE KEY UPDATE
  `display_name` = VALUES(`display_name`),
  `description` = VALUES(`description`),
  `http_method` = VALUES(`http_method`),
  `http_path` = VALUES(`http_path`),
  `path_param_keys` = VALUES(`path_param_keys`),
  `input_schema` = VALUES(`input_schema`),
  `tags` = VALUES(`tags`),
  `is_enabled` = VALUES(`is_enabled`),
  `sort_order` = VALUES(`sort_order`);
