-- Act-as-User durable runtime foundation.
-- Declaration only: this migration is fail-closed until separately promoted with evidence.
CREATE TABLE IF NOT EXISTS `act_as_user_sessions` (
  `session_id` varchar(191) NOT NULL,
  `tenant_id` varchar(191) NOT NULL,
  `actor_principal_id` varchar(191) NOT NULL,
  `target_user_id` varchar(191) NOT NULL,
  `actor_role` varchar(64) NOT NULL,
  `target_role` varchar(64) NOT NULL,
  `delegation_id` varchar(191) NOT NULL,
  `requested_tool` varchar(191) NOT NULL,
  `requested_operation` varchar(64) NOT NULL,
  `effective_capabilities_json` json NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `issued_at` datetime(3) NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `revoked_at` datetime(3) NULL,
  `revoked_reason` varchar(255) NULL,
  `version` bigint unsigned NOT NULL DEFAULT 1,
  `environment` varchar(32) NOT NULL DEFAULT 'staging',
  `secrets_included` tinyint(1) NOT NULL DEFAULT 0,
  `last_readback_id` varchar(191) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`session_id`),
  UNIQUE KEY `uq_act_as_user_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_act_as_user_session_status` (`tenant_id`, `status`, `expires_at`),
  KEY `idx_act_as_user_target` (`tenant_id`, `target_user_id`, `status`),
  CONSTRAINT `ck_act_as_user_session_no_secrets` CHECK (`secrets_included` = 0),
  CONSTRAINT `ck_act_as_user_session_distinct_subjects` CHECK (`actor_principal_id` <> `target_user_id`),
  CONSTRAINT `ck_act_as_user_session_valid_window` CHECK (`expires_at` > `issued_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `act_as_user_audit_events` (
  `event_id` varchar(191) NOT NULL,
  `session_id` varchar(191) NULL,
  `event_type` varchar(96) NOT NULL,
  `tenant_id` varchar(191) NULL,
  `actor_principal_id` varchar(191) NULL,
  `target_user_id` varchar(191) NULL,
  `requested_tool` varchar(191) NULL,
  `requested_operation` varchar(64) NULL,
  `correlation_id` varchar(191) NULL,
  `request_hash` char(64) NULL,
  `readback_id` varchar(191) NULL,
  `event_json` json NOT NULL,
  `secrets_included` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`event_id`),
  KEY `idx_act_as_user_audit_session` (`session_id`, `created_at`),
  KEY `idx_act_as_user_audit_tenant` (`tenant_id`, `created_at`),
  CONSTRAINT `ck_act_as_user_audit_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `act_as_user_readbacks` (
  `readback_id` varchar(191) NOT NULL,
  `session_id` varchar(191) NOT NULL,
  `tenant_id` varchar(191) NOT NULL,
  `actor_principal_id` varchar(191) NOT NULL,
  `target_user_id` varchar(191) NOT NULL,
  `status` varchar(32) NOT NULL,
  `payload_hash` char(64) NULL,
  `evidence_json` json NOT NULL,
  `secrets_included` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`readback_id`),
  KEY `idx_act_as_user_readback_session` (`session_id`, `created_at`),
  CONSTRAINT `ck_act_as_user_readback_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
