-- Safety contract: no_provider_call=true; no_credential_payload_read=true; no_raw_secrets=true;
-- no_external_send=true; no_external_write=true; secrets_included=false.
-- Registers an internal semantic capability and a rollback-only dynamic apply policy.
-- The certification script defaults to dry-run. Apply requires a typed confirmation,
-- a same-cycle approved capability envelope, transaction rollback, audit evidence,
-- and same-cycle readback. Provider calls, credential reads, and external writes remain forbidden.

INSERT INTO platform_semantic_capabilities (
  capability_key,
  display_name,
  description,
  resource_type,
  operation_key,
  risk_class,
  default_execution_mode,
  input_schema_json,
  output_schema_json,
  default_policy_key,
  requires_connection,
  requires_workspace_authority,
  requires_approval,
  requires_audit_evidence,
  requires_readback,
  schema_version,
  status,
  notes
) VALUES (
  'supervisor_behavioral_certification',
  'Supervisor behavioral certification',
  'Run bounded supervisor behavioral certification with transaction rollback and zero provider calls.',
  'supervisor_runtime_certification',
  'certify',
  'C',
  'apply',
  NULL,
  NULL,
  'supervisor_behavioral_certification_apply_v1',
  0,
  0,
  1,
  1,
  1,
  1,
  'active',
  'Internal Admin capability. Dry-run and typed confirmation are mandatory before rollback-only apply. No provider call, credential payload read, external write, deploy, publish, spend, or secrets.'
)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  description = VALUES(description),
  resource_type = VALUES(resource_type),
  operation_key = VALUES(operation_key),
  risk_class = VALUES(risk_class),
  default_execution_mode = VALUES(default_execution_mode),
  input_schema_json = VALUES(input_schema_json),
  output_schema_json = VALUES(output_schema_json),
  default_policy_key = VALUES(default_policy_key),
  requires_connection = VALUES(requires_connection),
  requires_workspace_authority = VALUES(requires_workspace_authority),
  requires_approval = VALUES(requires_approval),
  requires_audit_evidence = VALUES(requires_audit_evidence),
  requires_readback = VALUES(requires_readback),
  schema_version = VALUES(schema_version),
  status = VALUES(status),
  notes = VALUES(notes),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO capability_apply_authorization_policy_registry (
  policy_key,
  app_key,
  capability_key,
  operation_intent,
  runtime_surface,
  status,
  allow_external_write,
  allow_credential_binding,
  allow_no_credential_binding,
  requires_ready_for_dispatch,
  requires_dispatch_allowed,
  requires_zero_blocking_gaps,
  requires_audit_evidence,
  requires_readback,
  requires_typed_confirmation,
  requires_same_cycle_dry_run,
  allowed_source_tiers_json,
  policy_json,
  notes
) VALUES (
  'supervisor_behavioral_certification_apply_v1',
  'platform_orchestration',
  'supervisor_behavioral_certification',
  'supervisor_behavioral_certification',
  'admin_control',
  'active',
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  JSON_ARRAY('platform_managed_fallback'),
  JSON_OBJECT(
    'transaction_rollback_required', true,
    'typed_confirmation_required', true,
    'confirmation_token', 'APPLY_SUPERVISOR_BEHAVIORAL_CERTIFICATION',
    'same_cycle_dry_run_required', true,
    'same_cycle_readback_required', true,
    'execution_evidence_write_allowed', true,
    'fixture_persistence_forbidden', true,
    'provider_call_forbidden', true,
    'external_write_forbidden', true,
    'credential_binding_forbidden', true,
    'credential_payload_read_forbidden', true,
    'deploy_publish_spend_forbidden', true,
    'secrets_included', false
  ),
  'Internal rollback-only certification policy. Apply authorization requires a ready approved envelope, zero blocking gaps, typed confirmation, same-cycle dry-run, audit evidence, and readback. Provider calls and external writes remain forbidden.'
)
ON DUPLICATE KEY UPDATE
  app_key = VALUES(app_key),
  capability_key = VALUES(capability_key),
  operation_intent = VALUES(operation_intent),
  runtime_surface = VALUES(runtime_surface),
  status = VALUES(status),
  allow_external_write = VALUES(allow_external_write),
  allow_credential_binding = VALUES(allow_credential_binding),
  allow_no_credential_binding = VALUES(allow_no_credential_binding),
  requires_ready_for_dispatch = VALUES(requires_ready_for_dispatch),
  requires_dispatch_allowed = VALUES(requires_dispatch_allowed),
  requires_zero_blocking_gaps = VALUES(requires_zero_blocking_gaps),
  requires_audit_evidence = VALUES(requires_audit_evidence),
  requires_readback = VALUES(requires_readback),
  requires_typed_confirmation = VALUES(requires_typed_confirmation),
  requires_same_cycle_dry_run = VALUES(requires_same_cycle_dry_run),
  allowed_source_tiers_json = VALUES(allowed_source_tiers_json),
  policy_json = VALUES(policy_json),
  notes = VALUES(notes),
  updated_at = CURRENT_TIMESTAMP;

UPDATE admin_platform_endpoint_tools
SET tags = 'admin,supervisor,behavioral_certification,transaction_rollback,no_provider_calls,no_external_write,no_secrets,requires_confirmation,mutation_policy_required,capability_envelope,approval_required,audit_evidence,readback,same_cycle_dry_run,same_cycle_readback',
    updated_at = CURRENT_TIMESTAMP
WHERE tool_key = 'supervisor_behavioral_certification';
