-- Spec 011 Phase G integrated analytics and observability foundation.
-- Additive only. No migration apply, provider dispatch, notification send,
-- deployment, production activation, or credential read is authorized here.

CREATE TABLE IF NOT EXISTS `growth_control_kpi_definitions` (
  `kpi_definition_id` VARCHAR(64) NOT NULL,
  `normalized_kpi_key` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `value_type` ENUM('integer','number','ratio','percentage','currency','duration') NOT NULL,
  `unit_key` VARCHAR(128) NOT NULL,
  `aggregation` ENUM('sum','average','weighted_average','minimum','maximum','latest') NOT NULL,
  `direction` ENUM('higher_is_better','lower_is_better','target','neutral') NOT NULL DEFAULT 'neutral',
  `definition_version` BIGINT UNSIGNED NOT NULL,
  `freshness_seconds` BIGINT UNSIGNED NOT NULL DEFAULT 86400,
  `status` ENUM('draft','ready','active','deprecated','archived','blocked') NOT NULL DEFAULT 'draft',
  `revision` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `metadata_json` JSON NOT NULL,
  `checksum_sha256` CHAR(64) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`kpi_definition_id`),
  UNIQUE KEY `uq_growth_kpi_definition_version` (`normalized_kpi_key`,`definition_version`),
  KEY `idx_growth_kpi_definition_status` (`status`,`normalized_kpi_key`,`definition_version`),
  CONSTRAINT `chk_growth_kpi_definition_version` CHECK (`definition_version` > 0),
  CONSTRAINT `chk_growth_kpi_definition_revision` CHECK (`revision` > 0),
  CONSTRAINT `chk_growth_kpi_definition_freshness` CHECK (`freshness_seconds` > 0),
  CONSTRAINT `chk_growth_kpi_definition_hash` CHECK (`checksum_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_kpi_definition_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `growth_control_activity_kpi_bindings` (
  `activity_kpi_binding_id` VARCHAR(64) NOT NULL,
  `tenant_id` VARCHAR(64) NULL,
  `workspace_id` VARCHAR(64) NULL,
  `brand_key` VARCHAR(128) NULL,
  `activity_binding_id` VARCHAR(64) NOT NULL,
  `activity_type_key` VARCHAR(128) NOT NULL,
  `activity_pack_key` VARCHAR(128) NOT NULL,
  `native_kpi_key` VARCHAR(128) NOT NULL,
  `normalized_kpi_key` VARCHAR(128) NOT NULL,
  `definition_version` BIGINT UNSIGNED NOT NULL,
  `native_unit_key` VARCHAR(128) NOT NULL,
  `normalized_unit_key` VARCHAR(128) NOT NULL,
  `conversion_kind` ENUM('identity','scale') NOT NULL DEFAULT 'identity',
  `scale_multiplier` DECIMAL(30,12) NOT NULL DEFAULT 1,
  `mapping_confidence` DECIMAL(7,6) NOT NULL DEFAULT 1,
  `status` ENUM('draft','ready','active','deprecated','archived','blocked') NOT NULL DEFAULT 'draft',
  `revision` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `binding_sha256` CHAR(64) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`activity_kpi_binding_id`),
  UNIQUE KEY `uq_growth_activity_kpi_version` (`activity_binding_id`,`native_kpi_key`,`definition_version`),
  KEY `idx_growth_activity_kpi_scope` (`tenant_id`,`workspace_id`,`brand_key`,`activity_binding_id`),
  KEY `idx_growth_activity_kpi_normalized` (`normalized_kpi_key`,`definition_version`,`status`),
  CONSTRAINT `chk_growth_activity_kpi_version` CHECK (`definition_version` > 0),
  CONSTRAINT `chk_growth_activity_kpi_revision` CHECK (`revision` > 0),
  CONSTRAINT `chk_growth_activity_kpi_scale` CHECK (`scale_multiplier` > 0),
  CONSTRAINT `chk_growth_activity_kpi_confidence` CHECK (`mapping_confidence` >= 0 AND `mapping_confidence` <= 1),
  CONSTRAINT `chk_growth_activity_kpi_hash` CHECK (`binding_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_activity_kpi_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `growth_control_normalized_metric_observations` (
  `observation_id` VARCHAR(64) NOT NULL,
  `tenant_id` VARCHAR(64) NOT NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `brand_key` VARCHAR(128) NOT NULL,
  `activity_binding_id` VARCHAR(64) NOT NULL,
  `activity_type_key` VARCHAR(128) NOT NULL,
  `normalized_kpi_key` VARCHAR(128) NOT NULL,
  `native_kpi_key` VARCHAR(128) NOT NULL,
  `definition_version` BIGINT UNSIGNED NOT NULL,
  `native_unit_key` VARCHAR(128) NOT NULL,
  `normalized_unit_key` VARCHAR(128) NOT NULL,
  `native_value` DECIMAL(38,12) NOT NULL,
  `normalized_value` DECIMAL(38,12) NOT NULL,
  `weight_value` DECIMAL(30,12) NOT NULL DEFAULT 1,
  `period_start` DATETIME(6) NOT NULL,
  `period_end` DATETIME(6) NOT NULL,
  `observed_at` DATETIME(6) NOT NULL,
  `confidence` DECIMAL(7,6) NOT NULL,
  `freshness_age_seconds` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `freshness_status` ENUM('fresh','stale') NOT NULL,
  `lineage_json` JSON NOT NULL,
  `observation_sha256` CHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(191) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`observation_id`),
  UNIQUE KEY `uq_growth_metric_observation_idempotency` (`idempotency_key`),
  UNIQUE KEY `uq_growth_metric_observation_hash` (`observation_sha256`),
  KEY `idx_growth_metric_scope_time` (`tenant_id`,`workspace_id`,`brand_key`,`observed_at`),
  KEY `idx_growth_metric_kpi_period` (`normalized_kpi_key`,`definition_version`,`period_start`,`period_end`),
  KEY `idx_growth_metric_binding_native` (`activity_binding_id`,`native_kpi_key`,`observed_at`),
  CONSTRAINT `chk_growth_metric_period` CHECK (`period_end` >= `period_start`),
  CONSTRAINT `chk_growth_metric_weight` CHECK (`weight_value` > 0),
  CONSTRAINT `chk_growth_metric_confidence` CHECK (`confidence` >= 0 AND `confidence` <= 1),
  CONSTRAINT `chk_growth_metric_hash` CHECK (`observation_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_metric_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `growth_control_observability_samples` (
  `sample_id` VARCHAR(64) NOT NULL,
  `metric_key` VARCHAR(128) NOT NULL,
  `tenant_id` VARCHAR(64) NULL,
  `workspace_id` VARCHAR(64) NULL,
  `brand_key` VARCHAR(128) NULL,
  `environment` VARCHAR(32) NOT NULL,
  `value_number` DECIMAL(38,12) NOT NULL,
  `weight_value` DECIMAL(30,12) NOT NULL DEFAULT 1,
  `observed_at` DATETIME(6) NOT NULL,
  `source_evidence_sha256` CHAR(64) NOT NULL,
  `sample_sha256` CHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(191) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`sample_id`),
  UNIQUE KEY `uq_growth_observability_sample_idempotency` (`idempotency_key`),
  UNIQUE KEY `uq_growth_observability_sample_hash` (`sample_sha256`),
  KEY `idx_growth_observability_metric_time` (`metric_key`,`observed_at`),
  KEY `idx_growth_observability_scope_time` (`tenant_id`,`workspace_id`,`brand_key`,`observed_at`),
  CONSTRAINT `chk_growth_observability_weight` CHECK (`weight_value` > 0),
  CONSTRAINT `chk_growth_observability_evidence_hash` CHECK (`source_evidence_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_observability_sample_hash` CHECK (`sample_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_observability_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `growth_control_decision_evidence` (
  `evidence_id` VARCHAR(64) NOT NULL,
  `request_id` VARCHAR(191) NOT NULL,
  `trace_id` VARCHAR(191) NOT NULL,
  `tenant_id` VARCHAR(64) NULL,
  `workspace_id` VARCHAR(64) NULL,
  `brand_key` VARCHAR(128) NULL,
  `activity_binding_id` VARCHAR(64) NULL,
  `plan_id` VARCHAR(64) NULL,
  `run_id` VARCHAR(64) NULL,
  `capability_key` VARCHAR(128) NULL,
  `workflow_version` BIGINT UNSIGNED NULL,
  `config_snapshot_id` VARCHAR(64) NULL,
  `policy_snapshot_id` VARCHAR(64) NULL,
  `selected_adapter_key` VARCHAR(128) NULL,
  `gate_results_json` JSON NOT NULL,
  `reason_codes_json` JSON NOT NULL,
  `duration_ms` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `result_classification` VARCHAR(64) NOT NULL,
  `readback_status` VARCHAR(64) NOT NULL,
  `evidence_sha256` CHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(191) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`evidence_id`),
  UNIQUE KEY `uq_growth_decision_evidence_idempotency` (`idempotency_key`),
  UNIQUE KEY `uq_growth_decision_evidence_hash` (`evidence_sha256`),
  KEY `idx_growth_decision_trace` (`trace_id`,`request_id`),
  KEY `idx_growth_decision_scope` (`tenant_id`,`workspace_id`,`brand_key`,`created_at`),
  KEY `idx_growth_decision_run` (`plan_id`,`run_id`,`created_at`),
  CONSTRAINT `chk_growth_decision_hash` CHECK (`evidence_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_decision_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `growth_control_reconciliation_findings` (
  `finding_id` VARCHAR(64) NOT NULL,
  `finding_type` VARCHAR(128) NOT NULL,
  `tenant_id` VARCHAR(64) NULL,
  `workspace_id` VARCHAR(64) NULL,
  `brand_key` VARCHAR(128) NULL,
  `severity` ENUM('info','low','medium','high','critical') NOT NULL,
  `status` ENUM('open','acknowledged','resolved','blocked') NOT NULL DEFAULT 'open',
  `reason_code` VARCHAR(120) NOT NULL,
  `authority_ref` VARCHAR(191) NULL,
  `evidence_ref` VARCHAR(191) NULL,
  `detected_at` DATETIME(6) NOT NULL,
  `resolved_at` DATETIME(6) NULL,
  `finding_sha256` CHAR(64) NOT NULL,
  `secrets_included` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`finding_id`),
  UNIQUE KEY `uq_growth_reconciliation_finding_hash` (`finding_sha256`),
  KEY `idx_growth_reconciliation_scope` (`tenant_id`,`workspace_id`,`brand_key`,`status`,`detected_at`),
  KEY `idx_growth_reconciliation_severity` (`severity`,`status`,`detected_at`),
  CONSTRAINT `chk_growth_reconciliation_resolution` CHECK ((`status`='resolved' AND `resolved_at` IS NOT NULL) OR (`status`<>'resolved')),
  CONSTRAINT `chk_growth_reconciliation_hash` CHECK (`finding_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_growth_reconciliation_no_secrets` CHECK (`secrets_included` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `governed_migration_authorization_registry` (
  `migration_file`,`authorization_status`,`authorization_source`,`policy_key`,`risk_tier`,
  `requires_preflight`,`requires_confirmation`,`allow_record_only`,`allow_apply`,`notes`,`metadata_json`
) VALUES (
  '20260731_growth_control_analytics_observability_foundation.sql',
  'authorized','spec_011_phase_g_integrated_analytics_observability',
  'governed_migration_runner_authorization_v1','high',1,1,1,1,
  'Additive KPI, metric observation, bounded decision evidence, SLO sample, and reconciliation authorities. No runtime activation.',
  JSON_OBJECT(
    'spec_key','011-dynamic-multi-tenant-growth-control-plane',
    'phase','G','task_keys',JSON_ARRAY('T604','T605'),'additive_only',TRUE,
    'migration_applied',FALSE,'provider_calls',FALSE,'provider_writes',FALSE,
    'external_sends',FALSE,'production_activation',FALSE,'credentials_read',FALSE,
    'secrets_included',FALSE
  )
)
ON DUPLICATE KEY UPDATE
  `authorization_status`=VALUES(`authorization_status`),
  `authorization_source`=VALUES(`authorization_source`),
  `policy_key`=VALUES(`policy_key`),
  `risk_tier`=VALUES(`risk_tier`),
  `requires_preflight`=VALUES(`requires_preflight`),
  `requires_confirmation`=VALUES(`requires_confirmation`),
  `allow_record_only`=VALUES(`allow_record_only`),
  `allow_apply`=VALUES(`allow_apply`),
  `notes`=VALUES(`notes`),
  `metadata_json`=VALUES(`metadata_json`),
  `updated_at`=CURRENT_TIMESTAMP;
