-- Sprint 68: Growth Intelligence product registry foundation
-- Persists internally governed reports, insights, and dry-run actions.
-- Reuses workflow_runs and approval_holds; does not authorize provider writes or external sends.
-- Additive, idempotent, no destructive changes, no secrets.

CREATE TABLE IF NOT EXISTS growth_intelligence_reports (
  report_id VARCHAR(36) NOT NULL PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  brand_key VARCHAR(128) NOT NULL,
  workflow_run_id VARCHAR(36) NOT NULL,
  workflow_key VARCHAR(191) NOT NULL DEFAULT 'tenant_brand_growth_intelligence_pilot_v1',
  report_type VARCHAR(128) NOT NULL DEFAULT 'growth_intelligence_pilot',
  schema_version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
  status ENUM('generated','approval_pending','approved','rejected','archived') NOT NULL DEFAULT 'approval_pending',
  executive_summary_json JSON NOT NULL,
  report_json JSON NOT NULL,
  markdown_report LONGTEXT NOT NULL,
  readback_json JSON NOT NULL,
  audit_evidence_json JSON NOT NULL,
  quality_status ENUM('pending','pass','warn','fail') NOT NULL DEFAULT 'pending',
  quality_metrics_json JSON NOT NULL,
  freshness_expires_at DATETIME NULL,
  provider_writes INT NOT NULL DEFAULT 0,
  external_sends INT NOT NULL DEFAULT 0,
  secrets_included TINYINT(1) NOT NULL DEFAULT 0,
  generated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_growth_reports_tenant_brand (tenant_id, brand_key, created_at),
  KEY idx_growth_reports_status (tenant_id, status, created_at),
  KEY idx_growth_reports_run (workflow_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS growth_intelligence_insights (
  insight_record_id VARCHAR(36) NOT NULL PRIMARY KEY,
  insight_id VARCHAR(64) NOT NULL,
  report_id VARCHAR(36) NOT NULL,
  tenant_id VARCHAR(36) NOT NULL,
  brand_key VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  title VARCHAR(512) NOT NULL,
  rationale TEXT NULL,
  evidence_status ENUM('evidence_backed','assumption') NOT NULL DEFAULT 'assumption',
  evidence_refs_json JSON NOT NULL,
  insight_fingerprint CHAR(64) NOT NULL,
  supersedes_insight_record_id VARCHAR(36) NULL,
  score DECIMAL(12,4) NOT NULL DEFAULT 0,
  risk ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  status ENUM('proposed','accepted','rejected','stale','superseded') NOT NULL DEFAULT 'proposed',
  decision_by VARCHAR(191) NULL,
  decision_note VARCHAR(512) NULL,
  decided_at DATETIME NULL,
  freshness_expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_growth_insight_report_identity (report_id, insight_id),
  KEY idx_growth_insights_tenant_brand (tenant_id, brand_key, status, created_at),
  KEY idx_growth_insights_report (report_id, score),
  KEY idx_growth_insights_fingerprint (tenant_id, brand_key, insight_fingerprint, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS growth_intelligence_actions (
  action_record_id VARCHAR(36) NOT NULL PRIMARY KEY,
  action_id VARCHAR(64) NOT NULL,
  report_id VARCHAR(36) NOT NULL,
  opportunity_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(36) NOT NULL,
  brand_key VARCHAR(128) NOT NULL,
  workflow_run_id VARCHAR(36) NOT NULL,
  approval_hold_id VARCHAR(36) NULL,
  title VARCHAR(512) NOT NULL,
  priority_score DECIMAL(12,4) NOT NULL DEFAULT 0,
  risk ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  execution_class ENUM('advisory','draft','controlled_apply','provider_write','external_send') NOT NULL DEFAULT 'draft',
  execution_mode ENUM('dry_run') NOT NULL DEFAULT 'dry_run',
  approval_state ENUM('not_required','held','approved','rejected','expired') NOT NULL DEFAULT 'held',
  readiness_status ENUM('blocked','review_ready') NOT NULL DEFAULT 'blocked',
  readiness_assessment_id VARCHAR(36) NULL,
  readback_requirements_json JSON NOT NULL,
  provider_write TINYINT(1) NOT NULL DEFAULT 0,
  external_send TINYINT(1) NOT NULL DEFAULT 0,
  secrets_included TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_growth_action_report_identity (report_id, action_id),
  KEY idx_growth_actions_tenant_approval (tenant_id, approval_state, priority_score),
  KEY idx_growth_actions_report (report_id, priority_score),
  KEY idx_growth_actions_hold (approval_hold_id),
  KEY idx_growth_actions_readiness (tenant_id, readiness_status, approval_state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS growth_intelligence_readiness_assessments (
  assessment_id VARCHAR(36) NOT NULL PRIMARY KEY,
  report_id VARCHAR(36) NOT NULL,
  tenant_id VARCHAR(36) NOT NULL,
  brand_key VARCHAR(128) NOT NULL,
  assessment_status ENUM('blocked','review_ready') NOT NULL DEFAULT 'blocked',
  blocking_gap_count INT UNSIGNED NOT NULL DEFAULT 0,
  required_controls_json JSON NOT NULL,
  satisfied_controls_json JSON NOT NULL,
  blocking_gaps_json JSON NOT NULL,
  quality_metrics_json JSON NOT NULL,
  assessment_sha256 CHAR(64) NOT NULL,
  execution_allowed TINYINT(1) NOT NULL DEFAULT 0,
  provider_writes_allowed TINYINT(1) NOT NULL DEFAULT 0,
  external_sends_allowed TINYINT(1) NOT NULL DEFAULT 0,
  secrets_included TINYINT(1) NOT NULL DEFAULT 0,
  assessed_by VARCHAR(191) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_growth_readiness_report (report_id, created_at),
  KEY idx_growth_readiness_tenant (tenant_id, assessment_status, created_at),
  CONSTRAINT chk_growth_readiness_no_execution CHECK (execution_allowed = 0),
  CONSTRAINT chk_growth_readiness_no_provider_writes CHECK (provider_writes_allowed = 0),
  CONSTRAINT chk_growth_readiness_no_external_sends CHECK (external_sends_allowed = 0),
  CONSTRAINT chk_growth_readiness_no_secrets CHECK (secrets_included = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO database_table_lifecycle_registry
  (table_name, table_family, owner_engine_key, owner_workflow_key, authority_model, usage_status,
   write_strategy, retention_class, retention_days, archive_strategy, cleanup_strategy,
   growth_policy, linked_by_code, linked_by_policy, linked_by_foreign_key, risk_level, status, notes)
VALUES
  ('growth_intelligence_reports', 'growth_intelligence_product', 'workflow_runtime_engine', 'tenant_brand_growth_intelligence_pilot_v1',
   'canonical', 'runtime_canonical', 'platform_primary', 'business_record', NULL, 'archive_superseded_reports',
   'retain_latest_and_archive_superseded', 'monitor_report_volume_and_staleness', 1, 1, 0, 'medium', 'active',
   'Tenant/brand Growth Intelligence report authority. No provider execution authority.'),
  ('growth_intelligence_insights', 'growth_intelligence_product', 'workflow_runtime_engine', 'tenant_brand_growth_intelligence_pilot_v1',
   'canonical', 'runtime_canonical', 'platform_primary', 'canonical_with_compaction', NULL, 'compact_superseded_insights',
   'mark_stale_or_superseded_before_archive', 'monitor_stale_and_duplicate_insights', 1, 1, 0, 'medium', 'active',
   'Evidence-backed or assumption-marked Growth Intelligence insight authority.'),
  ('growth_intelligence_actions', 'growth_intelligence_product', 'workflow_runtime_engine', 'tenant_brand_growth_intelligence_pilot_v1',
   'canonical', 'runtime_canonical', 'platform_primary', 'approval_audit', 365, 'archive_terminal_actions_after_retention',
   'retain_approval_and_readback_links', 'monitor_pending_approval_latency', 1, 1, 0, 'high', 'active',
   'Dry-run Growth Intelligence action registry linked to approval_holds.'),
  ('growth_intelligence_readiness_assessments', 'growth_intelligence_product', 'workflow_runtime_engine', 'tenant_brand_growth_intelligence_pilot_v1',
   'canonical', 'runtime_canonical', 'platform_primary', 'approval_audit', 365, 'archive_superseded_assessments_after_retention',
   'retain_latest_and_decision_linked_assessments', 'monitor_blocking_gaps_and_review_readiness', 1, 1, 0, 'high', 'active',
   'Immutable no-execution readiness evidence for Growth Intelligence reports.')
ON DUPLICATE KEY UPDATE
  table_family=VALUES(table_family),
  owner_engine_key=VALUES(owner_engine_key),
  owner_workflow_key=VALUES(owner_workflow_key),
  authority_model=VALUES(authority_model),
  usage_status=VALUES(usage_status),
  write_strategy=VALUES(write_strategy),
  retention_class=VALUES(retention_class),
  retention_days=VALUES(retention_days),
  archive_strategy=VALUES(archive_strategy),
  cleanup_strategy=VALUES(cleanup_strategy),
  growth_policy=VALUES(growth_policy),
  linked_by_code=VALUES(linked_by_code),
  linked_by_policy=VALUES(linked_by_policy),
  linked_by_foreign_key=VALUES(linked_by_foreign_key),
  risk_level=VALUES(risk_level),
  status=VALUES(status),
  notes=VALUES(notes);
