-- Sprint 68: Platform Development Constitution execution policies.
--
-- Establishes blocking runtime policy seeds that make the final development
-- pattern policy-first, orchestration-driven, recommendation-led,
-- gate-enforced, readback-certified, no-secret, and generic-before-specific.
--
-- Idempotent. No destructive changes. No secrets.

INSERT INTO `execution_policies` (
  `policy_group`, `policy_key`, `policy_value`, `active`,
  `execution_scope`, `affects_layer`, `blocking`, `notes`
)
SELECT n.policy_group, n.policy_key, n.policy_value, 'TRUE',
       n.execution_scope, n.affects_layer, 'TRUE', n.notes
FROM (
  SELECT 'Platform Development Constitution' AS policy_group,
         'platform_development_constitution_policy_v1' AS policy_key,
         JSON_OBJECT(
           'rule','platform_development_constitution',
           'requires',JSON_ARRAY('domain_key','owner_scope','policy_key','orchestration_stage_or_exemption','readback_surface','tests','no_secret_contract','deprecation_path_for_legacy_surface'),
           'blocked_classification','architecture_degradation',
           'secrets_included',false
         ) AS policy_value,
         'platform_development|routes|tools|tables|workflows|plugins|runtime_configs|provider_adapters|tenant_capabilities' AS execution_scope,
         'releaseReadiness|repo_patch_apply|governed_migration_runner|admin_tools|tenant_tools|platform_engine_registry' AS affects_layer,
         'Every new platform surface must be policy-bound, orchestration-aware, readback-testable, no-secret, and release-gated.' AS notes
  UNION ALL SELECT 'Orchestration Intelligence Governance','orchestration_first_development_policy_v1',JSON_OBJECT('rule','orchestration_first_development','allowed_entry_classes',JSON_ARRAY('orchestrated_plugin_stage','intelligence_engine_policy','legacy_surface_with_migration_plan','explicit_exemption'),'blocked_classification','blocked_unorchestrated_surface','secrets_included',false),'platform_development|capability_addition|provider_adapter|tenant_tool|admin_tool|workflow','platform_orchestration_plugins|platform_orchestration_stages|intelligence_engines|platform_engine_policy_registry|execution_policies','Prevents isolated feature islands by requiring every capability to attach to orchestration graph, intelligence policy, legacy bridge, or explicit exemption.'
  UNION ALL SELECT 'Orchestration Intelligence Governance','orchestration_state_snapshot_required_policy_v1',JSON_OBJECT('rule','state_snapshot_required_before_recommendation','requires',JSON_ARRAY('input_sources_json','state_json','maturity_json','blockers_json','safety_json'),'secrets_included_must_be_false',true,'blocked_classification','missing_orchestration_state_snapshot','secrets_included',false),'orchestration_intelligence|recommendation_generation|execution_planning|tenant_guidance','platform_orchestration_state_snapshots|decision_runs|platform_engine_execution_runs','Recommendations and execution plans must derive from a stored state snapshot rather than one-off tool output.'
  UNION ALL SELECT 'Orchestration Intelligence Governance','recommendation_before_execution_policy_v1',JSON_OBJECT('rule','recommendation_before_execution','requires',JSON_ARRAY('recommendation_id_or_decision_run','safety_contract_satisfied','validation_not_failed'),'blocks_direct_continue_to_execution',true,'secrets_included',false),'tool_execution|repo_mutation|provider_adapter|deploy|publish|credential_change|ssh_command','platform_orchestration_recommendations|decision_runs|capability_resolution_envelope_ledger|approval_holds','Any execution or mutation must be preceded by a recorded recommendation/decision and safety contract.'
  UNION ALL SELECT 'Orchestration Intelligence Governance','intentional_safety_block_classification_policy_v1',JSON_OBJECT('rule','classify_safety_blocks_explicitly','required_blocker_classes',JSON_ARRAY('missing_dependency','missing_credential','platform_schema_blocker','validation_pending','approval_required','policy_disabled_by_design','unsafe_to_execute','runtime_transport_unready','legacy_surface_gap'),'policy_disabled_by_design_is_not_bug',true,'secrets_included',false),'blocker_classification|execution_enablement|provider_governance|runtime_readiness','execution_enablement_registry|platform_pending_tasks|platform_orchestration_recommendations|tenant_gpt_guidance','Safety blocks must be classified as intentional or actionable; disabled-by-design must not be treated as failure.'
  UNION ALL SELECT 'Execution Safety Governance','no_hidden_execution_policy_v1',JSON_OBJECT('rule','no_hidden_execution','requires_declared_side_effects',true,'forbidden_without_gate',JSON_ARRAY('provider_api_mutation','spend_change','credential_payload_read','external_write','freeform_shell'),'required_gates',JSON_ARRAY('capability_envelope','approval_when_risky','audit','readback'),'secrets_included',false),'tool_execution|provider_adapter|external_write|ssh_command|publish|deploy','appAdapters|connectorExecutor|hostingerSshDeployExecutor|wordpressPublishOrchestrator|gptToolsRoutes','No tool, script, route, or adapter may perform hidden side effects outside explicit gates and readback.'
  UNION ALL SELECT 'Plugin Governance','plugin_manifest_completeness_policy_v1',JSON_OBJECT('rule','plugin_manifest_completeness','requires',JSON_ARRAY('plugin_key','domain_key','owner_scope','plugin_type','status','version','safety_contract_json','supported_stages','readback_tool'),'blocked_classification','plugin_manifest_incomplete','secrets_included',false),'plugin_registry|plugin_contribution|domain_plugin|platform_plugin','platform_plugin_contributions|platform_orchestration_plugins|plugins|platform_plugin_smoke_certifications','Every plugin must have a complete manifest and safety/readback contract before being treated as governed.'
  UNION ALL SELECT 'Orchestration Intelligence Governance','orchestration_stage_graph_completeness_policy_v1',JSON_OBJECT('rule','orchestration_stage_graph_completeness','stage_requires',JSON_ARRAY('required_inputs_json','produced_outputs_json','required_tables_json','required_tools_json','required_policies_json','acceptance_criteria_json','safety_contract_json'),'edge_requires',JSON_ARRAY('from_stage','to_stage','edge_type','condition_json'),'secrets_included',false),'orchestration_graph|plugin_stage|workflow_stage|provider_stage','platform_orchestration_stages|platform_orchestration_edges|workflows|task_routes','Every orchestration stage and edge must declare inputs, outputs, dependencies, acceptance criteria, and safety contract.'
  UNION ALL SELECT 'Task Governance','platform_task_quality_gate_policy_v1',JSON_OBJECT('rule','platform_task_quality_gate','requires',JSON_ARRAY('task_type','status','blocker_level','source_surface','context_json','acceptance_criteria_json','depends_on_json','safety_contract_json','owner_scope','recommendation_or_decision_ref'),'degraded_classification','task_quality_degraded','secrets_included',false),'platform_task_creation|pending_task|checkpoint_followup|recommendation_task','platform_pending_tasks|platform_orchestration_recommendations|platform_evolution_checkpoints','New platform tasks must carry dependencies, acceptance criteria, safety contract, and recommendation/decision reference.'
  UNION ALL SELECT 'Tenant Experience Governance','tenant_proactive_guidance_policy_v1',JSON_OBJECT('rule','tenant_proactive_guidance','after_activation_requires',JSON_ARRAY('workspace','role','activation_mode','devices','connections','validation_states','blocked_or_gated_tools','business_context','next_best_action'),'do_not_require_user_to_name_internal_tool',true,'secrets_included',false),'tenant_gpt|tenant_activation|tenant_guidance|connect_status|workspace_guidance','tenant_gpt_operating_guide|tenant_capability_registry|connect_status|tenant_platform_endpoint_tools','Tenant GPT must guide proactively from an operating snapshot instead of waiting for exact tool names.'
  UNION ALL SELECT 'Runtime Validation Governance','validation_semantics_policy_v1',JSON_OBJECT('rule','validation_semantics','status_active_means','record_and_credentials_present','fully_validated_requires',JSON_ARRAY('same_cycle_live_check','explicit_validation_status_update','readback_ledger'),'forbid_claiming_fully_validated_from_status_active',true,'secrets_included',false),'connection_status|validation_status|tenant_connections|provider_readiness','user_app_connections|credential_intake_connection_status|tenant_infrastructure_routes|tenant_gpt_guidance','Runtime responses must separate status=active from full live validation.'
  UNION ALL SELECT 'Schema Governance','platform_schema_blocker_classification_policy_v1',JSON_OBJECT('rule','platform_schema_blocker_classification','schema_or_collation_errors_are_platform_blockers',true,'not_user_error',true,'not_credential_failure_without_auth_evidence',true,'requires_collation_safe_join_or_policy_repair',true,'secrets_included',false),'schema_error|collation_error|tenant_status_tool|credential_intake_status|runtime_join','database_collation_policy_registry|credential_intake_routes|tenantInfrastructureRoutes|releaseReadiness','Schema/collation failures in tenant-safe tools must be classified as platform blockers, not tenant credential failure.'
  UNION ALL SELECT 'Intelligence Governance','intelligence_policy_rules_required_policy_v1',JSON_OBJECT('rule','active_intelligence_engine_requires_rules','minimum_rules',JSON_ARRAY('default_rule','bypass_deny_rule','approval_rule','readback_rule','no_secret_rule','degraded_fallback_rule'),'blocked_classification','engine_policy_incomplete','secrets_included',false),'intelligence_engine_activation|platform_engine_activation|release_readiness','intelligence_engines|intelligence_policy_rules|platform_engine_registry|platform_engine_policy_rules','Active intelligence engines must have policy rules; engines without rules are incomplete and cannot be treated as enforceable.'
  UNION ALL SELECT 'Agent Runtime Governance','model_never_executes_tools_policy_v1',JSON_OBJECT('rule','model_never_executes_tools','model_may',JSON_ARRAY('generate_candidates','score','explain'),'model_may_not',JSON_ARRAY('execute_tool','bypass_policy','receive_secrets'),'tool_execution_must_be_platform_authorized',true,'secrets_included',false),'agent_loop|model_tool_loop|tool_use|agent_runtime|orchestration_intelligence','agentLoopRunner|agentRuntime|agent_tool_calls|platformEngineRegistry|gptToolsRoutes','Models may propose, score, and explain; platform runtime authorizes and executes tools separately.'
  UNION ALL SELECT 'Domain Architecture Governance','domain_generalization_before_provider_specific_policy_v1',JSON_OBJECT('rule','generic_before_provider_specific','requires_before_provider_specific',JSON_ARRAY('generic_contract','generic_blueprint','provider_profile','provider_specific_implementation','readback'),'applies_to',JSON_ARRAY('ads','wordpress','hostinger','n8n','crm','seo'),'secrets_included',false),'provider_adapter|provider_surface|domain_plugin|capability_family','ads_provider_preflight_contract_registry|ads_provider_preflight_surface_blueprint_registry|provider_profiles|platform_orchestration_plugins','Provider-specific surfaces must be preceded by generic contract and blueprint abstractions.'
  UNION ALL SELECT 'Legacy Migration Governance','legacy_surface_bridge_policy_v1',JSON_OBJECT('rule','legacy_surface_bridge','legacy_surface_requires',JSON_ARRAY('bridge_to_new_authority','migration_plan','readback','deprecation_status'),'legacy_not_final_authority_when_new_orchestration_exists',true,'secrets_included',false),'legacy_surface|legacy_table|legacy_route|migration_bridge','execution_policies|platform_pending_tasks|platform_evolution_checkpoints|logic_definitions|policy_logic_bindings','Legacy surfaces may remain reachable but must have a bridge, migration plan, readback, and deprecation status.'
  UNION ALL SELECT 'Session Memory Governance','session_memory_reliability_policy_v1',JSON_OBJECT('rule','session_memory_reliability','requires',JSON_ARRAY('user_prompt_archived','assistant_reply_archived','tool_turns_archived','summary_generated','old_active_sessions_summarized_or_closed','conversation_ref_linked_when_available'),'secrets_included',false),'session_memory|gpt_session_turns|session_archive|conversation_ref|activation_context','gpt_session_turns|customer_sessions|session_summaries|gpt_session_conversation_refs|release_session_archive_smoke','Session memory must capture user and assistant turns, not only tool evidence, before relying on cross-session intelligence.'
  UNION ALL SELECT 'Release Governance','release_readiness_orchestration_gate_policy_v1',JSON_OBJECT('rule','release_readiness_orchestration_gate','release_must_check',JSON_ARRAY('new_routes_have_openapi','new_tools_have_registry','new_tables_have_lifecycle_collation_policy','new_plugins_have_manifest','new_stages_have_edges','new_intelligence_engines_have_policy_rules','new_recommendations_have_readback','no_secrets_in_outputs'),'secrets_included',false),'release_readiness|pr_gate|migration_review|deployment_gate','releaseReadiness|openapi.yaml|admin_platform_endpoint_tools|tenant_platform_endpoint_tools|platform_engine_policy_rules','Release readiness must fail or warn on ungoverned new surfaces that bypass orchestration intelligence.'
  UNION ALL SELECT 'Development Drift Governance','development_drift_detection_policy_v1',JSON_OBJECT('rule','development_drift_detection','detects',JSON_ARRAY('orphan_tools','orphan_routes','tables_without_lifecycle','tasks_without_acceptance_criteria','engines_without_rules','policies_not_referenced_by_runtime','plugin_stages_without_edges','recommendations_without_decision_run','provider_specific_without_generic_contract'),'secrets_included',false),'architecture_drift|release_readiness|registry_audit|platform_evolution','releaseReadiness|platform_data_source_census|v_platform_capability_gaps|v_platform_relationship_integrity_score','Detect architecture drift early before it becomes runtime degradation.'
  UNION ALL SELECT 'Platform Development Constitution','final_pattern_enforcement_policy_v1',JSON_OBJECT('rule','final_pattern_enforcement','final_pattern',JSON_ARRAY('policy_first','state_aware','orchestration_driven','recommendation_led','gate_enforced','readback_certified','no_secret','no_hidden_execution','generic_before_specific'),'degraded_classification','architecture_degradation','secrets_included',false),'platform_development|runtime_execution|release_readiness|orchestration_intelligence|governed_tools','execution_policies|releaseReadiness|platform_engine_policy_rules|platform_orchestration_recommendations|capability_resolution_envelope_ledger','Top-level enforcement policy: all platform development must follow the final governed intelligence pattern.'
) n
WHERE NOT EXISTS (
  SELECT 1 FROM `execution_policies` ep
  WHERE ep.`policy_group` = n.policy_group
    AND ep.`policy_key` = n.policy_key
);

UPDATE `execution_policies` ep
JOIN (
  SELECT 'Platform Development Constitution' AS policy_group, 'platform_development_constitution_policy_v1' AS policy_key UNION ALL
  SELECT 'Orchestration Intelligence Governance','orchestration_first_development_policy_v1' UNION ALL
  SELECT 'Orchestration Intelligence Governance','orchestration_state_snapshot_required_policy_v1' UNION ALL
  SELECT 'Orchestration Intelligence Governance','recommendation_before_execution_policy_v1' UNION ALL
  SELECT 'Orchestration Intelligence Governance','intentional_safety_block_classification_policy_v1' UNION ALL
  SELECT 'Execution Safety Governance','no_hidden_execution_policy_v1' UNION ALL
  SELECT 'Plugin Governance','plugin_manifest_completeness_policy_v1' UNION ALL
  SELECT 'Orchestration Intelligence Governance','orchestration_stage_graph_completeness_policy_v1' UNION ALL
  SELECT 'Task Governance','platform_task_quality_gate_policy_v1' UNION ALL
  SELECT 'Tenant Experience Governance','tenant_proactive_guidance_policy_v1' UNION ALL
  SELECT 'Runtime Validation Governance','validation_semantics_policy_v1' UNION ALL
  SELECT 'Schema Governance','platform_schema_blocker_classification_policy_v1' UNION ALL
  SELECT 'Intelligence Governance','intelligence_policy_rules_required_policy_v1' UNION ALL
  SELECT 'Agent Runtime Governance','model_never_executes_tools_policy_v1' UNION ALL
  SELECT 'Domain Architecture Governance','domain_generalization_before_provider_specific_policy_v1' UNION ALL
  SELECT 'Legacy Migration Governance','legacy_surface_bridge_policy_v1' UNION ALL
  SELECT 'Session Memory Governance','session_memory_reliability_policy_v1' UNION ALL
  SELECT 'Release Governance','release_readiness_orchestration_gate_policy_v1' UNION ALL
  SELECT 'Development Drift Governance','development_drift_detection_policy_v1' UNION ALL
  SELECT 'Platform Development Constitution','final_pattern_enforcement_policy_v1'
) required
  ON ep.`policy_group` = required.policy_group
 AND ep.`policy_key` = required.policy_key
SET ep.`active` = 'TRUE',
    ep.`blocking` = 'TRUE',
    ep.`updated_at` = CURRENT_TIMESTAMP;
