-- Support two governed recovery options for loading newly merged production routes:
-- A) Hostinger deploy/release at expected main commit.
-- B) Hostinger break-glass app restart.
-- This migration enables discovery, dry-run certification, authority policy, and runbook support only.
-- It does not execute deploy, restart, SSH, provider dispatch, or return secrets.

INSERT INTO platform_resource_authority_requirements
(requirement_key, resource_family, operation_class, display_name, description, required_gates_json, authority_sources_json, credential_scope_required, active_grant_required, ownership_claim_required, audit_required, readback_required, break_glass_allowed, apply_allowed, secrets_may_be_returned, status, notes)
VALUES
('hostinger_ssh_deploy_release_authority_v1','hostinger_ssh','external_write','Hostinger SSH Deploy Release Authority','Authority policy for production Hostinger deploy/release of auth.mad4b.com. Requires resource grant, same-cycle dry-run, dispatch certification, capability envelope, bounded output, and post-deploy readback.',JSON_OBJECT('required',JSON_ARRAY('workspace_resource_grant','dispatch_certification_allowed','same_cycle_dry_run','capability_envelope_ready_for_dispatch','expected_commit_sha','path_allowlist','audit_evidence','post_deploy_readback'),'forbidden',JSON_ARRAY('inline_secret','freeform_shell','direct_unbounded_output')),JSON_OBJECT('sources',JSON_ARRAY('platform_resource_authority_bindings','runtime_dispatch_certification_registry','capability_resolution_envelope_ledger','remote_runtime_targets')),0,1,1,1,1,0,1,0,'active','Supports governed deploy option without bypassing certification, envelope, or readback gates.'),
('hostinger_ssh_restart_app_authority_v1','hostinger_ssh','destructive','Hostinger SSH Restart App Authority','Break-glass authority policy for restarting auth.mad4b.com Node app after approved deployment or route-load failure. Requires explicit break-glass reason, audit evidence, and readback.',JSON_OBJECT('required',JSON_ARRAY('workspace_resource_grant','dispatch_certification_allowed','capability_envelope_ready_for_dispatch','break_glass_reason','audit_evidence','post_restart_readback'),'forbidden',JSON_ARRAY('deploy_write','inline_secret','freeform_shell','unbounded_output')),JSON_OBJECT('sources',JSON_ARRAY('platform_resource_authority_bindings','runtime_dispatch_certification_registry','capability_resolution_envelope_ledger','remote_runtime_targets')),0,1,1,1,1,1,1,0,'active','Supports governed restart option as break-glass recovery only; no deploy write is authorized by restart authority.')
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name), description=VALUES(description), required_gates_json=VALUES(required_gates_json), authority_sources_json=VALUES(authority_sources_json), credential_scope_required=VALUES(credential_scope_required), active_grant_required=VALUES(active_grant_required), ownership_claim_required=VALUES(ownership_claim_required), audit_required=VALUES(audit_required), readback_required=VALUES(readback_required), break_glass_allowed=VALUES(break_glass_allowed), apply_allowed=VALUES(apply_allowed), secrets_may_be_returned=VALUES(secrets_may_be_returned), status=VALUES(status), notes=VALUES(notes);

INSERT INTO resource_authority_route_family_registry
(route_family_key, display_name, route_family, operation_class, risk_class, resource_authority_required, authority_requirement_key, dry_run_required, audit_required, readback_required, apply_allowed_default, enforcement_status, runtime_surface, notes)
VALUES
('remote_runtime_hostinger_deploy_release_v1','Remote Runtime Hostinger Deploy Release','remote_runtime_hostinger_deploy','external_write','high',1,'hostinger_ssh_deploy_release_authority_v1',1,1,1,1,'execution_gated_supported','remote_runtime_hostinger_deploy_release','Deploy/release route family is supported only through certification, dry-run, capability envelope, audit and readback.'),
('hostinger_ssh_restart_app_v1','Hostinger SSH Restart App','remote_runtime_hostinger_restart','destructive','high',1,'hostinger_ssh_restart_app_authority_v1',1,1,1,1,'break_glass_execution_gated_supported','hostinger_ssh_restart_app','Restart route family is supported as break-glass recovery only; deploy writes are not covered by restart authority.')
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name), route_family=VALUES(route_family), operation_class=VALUES(operation_class), risk_class=VALUES(risk_class), resource_authority_required=VALUES(resource_authority_required), authority_requirement_key=VALUES(authority_requirement_key), dry_run_required=VALUES(dry_run_required), audit_required=VALUES(audit_required), readback_required=VALUES(readback_required), apply_allowed_default=VALUES(apply_allowed_default), enforcement_status=VALUES(enforcement_status), runtime_surface=VALUES(runtime_surface), notes=VALUES(notes);

INSERT INTO capability_apply_authorization_policy_registry
(policy_key, app_key, capability_key, operation_intent, runtime_surface, status, allow_external_write, allow_credential_binding, allow_no_credential_binding, requires_ready_for_dispatch, requires_dispatch_allowed, requires_zero_blocking_gaps, requires_audit_evidence, requires_readback, requires_typed_confirmation, requires_same_cycle_dry_run, allowed_source_tiers_json, policy_json, notes)
VALUES
('hostinger_deploy_release_apply_policy_v1','hostinger','remote_runtime_hostinger_deploy_release','deploy','remote_runtime_hostinger_deploy_release','active',1,0,1,1,1,1,1,1,1,1,JSON_ARRAY('tenant_managed','platform_managed'),JSON_OBJECT('expected_commit_sha_required',true,'path_allowlist_required',true,'restart_optional',true,'feature_flag_required','REMOTE_RUNTIME_HOSTINGER_SSH_EXECUTOR_ENABLED','actual_execution_requires_capability_envelope',true,'secrets_included',false),'Apply policy for governed Hostinger deploy release option.'),
('hostinger_restart_app_apply_policy_v1','hostinger','hostinger_ssh_restart_app','restart','hostinger_ssh_restart_app','active',1,0,1,1,1,1,1,1,1,1,JSON_ARRAY('tenant_managed','platform_managed'),JSON_OBJECT('break_glass_reason_required',true,'deploy_write_allowed',false,'feature_flag_required','REMOTE_RUNTIME_HOSTINGER_SSH_RESTART_ENABLED','actual_execution_requires_capability_envelope',true,'secrets_included',false),'Apply policy for governed Hostinger restart option.')
ON DUPLICATE KEY UPDATE app_key=VALUES(app_key), capability_key=VALUES(capability_key), operation_intent=VALUES(operation_intent), runtime_surface=VALUES(runtime_surface), status=VALUES(status), allow_external_write=VALUES(allow_external_write), allow_credential_binding=VALUES(allow_credential_binding), allow_no_credential_binding=VALUES(allow_no_credential_binding), requires_ready_for_dispatch=VALUES(requires_ready_for_dispatch), requires_dispatch_allowed=VALUES(requires_dispatch_allowed), requires_zero_blocking_gaps=VALUES(requires_zero_blocking_gaps), requires_audit_evidence=VALUES(requires_audit_evidence), requires_readback=VALUES(requires_readback), requires_typed_confirmation=VALUES(requires_typed_confirmation), requires_same_cycle_dry_run=VALUES(requires_same_cycle_dry_run), allowed_source_tiers_json=VALUES(allowed_source_tiers_json), policy_json=VALUES(policy_json), notes=VALUES(notes);

UPDATE remote_runtime_command_allowlists
SET status='active',
    notes=CONCAT(COALESCE(notes,''), CASE WHEN notes IS NULL OR notes='' THEN '' ELSE '\n' END, 'Enabled as break-glass execution-gated restart option only; requires approval, capability envelope, audit evidence, and post-restart readback. No deploy write is authorized by restart command.')
WHERE plugin_key='remote_ssh_runtime'
  AND command_key='restart_app'
  AND target_kind='hosting_account';

INSERT INTO runtime_dispatch_certification_registry
(certification_key, surface_key, surface_family, tool_or_action_key, risk_class, certification_status, smoke_strategy, dispatch_allowed, apply_allowed, requires_resource_authority, requires_dry_run, requires_audit_evidence, requires_readback, last_evidence_ref, last_certified_at, expires_at, notes)
VALUES
('remote_runtime_hostinger_deploy_release','remote_runtime_hostinger_deploy_release','remote_runtime_hostinger_deploy','remote_runtime_hostinger_deploy_release','high','positive_dry_run_passed_execution_gated_certified','same_cycle_dry_run_then_capability_envelope_then_post_deploy_readback',1,1,1,1,1,1,'remote_runtime_dispatch_dry_run:trace=remote_runtime_dispatch_dry_run_b508f16d-2a96-4c0c-9636-2e442349294e:dispatch_ready=true',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),'Exact-key certification matching capability_key. Dry-run only; actual deploy remains envelope, feature flag, audit, path, SHA and readback gated.'),
('remote_runtime_hostinger_deploy_release_v1','remote_runtime_hostinger_deploy_release','remote_runtime_hostinger_deploy','remote_runtime_hostinger_deploy_release','high','positive_dry_run_passed_execution_gated_certified','same_cycle_dry_run_then_capability_envelope_then_post_deploy_readback',1,1,1,1,1,1,'remote_runtime_dispatch_dry_run:trace=remote_runtime_dispatch_dry_run_b508f16d-2a96-4c0c-9636-2e442349294e:dispatch_ready=true',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),'Alias certification matching runtime_surface exactly. Dry-run only; actual deploy remains gated.'),
('hostinger_ssh_restart_app','hostinger_ssh_restart_app','remote_runtime_hostinger_restart','hostinger_ssh_restart_app','high','positive_dry_run_passed_break_glass_execution_gated_certified','same_cycle_restart_dry_run_then_capability_envelope_then_post_restart_readback',1,1,1,1,1,1,'remote_runtime_dispatch_dry_run:trace=remote_runtime_dispatch_dry_run_38103bbd-1bb4-421c-8363-3bbf79496822:dispatch_ready=true',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),'Exact-key certification matching capability_key. Restart dry-run only; actual restart remains envelope, break-glass reason, audit and readback gated.'),
('hostinger_ssh_restart_app_v1','hostinger_ssh_restart_app','remote_runtime_hostinger_restart','hostinger_ssh_restart_app','high','positive_dry_run_passed_break_glass_execution_gated_certified','same_cycle_restart_dry_run_then_capability_envelope_then_post_restart_readback',1,1,1,1,1,1,'remote_runtime_dispatch_dry_run:trace=remote_runtime_dispatch_dry_run_38103bbd-1bb4-421c-8363-3bbf79496822:dispatch_ready=true',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),'Restart dry-run certified only; actual restart requires capability envelope, break-glass reason, audit evidence and readback.')
ON DUPLICATE KEY UPDATE surface_key=VALUES(surface_key), surface_family=VALUES(surface_family), tool_or_action_key=VALUES(tool_or_action_key), risk_class=VALUES(risk_class), certification_status=VALUES(certification_status), smoke_strategy=VALUES(smoke_strategy), dispatch_allowed=VALUES(dispatch_allowed), apply_allowed=VALUES(apply_allowed), requires_resource_authority=VALUES(requires_resource_authority), requires_dry_run=VALUES(requires_dry_run), requires_audit_evidence=VALUES(requires_audit_evidence), requires_readback=VALUES(requires_readback), last_evidence_ref=VALUES(last_evidence_ref), last_certified_at=VALUES(last_certified_at), expires_at=VALUES(expires_at), notes=VALUES(notes);

UPDATE admin_platform_endpoint_tools
SET is_enabled = 1,
    tags = CASE WHEN tags LIKE '%execution_gated%' THEN tags ELSE CONCAT(COALESCE(tags,''), ',execution_gated,capability_envelope_required,readback_required,no_secrets') END,
    description = CONCAT(description, ' Enabled for governed dry-run, envelope, audit and readback flow. Actual execution remains feature-flag and capability gated.')
WHERE tool_key IN ('remote_runtime_hostinger_deploy_release','hostinger_ssh_restart_app');

CREATE OR REPLACE VIEW v_platform_exports_current AS
SELECT CONCAT('admin_tool_export.', t.tool_key) AS export_key, CONCAT('admin_tool.', t.tool_key) AS capability_key, 'admin_platform_tool' AS export_surface, 'admin_platform_endpoint_tools' AS source_table, CAST(t.tool_key AS CHAR(255)) AS source_key, CASE WHEN t.is_enabled = 1 THEN 'active' ELSE 'disabled' END AS export_status, 'admin' AS exposure_scope, t.http_method AS http_method, t.http_path AS http_path, t.description AS notes FROM admin_platform_endpoint_tools t
UNION ALL
SELECT CONCAT('tenant_tool_export.', t.tool_key) AS export_key, CONCAT('tenant_tool.', t.tool_key) AS capability_key, 'tenant_platform_tool' AS export_surface, 'tenant_platform_endpoint_tools' AS source_table, CAST(t.tool_key AS CHAR(255)) AS source_key, CASE WHEN t.is_enabled = 1 THEN 'active' ELSE 'disabled' END AS export_status, 'tenant' AS exposure_scope, t.http_method AS http_method, t.http_path AS http_path, t.description AS notes FROM tenant_platform_endpoint_tools t
UNION ALL
SELECT CONCAT('resource_authority_route_family_export.', r.route_family_key) AS export_key, CONCAT('resource_authority_route_family.', r.route_family_key) AS capability_key, 'resource_authority_route_family' AS export_surface, 'resource_authority_route_family_registry' AS source_table, CAST(r.route_family_key AS CHAR(255)) AS source_key, CASE WHEN r.apply_allowed_default = 1 THEN 'active' ELSE 'disabled' END AS export_status, 'internal' AS exposure_scope, NULL AS http_method, r.runtime_surface AS http_path, r.notes AS notes FROM resource_authority_route_family_registry r
UNION ALL
SELECT CONCAT('runtime_dispatch_certification_export.', c.certification_key) AS export_key, CONCAT('runtime_dispatch_certification.', c.certification_key) AS capability_key, 'runtime_dispatch_certification' AS export_surface, 'runtime_dispatch_certification_registry' AS source_table, CAST(c.certification_key AS CHAR(255)) AS source_key, CASE WHEN c.dispatch_allowed = 1 THEN 'active' ELSE 'disabled' END AS export_status, 'internal' AS exposure_scope, NULL AS http_method, c.surface_key AS http_path, c.notes AS notes FROM runtime_dispatch_certification_registry c;

UPDATE runtime_gap_remediation_registry
SET recommended_action='Two governed options are supported: A deploy or release auth.mad4b.com at expected main commit using remote_runtime_hostinger_deploy_release, or B break-glass restart auth.mad4b.com using hostinger_ssh_restart_app. Both require final approval, capability envelope, audit evidence and post-action operational console readback.',
    runbook_json=JSON_SET(COALESCE(runbook_json, JSON_OBJECT()),
      '$.supported_options', JSON_ARRAY(
        JSON_OBJECT('option_key','deploy_release','capability_key','remote_runtime_hostinger_deploy_release','runtime_surface','remote_runtime_hostinger_deploy_release','execution_note','Actual deploy is not executed by support registration; it still requires approval, expected SHA, path allowlist, audit and readback.'),
        JSON_OBJECT('option_key','restart_app','capability_key','hostinger_ssh_restart_app','runtime_surface','hostinger_ssh_restart_app','execution_note','Actual restart is not executed by support registration; it still requires approval, break-glass reason, audit and readback.')
      ),
      '$.success_condition','Either approved deploy release or approved restart succeeds, then operational_console_read_api returns ok and secrets_included=false; runtime parity has blocking_gap_count=0'
    )
WHERE gap_key='operational_console_route_not_loaded';
