-- 902_sprint68_dynamic_capability_apply_authorization_policy.sql
-- Purpose: replace hardcoded apply-authorization allowlists with a DB-backed
-- policy registry. This migration is registry-only; it does not authorize any
-- existing envelope, execute provider calls, create Drive files, expose secrets,
-- or bypass runtime typed-confirmation/readback gates.

CREATE TABLE IF NOT EXISTS `capability_apply_authorization_policy_registry` (
  `policy_key` varchar(191) NOT NULL,
  `app_key` varchar(128) NOT NULL,
  `capability_key` varchar(191) NOT NULL,
  `operation_intent` varchar(191) DEFAULT NULL,
  `runtime_surface` varchar(191) NOT NULL,
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `allow_external_write` tinyint(1) NOT NULL DEFAULT 0,
  `allow_credential_binding` tinyint(1) NOT NULL DEFAULT 0,
  `allow_no_credential_binding` tinyint(1) NOT NULL DEFAULT 1,
  `requires_ready_for_dispatch` tinyint(1) NOT NULL DEFAULT 1,
  `requires_dispatch_allowed` tinyint(1) NOT NULL DEFAULT 1,
  `requires_zero_blocking_gaps` tinyint(1) NOT NULL DEFAULT 1,
  `requires_audit_evidence` tinyint(1) NOT NULL DEFAULT 1,
  `requires_readback` tinyint(1) NOT NULL DEFAULT 1,
  `requires_typed_confirmation` tinyint(1) NOT NULL DEFAULT 1,
  `requires_same_cycle_dry_run` tinyint(1) NOT NULL DEFAULT 1,
  `allowed_source_tiers_json` json DEFAULT NULL,
  `policy_json` json DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`policy_key`),
  UNIQUE KEY `uq_capability_apply_auth_policy_match` (`app_key`,`capability_key`,`runtime_surface`),
  KEY `idx_capability_apply_auth_policy_lookup` (`capability_key`,`app_key`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `capability_apply_authorization_policy_registry` (
  `policy_key`,
  `app_key`,
  `capability_key`,
  `operation_intent`,
  `runtime_surface`,
  `status`,
  `allow_external_write`,
  `allow_credential_binding`,
  `allow_no_credential_binding`,
  `requires_ready_for_dispatch`,
  `requires_dispatch_allowed`,
  `requires_zero_blocking_gaps`,
  `requires_audit_evidence`,
  `requires_readback`,
  `requires_typed_confirmation`,
  `requires_same_cycle_dry_run`,
  `allowed_source_tiers_json`,
  `policy_json`,
  `notes`
)
VALUES
  (
    'ads_provider_governance_snapshot_record_apply_v1',
    'platform_orchestration',
    'ads_provider_governance_snapshot_record',
    'ads_provider_governance_snapshot_record',
    'ads_provider_governance_snapshot_record',
    'active',
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    JSON_ARRAY('platform_managed_fallback'),
    JSON_OBJECT(
      'external_write_allowed', false,
      'provider_call_allowed', false,
      'credential_payload_read_allowed', false,
      'spend_change_allowed', false,
      'graph_write_expected', true,
      'secrets_included', false
    ),
    'Existing internal no-credential orchestration snapshot/recommendation record apply authorization policy.'
  ),
  (
    'resource_manifest_create_google_drive_apply_v1',
    'google_drive',
    'resource_manifest_create',
    'manifest.create_after_review',
    'governed_resource_run',
    'active',
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    JSON_ARRAY('tenant_managed','workspace_owner_managed','platform_managed_fallback'),
    JSON_OBJECT(
      'external_write_allowed', true,
      'provider_call_allowed', true,
      'provider_call_surface', 'google_drive_api.uploadNewFile',
      'readback_surface', 'google_drive_api.getFileMetadata',
      'credential_payload_read_allowed', false,
      'overwrite_allowed', false,
      'graph_write_allowed', false,
      'file_content_read_allowed', false,
      'secrets_included', false
    ),
    'External Google Drive manifest create apply authorization policy. Runtime must still enforce exact typed confirmation, same-cycle dry-run hash, uploadNewFile only, getFileMetadata readback, no overwrite, no graph write, no file-content read, and no secrets.'
  )
ON DUPLICATE KEY UPDATE
  `app_key` = VALUES(`app_key`),
  `capability_key` = VALUES(`capability_key`),
  `operation_intent` = VALUES(`operation_intent`),
  `runtime_surface` = VALUES(`runtime_surface`),
  `status` = VALUES(`status`),
  `allow_external_write` = VALUES(`allow_external_write`),
  `allow_credential_binding` = VALUES(`allow_credential_binding`),
  `allow_no_credential_binding` = VALUES(`allow_no_credential_binding`),
  `requires_ready_for_dispatch` = VALUES(`requires_ready_for_dispatch`),
  `requires_dispatch_allowed` = VALUES(`requires_dispatch_allowed`),
  `requires_zero_blocking_gaps` = VALUES(`requires_zero_blocking_gaps`),
  `requires_audit_evidence` = VALUES(`requires_audit_evidence`),
  `requires_readback` = VALUES(`requires_readback`),
  `requires_typed_confirmation` = VALUES(`requires_typed_confirmation`),
  `requires_same_cycle_dry_run` = VALUES(`requires_same_cycle_dry_run`),
  `allowed_source_tiers_json` = VALUES(`allowed_source_tiers_json`),
  `policy_json` = VALUES(`policy_json`),
  `notes` = VALUES(`notes`),
  `updated_at` = CURRENT_TIMESTAMP;
