-- Sprint 68: Support Ticket orchestration completion readbacks.
-- No ticket mutation, workflow dispatch, approval decision, external send/write,
-- provider call, credential payload read, spend change, deploy/publish, or secrets.

CREATE OR REPLACE VIEW `v_platform_orchestration_support_ticket_external_delivery_readiness` AS
SELECT
  'support_ticket_external_delivery_orchestrator' AS `plugin_key`,
  (SELECT COUNT(*) FROM `platform_orchestration_stages` WHERE `plugin_key`='support_ticket_external_delivery_orchestrator') AS `stage_count`,
  (SELECT COUNT(*) FROM `platform_orchestration_edges` WHERE `plugin_key`='support_ticket_external_delivery_orchestrator') AS `edge_count`,
  7 AS `expected_stage_count`,
  6 AS `expected_edge_count`,
  (SELECT COUNT(*) FROM `credential_bindings`) AS `credential_binding_rows`,
  (SELECT COUNT(*) FROM `credential_intake_sessions`) AS `credential_intake_rows`,
  (SELECT COUNT(*) FROM `external_delivery_provider_adapter_enablement_proposals`) AS `adapter_enablement_proposal_rows`,
  (SELECT COUNT(*) FROM `external_delivery_provider_adapter_readiness_checklists`) AS `adapter_readiness_checklist_rows`,
  (SELECT COUNT(*) FROM `external_delivery_provider_adapter_readiness_decisions`) AS `adapter_readiness_decision_rows`,
  (SELECT COUNT(*) FROM `external_delivery_provider_send_mode_policy_registry`) AS `send_mode_policy_rows`,
  (SELECT COUNT(*) FROM `ticket_workflow_links` WHERE `relationship` LIKE 'external_%') AS `external_workflow_link_rows`,
  CASE WHEN (SELECT COUNT(*) FROM `platform_orchestration_stages` WHERE `plugin_key`='support_ticket_external_delivery_orchestrator') >= 7
         AND (SELECT COUNT(*) FROM `platform_orchestration_edges` WHERE `plugin_key`='support_ticket_external_delivery_orchestrator') >= 6
       THEN 'ready_readonly_external_delivery_graph'
       ELSE 'degraded_external_delivery_graph_incomplete'
  END AS `readiness_status`,
  JSON_OBJECT('no_provider_call',true,'no_credential_payload_read',true,'no_external_send',true,'no_external_write',true,'no_deploy',true,'no_publish',true,'secrets_included',false) AS `safety_json`,
  JSON_OBJECT('mode','read_only','external_send_performed',false,'secrets_included',false) AS `evidence_json`,
  0 AS `secrets_included`;

INSERT INTO `platform_orchestration_plugins` (`plugin_key`,`display_name`,`domain_key`,`plugin_type`,`owner_scope`,`version`,`lifecycle_stage`,`engine_key`,`policy_key`,`readback_tool_key`,`manifest_json`,`safety_contract_json`,`status`,`notes`,`secrets_included`) VALUES
('support_ticket_external_delivery_orchestrator','Support Ticket External Delivery Orchestrator','support_ticket_external_delivery','orchestration_graph','platform_admin','v1','foundation','orchestration_intelligence_engine','orchestration_intelligence_policy_v1','platform_orchestration_readback',JSON_OBJECT('domain','support_ticket_external_delivery','graph_version','v1','subject_type','external_delivery_gate','execution_enabled_default',false,'stages',JSON_ARRAY('delivery_intake','send_mode_policy','credential_readiness','adapter_readiness','approval_gate','send_execution_gate','recommendation_candidate')),JSON_OBJECT('no_provider_call',true,'no_credential_payload_read',true,'no_external_send',true,'no_external_write',true,'no_deploy',true,'no_publish',true,'recommendation_only',true,'secrets_included',false),'active','Read-only graph over Support Ticket external delivery readiness, credential intake/binding, adapter readiness, approval gating, and send-mode policy.',0)
ON DUPLICATE KEY UPDATE `display_name`=VALUES(`display_name`),`domain_key`=VALUES(`domain_key`),`plugin_type`=VALUES(`plugin_type`),`manifest_json`=VALUES(`manifest_json`),`safety_contract_json`=VALUES(`safety_contract_json`),`status`=VALUES(`status`),`notes`=VALUES(`notes`),`updated_at`=CURRENT_TIMESTAMP;

INSERT INTO `platform_orchestration_stages` (`stage_key`,`plugin_key`,`stage_order`,`display_name`,`stage_type`,`required_inputs_json`,`produced_outputs_json`,`required_tables_json`,`required_tools_json`,`required_policies_json`,`acceptance_criteria_json`,`safety_contract_json`,`status`,`notes`,`secrets_included`) VALUES
('support_ticket_external.delivery_intake','support_ticket_external_delivery_orchestrator',10,'External Delivery Intake','state_readiness',JSON_ARRAY('ticket_id'),JSON_ARRAY('delivery_intake_state'),JSON_ARRAY('ticket_workflow_links','approval_holds'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('support_ticket_external_delivery_orchestration_readback_policy_v1'),JSON_ARRAY('external_delivery_links_readable','no_external_send'),JSON_OBJECT('no_external_send',true,'secrets_included',false),'active','Reads external delivery links and approvals only.',0),
('support_ticket_external.send_mode_policy','support_ticket_external_delivery_orchestrator',20,'Send Mode Policy','policy_readiness',JSON_ARRAY('delivery_intake_state'),JSON_ARRAY('send_mode_policy_state'),JSON_ARRAY('external_delivery_provider_send_mode_policy_registry'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('support_ticket_external_delivery_orchestration_readback_policy_v1'),JSON_ARRAY('send_mode_policy_known','record_only_default'),JSON_OBJECT('no_external_send',true,'secrets_included',false),'active','Reads provider send-mode policy registry; no send performed.',0),
('support_ticket_external.credential_readiness','support_ticket_external_delivery_orchestrator',30,'Credential Readiness','credential_readiness',JSON_ARRAY('delivery_intake_state'),JSON_ARRAY('credential_readiness_state'),JSON_ARRAY('credential_bindings','credential_intake_sessions'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('support_ticket_external_delivery_orchestration_readback_policy_v1'),JSON_ARRAY('credential_binding_or_intake_state_known','no_secret_payloads'),JSON_OBJECT('no_credential_payload_read',true,'secrets_included',false),'active','Reads credential references/intake state only.',0),
('support_ticket_external.adapter_readiness','support_ticket_external_delivery_orchestrator',40,'Adapter Readiness','adapter_readiness',JSON_ARRAY('credential_readiness_state'),JSON_ARRAY('adapter_readiness_state'),JSON_ARRAY('external_delivery_provider_adapter_enablement_proposals','external_delivery_provider_adapter_readiness_checklists','external_delivery_provider_adapter_readiness_decisions'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('support_ticket_external_delivery_orchestration_readback_policy_v1'),JSON_ARRAY('adapter_readiness_state_known','no_provider_call'),JSON_OBJECT('no_provider_call',true,'secrets_included',false),'active','Reads adapter enablement/readiness evidence only.',0),
('support_ticket_external.approval_gate','support_ticket_external_delivery_orchestrator',50,'External Delivery Approval Gate','approval_readiness',JSON_ARRAY('adapter_readiness_state'),JSON_ARRAY('approval_gate_state'),JSON_ARRAY('approval_holds','ticket_workflow_links'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('support_ticket_external_delivery_orchestration_readback_policy_v1'),JSON_ARRAY('approval_state_known','approval_not_decided'),JSON_OBJECT('no_external_write',true,'secrets_included',false),'active','Reads approval gate only; does not decide approval.',0),
('support_ticket_external.send_execution_gate','support_ticket_external_delivery_orchestrator',60,'Send Execution Gate','execution_gate_readiness',JSON_ARRAY('approval_gate_state'),JSON_ARRAY('send_execution_gate_state'),JSON_ARRAY('ticket_workflow_links'),JSON_ARRAY('support_ticket_external_delivery_readback'),JSON_ARRAY('no_hidden_execution_policy_v1'),JSON_ARRAY('send_execution_remains_blocked','external_send_false'),JSON_OBJECT('no_external_send',true,'no_external_write',true,'secrets_included',false),'active','Confirms external send/write remains blocked/read-only.',0),
('support_ticket_external.recommendation_candidate','support_ticket_external_delivery_orchestrator',70,'External Delivery Recommendation Candidate','recommendation_candidate',JSON_ARRAY('send_execution_gate_state'),JSON_ARRAY('external_delivery_recommendation_candidate'),JSON_ARRAY('platform_orchestration_recommendations','platform_pending_tasks'),JSON_ARRAY('platform_orchestration_readback'),JSON_ARRAY('recommendation_before_execution_policy_v1'),JSON_ARRAY('recommendation_only','separate_capability_required_before_any_send'),JSON_OBJECT('recommendation_only',true,'requires_separate_capability_envelope',true,'secrets_included',false),'active','Produces read-only next-action candidates for external delivery readiness.',0)
ON DUPLICATE KEY UPDATE `stage_order`=VALUES(`stage_order`),`display_name`=VALUES(`display_name`),`stage_type`=VALUES(`stage_type`),`required_inputs_json`=VALUES(`required_inputs_json`),`produced_outputs_json`=VALUES(`produced_outputs_json`),`required_tables_json`=VALUES(`required_tables_json`),`required_tools_json`=VALUES(`required_tools_json`),`required_policies_json`=VALUES(`required_policies_json`),`acceptance_criteria_json`=VALUES(`acceptance_criteria_json`),`safety_contract_json`=VALUES(`safety_contract_json`),`status`=VALUES(`status`),`notes`=VALUES(`notes`),`secrets_included`=VALUES(`secrets_included`),`updated_at`=CURRENT_TIMESTAMP;

INSERT INTO `platform_orchestration_edges` (`edge_key`,`plugin_key`,`from_stage_key`,`to_stage_key`,`edge_type`,`condition_json`,`safety_contract_json`,`status`,`notes`,`secrets_included`) VALUES
('support_ticket_external.intake_to_send_mode','support_ticket_external_delivery_orchestrator','support_ticket_external.delivery_intake','support_ticket_external.send_mode_policy','requires_delivery_intake',JSON_OBJECT('requires','delivery_intake_state_known'),JSON_OBJECT('no_external_send',true,'secrets_included',false),'active','Send-mode policy after delivery intake.',0),
('support_ticket_external.send_mode_to_credential','support_ticket_external_delivery_orchestrator','support_ticket_external.send_mode_policy','support_ticket_external.credential_readiness','requires_send_mode_policy',JSON_OBJECT('requires','send_mode_policy_known'),JSON_OBJECT('no_credential_payload_read',true,'secrets_included',false),'active','Credential readiness after send-mode policy.',0),
('support_ticket_external.credential_to_adapter','support_ticket_external_delivery_orchestrator','support_ticket_external.credential_readiness','support_ticket_external.adapter_readiness','requires_credential_state',JSON_OBJECT('requires','credential_reference_or_intake_state_known'),JSON_OBJECT('no_provider_call',true,'secrets_included',false),'active','Adapter readiness after credential state.',0),
('support_ticket_external.adapter_to_approval','support_ticket_external_delivery_orchestrator','support_ticket_external.adapter_readiness','support_ticket_external.approval_gate','requires_adapter_state',JSON_OBJECT('requires','adapter_readiness_state_known'),JSON_OBJECT('no_external_write',true,'secrets_included',false),'active','Approval gate after adapter readiness.',0),
('support_ticket_external.approval_to_send_gate','support_ticket_external_delivery_orchestrator','support_ticket_external.approval_gate','support_ticket_external.send_execution_gate','requires_approval_state',JSON_OBJECT('requires','approval_state_known_or_required'),JSON_OBJECT('no_external_send',true,'secrets_included',false),'active','Send execution remains gated after approval state.',0),
('support_ticket_external.send_gate_to_recommendation','support_ticket_external_delivery_orchestrator','support_ticket_external.send_execution_gate','support_ticket_external.recommendation_candidate','recommendation_only',JSON_OBJECT('requires','send_execution_gate_state_known','execution_without_envelope','blocked'),JSON_OBJECT('recommendation_only',true,'secrets_included',false),'active','External delivery produces recommendation-only output.',0)
ON DUPLICATE KEY UPDATE `from_stage_key`=VALUES(`from_stage_key`),`to_stage_key`=VALUES(`to_stage_key`),`edge_type`=VALUES(`edge_type`),`condition_json`=VALUES(`condition_json`),`safety_contract_json`=VALUES(`safety_contract_json`),`status`=VALUES(`status`),`notes`=VALUES(`notes`),`secrets_included`=VALUES(`secrets_included`),`updated_at`=CURRENT_TIMESTAMP;

INSERT INTO `admin_platform_endpoint_tools` (`tool_key`,`display_name`,`description`,`http_method`,`http_path`,`path_param_keys`,`input_schema`,`fixed_body`,`tags`,`is_enabled`,`sort_order`) VALUES
('support_ticket_lifecycle_next_action_readback','Support Ticket Lifecycle Next Action Readback','Read-only admin/customer guidance over the latest recorded Support Ticket lifecycle snapshot and recommendation.','POST','/platform/orchestration/support-ticket/next-action-readback',NULL,JSON_OBJECT('type','object','required',JSON_ARRAY('ticket_id'),'properties',JSON_OBJECT('ticket_id',JSON_OBJECT('type','string','minLength',1,'maxLength',128)),'additionalProperties',false),NULL,'admin,orchestration_intelligence,support_ticket_lifecycle,next_action_readback,read_only,no_execution,no_secrets',1,644),
('support_ticket_external_delivery_readback','Support Ticket External Delivery Readback','Read-only Support Ticket external delivery readiness. No external send/write, provider call, credential payload read, workflow dispatch, ticket mutation, deploy, publish, or secrets.','POST','/platform/orchestration/support-ticket/external-delivery/readback',NULL,JSON_OBJECT('type','object','properties',JSON_OBJECT('tenant_id',JSON_OBJECT('type','string'),'limit',JSON_OBJECT('type','integer','minimum',1,'maximum',50)),'additionalProperties',false),NULL,'admin,orchestration_intelligence,support_ticket_external_delivery,readback,read_only,no_external_send,no_provider_call,no_secrets',1,645)
ON DUPLICATE KEY UPDATE `display_name`=VALUES(`display_name`),`description`=VALUES(`description`),`http_method`=VALUES(`http_method`),`http_path`=VALUES(`http_path`),`input_schema`=VALUES(`input_schema`),`tags`=VALUES(`tags`),`is_enabled`=VALUES(`is_enabled`),`sort_order`=VALUES(`sort_order`),`updated_at`=CURRENT_TIMESTAMP;

INSERT INTO `execution_policies` (`policy_group`,`policy_key`,`policy_value`,`active`,`execution_scope`,`affects_layer`,`blocking`,`notes`)
SELECT 'Orchestration Intelligence Governance','support_ticket_orchestration_completion_readbacks_policy_v1',JSON_OBJECT('rule','support_ticket_orchestration_completion_readbacks','tools',JSON_ARRAY('support_ticket_lifecycle_next_action_readback','support_ticket_external_delivery_readback'),'no_ticket_mutation',true,'no_workflow_dispatch',true,'no_approval_decision',true,'no_external_send',true,'no_external_write',true,'no_provider_call',true,'no_credential_payload_read',true,'no_spend_change',true,'no_deploy',true,'no_publish',true,'secrets_included',false),'TRUE','support_ticket_lifecycle|support_ticket_external_delivery|next_action_readback|external_delivery_readback|no_execution','supportTicketLifecycleNextActionReadback|supportTicketExternalDeliveryOrchestrationReadback|platformPluginRoutes|platform_orchestration_readback','TRUE','Completion readbacks for Support Ticket lifecycle and External Delivery. Read-only; no execution or secrets.'
WHERE NOT EXISTS (SELECT 1 FROM `execution_policies` WHERE `policy_group`='Orchestration Intelligence Governance' AND `policy_key`='support_ticket_orchestration_completion_readbacks_policy_v1');

INSERT INTO `execution_policies` (`policy_group`,`policy_key`,`policy_value`,`active`,`execution_scope`,`affects_layer`,`blocking`,`notes`)
SELECT 'Orchestration Intelligence Governance','support_ticket_external_delivery_orchestration_readback_policy_v1',JSON_OBJECT('rule','support_ticket_external_delivery_orchestration_readback','plugin_key','support_ticket_external_delivery_orchestrator','stage_count',7,'edge_count',6,'no_external_send',true,'no_external_write',true,'no_provider_call',true,'no_credential_payload_read',true,'secrets_included',false),'TRUE','support_ticket_external_delivery|orchestration_readback|external_delivery_readiness|no_execution','supportTicketExternalDeliveryOrchestrationReadback|platformOrchestrationReadback|platform_orchestration_stages|platform_orchestration_edges','TRUE','Read-only external delivery orchestration graph and readiness policy. No external send/write, provider call, credential payload read, or secrets.'
WHERE NOT EXISTS (SELECT 1 FROM `execution_policies` WHERE `policy_group`='Orchestration Intelligence Governance' AND `policy_key`='support_ticket_external_delivery_orchestration_readback_policy_v1');
