-- 952_sprint68_resource_graph_projection_apply_gate.sql
-- Purpose: seed dynamic apply authorization and dispatch certification for the
-- governed resource graph projection apply gate. This migration does not create
-- new graph tables, does not call providers, and does not store credential values.

INSERT INTO `runtime_dispatch_certification_registry` (
  `certification_key`,
  `surface_key`,
  `surface_family`,
  `tool_or_action_key`,
  `risk_class`,
  `certification_status`,
  `smoke_strategy`,
  `dispatch_allowed`,
  `apply_allowed`,
  `requires_resource_authority`,
  `requires_dry_run`,
  `requires_audit_evidence`,
  `requires_readback`,
  `last_evidence_ref`,
  `last_certified_at`,
  `notes`
)
VALUES (
  'resource_graph_projection_apply',
  'governed_resource_run',
  'resource_recipe_runtime',
  'governed_resource_run',
  'medium',
  'graph_projection_dry_run_smoke_passed_apply_gate_pending',
  'Positive apply smoke must first recompute graph_projection_dry_run, require exact typed confirmation, require capability envelope apply authorization, write candidate/advisory graph rows only, perform same-cycle readback, and prove no provider calls, no file-content read, no secrets, no runtime enforcement.',
  1,
  0,
  1,
  1,
  1,
  1,
  'governed_resource_run:graph_projection_dry_run:2026-06-11',
  CURRENT_TIMESTAMP,
  'Allows Dynamic Capability Resolution to issue approved envelopes for the guarded Resource Recipe graph projection apply gate only. It does not bypass typed confirmation, same-cycle dry-run hash, readback, or candidate/advisory-only graph write policy.'
)
ON DUPLICATE KEY UPDATE
  `surface_key` = VALUES(`surface_key`),
  `surface_family` = VALUES(`surface_family`),
  `tool_or_action_key` = VALUES(`tool_or_action_key`),
  `risk_class` = VALUES(`risk_class`),
  `certification_status` = IF(`certification_status` = 'resource_graph_projection_apply_smoke_passed', `certification_status`, VALUES(`certification_status`)),
  `smoke_strategy` = VALUES(`smoke_strategy`),
  `dispatch_allowed` = VALUES(`dispatch_allowed`),
  `apply_allowed` = IF(`certification_status` = 'resource_graph_projection_apply_smoke_passed', `apply_allowed`, VALUES(`apply_allowed`)),
  `requires_resource_authority` = VALUES(`requires_resource_authority`),
  `requires_dry_run` = VALUES(`requires_dry_run`),
  `requires_audit_evidence` = VALUES(`requires_audit_evidence`),
  `requires_readback` = VALUES(`requires_readback`),
  `last_evidence_ref` = IF(`certification_status` = 'resource_graph_projection_apply_smoke_passed', `last_evidence_ref`, VALUES(`last_evidence_ref`)),
  `last_certified_at` = IF(`certification_status` = 'resource_graph_projection_apply_smoke_passed', `last_certified_at`, VALUES(`last_certified_at`)),
  `notes` = IF(`certification_status` = 'resource_graph_projection_apply_smoke_passed', `notes`, VALUES(`notes`)),
  `updated_at` = CURRENT_TIMESTAMP;

INSERT INTO `capability_apply_authorization_policy_registry` (
  `policy_key`,
  `app_key`,
  `capability_key`,
  `operation_intent`,
  `runtime_surface`,
  `status`,
  `allow_external_write`,
  `allow_credential_binding`,
  `allow_no_credential_binding`,
  `requires_ready_for_dispatch`,
  `requires_dispatch_allowed`,
  `requires_zero_blocking_gaps`,
  `requires_audit_evidence`,
  `requires_readback`,
  `requires_typed_confirmation`,
  `requires_same_cycle_dry_run`,
  `allowed_source_tiers_json`,
  `policy_json`,
  `notes`
)
VALUES (
  'resource_graph_projection_apply_v1',
  'platform_orchestration',
  'resource_graph_projection_apply',
  'resource_graph_projection.apply_after_review',
  'governed_resource_run',
  'active',
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  JSON_ARRAY('platform_managed_fallback'),
  JSON_OBJECT(
    'external_write_allowed', false,
    'provider_call_allowed', false,
    'credential_payload_read_allowed', false,
    'spend_change_allowed', false,
    'graph_write_allowed', true,
    'graph_write_tables', JSON_ARRAY('platform_graph_nodes','platform_graph_edges','platform_graph_edge_evidence'),
    'graph_authority_status', 'candidate',
    'graph_runtime_role', 'advisory',
    'runtime_enforced', false,
    'requires_same_cycle_dry_run_hash', true,
    'requires_typed_confirmation', true,
    'requires_readback_in_runtime', true,
    'file_content_read_allowed', false,
    'secrets_included', false
  ),
  'Internal no-credential resource graph projection apply authorization policy. Runtime must still enforce exact typed confirmation, same-cycle graph projection hash, candidate/advisory rows only, same-cycle readback, no provider call, no file-content read, no secrets, and runtime_enforced=false.'
)
ON DUPLICATE KEY UPDATE
  `app_key` = VALUES(`app_key`),
  `capability_key` = VALUES(`capability_key`),
  `operation_intent` = VALUES(`operation_intent`),
  `runtime_surface` = VALUES(`runtime_surface`),
  `status` = VALUES(`status`),
  `allow_external_write` = VALUES(`allow_external_write`),
  `allow_credential_binding` = VALUES(`allow_credential_binding`),
  `allow_no_credential_binding` = VALUES(`allow_no_credential_binding`),
  `requires_ready_for_dispatch` = VALUES(`requires_ready_for_dispatch`),
  `requires_dispatch_allowed` = VALUES(`requires_dispatch_allowed`),
  `requires_zero_blocking_gaps` = VALUES(`requires_zero_blocking_gaps`),
  `requires_audit_evidence` = VALUES(`requires_audit_evidence`),
  `requires_readback` = VALUES(`requires_readback`),
  `requires_typed_confirmation` = VALUES(`requires_typed_confirmation`),
  `requires_same_cycle_dry_run` = VALUES(`requires_same_cycle_dry_run`),
  `allowed_source_tiers_json` = VALUES(`allowed_source_tiers_json`),
  `policy_json` = VALUES(`policy_json`),
  `notes` = VALUES(`notes`),
  `updated_at` = CURRENT_TIMESTAMP;
