import {google} from "googleapis";import {getPool} from "./db.js";
const WORKSPACE_SCOPES=["https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/documents","https://www.googleapis.com/auth/drive"];
const GOOGLE_SCOPES=[...WORKSPACE_SCOPES,"https://www.googleapis.com/auth/analytics.readonly","https://www.googleapis.com/auth/analytics","https://www.googleapis.com/auth/analytics.edit","https://www.googleapis.com/auth/analytics.manage.users","https://www.googleapis.com/auth/analytics.manage.users.readonly","https://www.googleapis.com/auth/analytics.provision","https://www.googleapis.com/auth/doubleclicksearch","https://www.googleapis.com/auth/webmasters","https://www.googleapis.com/auth/tagmanager.readonly","https://www.googleapis.com/auth/tagmanager.edit.containers","https://www.googleapis.com/auth/tagmanager.edit.containers.readonly","https://www.googleapis.com/auth/tagmanager.manage.accounts","https://www.googleapis.com/auth/tagmanager.manage.users","https://www.googleapis.com/auth/tagmanager.delete.containers","https://www.googleapis.com/auth/tagmanager.edit.containerversions","https://www.googleapis.com/auth/tagmanager.publish","https://www.googleapis.com/auth/adwords","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloud-platform.read-only","https://www.googleapis.com/auth/cloudplatformprojects","https://www.googleapis.com/auth/cloudplatformprojects.readonly"];
const cache=new Map();let fetching=false,warned=false,logged=false;
function jsonMaybe(v){if(!v)return null;if(typeof v==="object")return v;const s=String(v).trim();for(const x of [s,(()=>{try{return Buffer.from(s,"base64").toString("utf8")}catch{return ""}})()]){try{return JSON.parse(x)}catch{}}return null}
function parseSaJson(raw){return jsonMaybe(raw)}
function split(v){return String(v||"").split(/[,\s]+/).map(s=>s.trim()).filter(Boolean)}
function ref(raw=""){const out={mode:"",value:"",params:{}};const parts=String(raw||"").split(";").map(s=>s.trim()).filter(Boolean);if(!parts.length)return out;const i=parts[0].indexOf(":");if(i>=0){out.mode=parts[0].slice(0,i).trim();out.value=parts[0].slice(i+1).trim()}else out.mode=parts[0];for(const p of parts.slice(1)){const j=p.indexOf("=");if(j>0)out.params[p.slice(0,j).trim()]=p.slice(j+1).trim()}return out}
function emailKey(e=""){return String(e).trim().toUpperCase().replace(/[^A-Z0-9]/g,"_").replace(/_+/g,"_").replace(/^_+|_+$/g,"")}
function envCredForEmail(e){const k=emailKey(e);if(!k)return null;const rt=process.env[`GOOGLE_REFRESH_TOKEN_${k}`];if(!rt)return null;return{refresh_token:rt,client_id:process.env[`GOOGLE_CLIENT_ID_${k}`]||process.env.GOOGLE_CLIENT_ID,client_secret:process.env[`GOOGLE_CLIENT_SECRET_${k}`]||process.env.GOOGLE_CLIENT_SECRET,source:`env_member:${String(e).toLowerCase()}`}}
function appKeys(action={},r={}){return [r.params.app_key,action.action_key,action.module_binding,action.connector_family,"google_cloud","google","gcloud_api"].map(x=>String(x||"").trim()).filter(Boolean)}
function credFromRow(row){const p=jsonMaybe(row?.encrypted_credentials);if(!p)return null;const rt=p.refresh_token||p.refreshToken||p.credentials?.refresh_token||p.oauth?.refresh_token;if(!rt)return null;return{refresh_token:rt,client_id:p.client_id||p.clientId||p.credentials?.client_id||process.env.GOOGLE_CLIENT_ID,client_secret:p.client_secret||p.clientSecret||p.credentials?.client_secret||process.env.GOOGLE_CLIENT_SECRET,source:`user_app_connections:${row.connection_id||row.id}`}}
function hasScopes(granted,required){const g=new Set(split(granted));return !required.length||!g.size||required.every(s=>g.has(s))}
async function memberConnection(action,r){const keys=appKeys(action,r),ph=keys.map(()=>"?").join(","),req=split(r.params.scopes||action.required_oauth_scopes||"");let sql="",params=[];if(r.mode==="member_email"){sql=`SELECT uac.*,u.email member_email FROM user_app_connections uac JOIN users u ON CAST(u.user_id AS CHAR)=CAST(uac.user_id AS CHAR) WHERE LOWER(u.email)=LOWER(?) AND uac.auth_type='oauth2' AND uac.status='active' AND uac.app_key IN (${ph}) ORDER BY uac.is_primary DESC,COALESCE(uac.last_used_at,uac.connected_at) DESC LIMIT 10`;params=[r.value,...keys]}else if(r.mode==="member_user_id"){sql=`SELECT uac.*,u.email member_email FROM user_app_connections uac LEFT JOIN users u ON CAST(u.user_id AS CHAR)=CAST(uac.user_id AS CHAR) WHERE CAST(uac.user_id AS CHAR)=CAST(? AS CHAR) AND uac.auth_type='oauth2' AND uac.status='active' AND uac.app_key IN (${ph}) ORDER BY uac.is_primary DESC,COALESCE(uac.last_used_at,uac.connected_at) DESC LIMIT 10`;params=[r.value,...keys]}else if(r.mode==="tenant_primary"){sql=`SELECT uac.*,u.email member_email FROM user_app_connections uac LEFT JOIN users u ON CAST(u.user_id AS CHAR)=CAST(uac.user_id AS CHAR) WHERE uac.tenant_id=? AND uac.app_key=? AND uac.auth_type='oauth2' AND uac.status='active' ORDER BY uac.is_primary DESC,COALESCE(uac.last_used_at,uac.connected_at) DESC LIMIT 10`;params=[action.tenant_id||r.params.tenant_id||process.env.DEFAULT_TENANT_ID||"",r.value||r.params.app_key||"google"]}else return null;const [rows]=await getPool().query(sql,params);for(const row of rows||[]){if(!hasScopes(row.scopes_granted,req))continue;const c=credFromRow(row);if(c)return{row,credentials:c}}return null}
async function fromRefresh(c){if(!c?.refresh_token||!c?.client_id||!c?.client_secret){const e=new Error("Missing refresh token OAuth client material.");e.code="oauth_credential_incomplete";e.status=403;throw e}const o=new google.auth.OAuth2(c.client_id,c.client_secret);o.setCredentials({refresh_token:c.refresh_token});const resp=await o.getAccessToken();const t=typeof resp==="string"?resp:resp?.token;if(!t){const e=new Error("Google OAuth refresh returned no access token.");e.code="oauth_token_refresh_failed";e.status=403;throw e}return t}
export function getGoogleAuthCredentialSourcesForEnv(env=process.env){const sources=[],mode=String(env.GOOGLE_AUTH_MODE||"").trim().toLowerCase();if(mode==="refresh_token"&&env.GOOGLE_REFRESH_TOKEN)sources.push("refresh_token");if(env.GOOGLE_APPLICATION_CREDENTIALS||parseSaJson(env.GOOGLE_SA_JSON))sources.push("explicit_service_account");else sources.push("managed_service_account_adc");if(env.GOOGLE_REFRESH_TOKEN&&!sources.includes("refresh_token"))sources.push("refresh_token");return sources}
async function fetchToken(options={}){const action=options.action||{},r=ref(options.oauth_config_ref||action.oauth_config_ref||""),key=r.mode?`ref:${action.action_key||""}:${action.oauth_config_ref||""}`:"global";const hit=cache.get(key);if(hit?.token&&hit.expiresAt>Date.now()+60000)return hit.token;if(r.mode==="member_email"){const c=envCredForEmail(r.value);if(c){const token=await fromRefresh(c);cache.set(key,{token,expiresAt:Date.now()+55*60000});console.log(`[googleAuth] Access token obtained via ${c.source}.`);return token}}if(["member_email","member_user_id","tenant_primary"].includes(r.mode)){const m=await memberConnection(action,r);if(!m){const e=new Error(`No active Google OAuth connection found for ${action.oauth_config_ref||r.mode}.`);e.code="google_oauth_connection_not_found";e.status=403;throw e}const token=await fromRefresh(m.credentials);cache.set(key,{token,expiresAt:Date.now()+55*60000});console.log(`[googleAuth] Access token obtained via member OAuth for ${m.row.member_email||m.row.account_label||"unknown"}.`);return token}if(fetching)return cache.get("global")?.token||"";fetching=true;try{const sa=parseSaJson(process.env.GOOGLE_SA_JSON),credFile=process.env.GOOGLE_APPLICATION_CREDENTIALS,rt=process.env.GOOGLE_REFRESH_TOKEN,attempts=[];for(const source of getGoogleAuthCredentialSourcesForEnv(process.env)){if(source==="explicit_service_account"){attempts.push({source:"explicit service account",run:async()=>{const opts={scopes:GOOGLE_SCOPES};if(sa)opts.credentials=sa;else opts.keyFilename=credFile;const a=new google.auth.GoogleAuth(opts),c=await a.getClient();return c.getAccessToken()}})}if(source==="managed_service_account_adc"){attempts.push({source:"managed service account ADC",run:async()=>{const a=new google.auth.GoogleAuth({scopes:WORKSPACE_SCOPES}),c=await a.getClient();return c.getAccessToken()}})}if(source==="refresh_token"){attempts.push({source:"refresh token",run:async()=>fromRefresh({refresh_token:rt,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET})})}}let last=null;for(const a of attempts){try{const resp=await a.run(),token=typeof resp==="string"?resp:resp?.token;if(token){cache.set("global",{token,expiresAt:Date.now()+55*60000});if(!logged){logged=true;console.log(`[googleAuth] Access token obtained via ${a.source}.`)}return token}}catch(e){last=e}}if(!warned){warned=true;console.warn("[googleAuth] Could not obtain a Google access token."+ (last?.message?` Last error: ${last.message}`:""))}return ""}finally{fetching=false}}
export function getGoogleAccessTokenSync(options={}){const action=options.action||{},r=ref(options.oauth_config_ref||action.oauth_config_ref||""),key=r.mode?`ref:${action.action_key||""}:${action.oauth_config_ref||""}`:"global",hit=cache.get(key);if(hit?.token&&hit.expiresAt>Date.now()+60000)return hit.token;fetchToken(options).catch(()=>{});return hit?.token||""}
export async function getGoogleAccessToken(options={}){const action=options.action||{},r=ref(options.oauth_config_ref||action.oauth_config_ref||""),key=r.mode?`ref:${action.action_key||""}:${action.oauth_config_ref||""}`:"global",hit=cache.get(key);if(hit?.token&&hit.expiresAt>Date.now()+60000)return hit.token;return fetchToken(options)}
if(String(process.env.GOOGLE_AUTH_DISABLE_PREWARM||"").trim().toLowerCase()!=="true"){fetchToken().catch(()=>{});setInterval(()=>fetchToken().catch(()=>{}),50*60000).unref()}
