import { isBackendApiKeyEnabled } from "./runtimeGuards.js";
import { randomUUID }             from "node:crypto";
import { getPool }                from "./db.js";
import { runDevAgentSweep }       from "./devAgentRunner.js";

// Ensure the token is strictly via URL (?token=...)
export function requireMcpToken(req, res, next) {
  // Reject Authorization header entirely for MCP
  if (req.header("Authorization")) {
    return res.status(400).json({
      ok: false,
      error: { code: "invalid_auth_method", message: "MCP contract strictly requires token_in_url. Authorization headers are rejected." }
    });
  }

  if (!isBackendApiKeyEnabled(process.env)) return next();
  const expected = process.env.BACKEND_API_KEY;
  const token = req.query.token;

  if (token !== expected) {
    return res.status(401).json({
      ok: false,
      error: { code: "unauthorized", message: "Invalid MCP token." }
    });
  }
  next();
}

// Ensure transport uses valid Accept types
export function requireMcpAcceptHeader(req, res, next) {
  const accept = req.header("Accept") || "";
  if (!accept.includes("application/json") && !accept.includes("text/event-stream")) {
    return res.status(406).json({
      ok: false,
      error: { code: "not_acceptable", message: "MCP contract requires Accept: application/json or text/event-stream" }
    });
  }
  next();
}

export async function mcpInitialize(req, res) {
  return res.json({
    protocolVersion: "2024-11-05",
    capabilities: {
      tools: {
        listChanged: true
      }
    },
    serverInfo: {
      name: "multi-business-growth-intelligence-os",
      version: "1.0.0"
    }
  });
}

export async function mcpToolsList(req, res) {
  // Uses cached layer to prevent heavy registry polling on each list request
  return res.json({
    tools: [
      {
        name: "execute_action",
        description: "Executes a governed registry action.",
        inputSchema: {
          type: "object",
          properties: {
            parent_action_key: { type: "string" },
            endpoint_key: { type: "string" },
            brand: { type: "string" },
            target_key: { type: "string" }
          },
          required: ["parent_action_key", "endpoint_key"]
        }
      }
    ]
  });
}

export async function mcpToolsCall(req, res) {
  const { name, arguments: args } = req.body;
  if (name !== "execute_action") {
    return res.status(400).json({ error: `Unknown tool: ${name}` });
  }

  // To truly execute, this should pipe into the main execution route
  // For now we map it conceptually to be consumed by the execution endpoint
  return res.json({
    content: [
      {
        type: "text",
        text: JSON.stringify({ status: "MCP execution received.", args })
      }
    ]
  });
}

// ── Full-capability MCP handler factory ──────────────────────────────────────
// Returns mcpInitialize, mcpToolsList, mcpToolsCall with live dispatchers.
// Used by mcpRoutes.js instead of the static stubs above.

const TOOL_DEFINITIONS = [
  {
    name: "dev_agent_run",
    description: "Trigger the developer agent to summarise recent sessions and extract platform improvement proposals. Returns run_id immediately; sweep runs in background.",
    inputSchema: { type: "object", properties: {}, required: [] },
  },
  {
    name: "dev_agent_list_proposals",
    description: "List platform improvement proposals generated by the developer agent.",
    inputSchema: {
      type: "object",
      properties: {
        status:    { type: "string", enum: ["pending","confirmed","dismissed","in_discussion","implemented"] },
        scope:     { type: "string", enum: ["code","db","workflow","integration","agent","ux"] },
        priority:  { type: "string", enum: ["low","medium","high","critical"] },
        tenant_id: { type: "string" },
        limit:     { type: "integer", default: 20 },
      },
      required: [],
    },
  },
  {
    name: "dev_agent_get_proposal",
    description: "Get full details of a single development proposal, including rationale and evidence sessions.",
    inputSchema: {
      type: "object",
      properties: { proposal_id: { type: "string" } },
      required: ["proposal_id"],
    },
  },
  {
    name: "dev_agent_confirm_proposal",
    description: "Confirm a pending proposal so it is queued for implementation.",
    inputSchema: {
      type: "object",
      properties: {
        proposal_id:          { type: "string" },
        confirmed_by:         { type: "string", description: "user_id or identifier of the confirming user" },
        implementation_notes: { type: "string" },
      },
      required: ["proposal_id"],
    },
  },
  {
    name: "dev_agent_dismiss_proposal",
    description: "Dismiss a pending proposal as not needed or out of scope.",
    inputSchema: {
      type: "object",
      properties: {
        proposal_id:  { type: "string" },
        dismissed_by: { type: "string" },
      },
      required: ["proposal_id"],
    },
  },
  {
    name: "dev_agent_list_session_summaries",
    description: "List LLM-generated summaries of completed user sessions, with feature requests and blockers extracted.",
    inputSchema: {
      type: "object",
      properties: {
        tenant_id: { type: "string" },
        analyzed:  { type: "boolean", description: "Filter by whether summary has been included in a proposal sweep" },
        limit:     { type: "integer", default: 20 },
      },
      required: [],
    },
  },
  {
    name: "list_app_connections",
    description: "List active app connections for a tenant (Google Drive, Slack, GitHub, Make.com, n8n, etc.).",
    inputSchema: {
      type: "object",
      properties: {
        tenant_id: { type: "string" },
        app_key:   { type: "string", description: "Filter to a specific app (e.g. slack, github)" },
      },
      required: ["tenant_id"],
    },
  },
  {
    name: "execute_action",
    description: "Execute a governed registry action via the platform execution engine.",
    inputSchema: {
      type: "object",
      properties: {
        parent_action_key: { type: "string" },
        endpoint_key:      { type: "string" },
        brand:             { type: "string" },
        target_key:        { type: "string" },
      },
      required: ["parent_action_key", "endpoint_key"],
    },
  },
];

async function dispatchTool(name, args, deps) {
  const callModel = deps?.getCallModelForClass
    ? deps.getCallModelForClass("standard")
    : deps?.callModel;

  switch (name) {

    case "dev_agent_run": {
      if (!callModel) return { error: "callModel not configured on this server instance" };
      // Fire-and-forget sweep, return run_id
      const result = await runDevAgentSweep({ ...deps, callModel });
      return result;
    }

    case "dev_agent_list_proposals": {
      const { status, scope, priority, tenant_id, limit = 20 } = args;
      const where = ["1=1"], params = [];
      if (status)    { where.push("status = ?");    params.push(status); }
      if (scope)     { where.push("scope = ?");     params.push(scope); }
      if (priority)  { where.push("priority = ?");  params.push(priority); }
      if (tenant_id) { where.push("tenant_id = ?"); params.push(tenant_id); }

      const [rows] = await getPool().query(
        `SELECT proposal_id, tenant_id, scope, layer, title, description,
                rationale, priority, status, evidence_session_ids,
                confirmed_at, dismissed_at, created_at, updated_at
         FROM \`dev_agent_proposals\`
         WHERE ${where.join(" AND ")}
         ORDER BY
           FIELD(priority,'critical','high','medium','low'),
           FIELD(status,'pending','in_discussion','confirmed','implemented','dismissed'),
           created_at DESC
         LIMIT ?`,
        [...params, Math.min(parseInt(limit) || 20, 100)]
      );
      return { proposals: rows, count: rows.length };
    }

    case "dev_agent_get_proposal": {
      const { proposal_id } = args;
      if (!proposal_id) return { error: "proposal_id required" };
      const [rows] = await getPool().query(
        "SELECT * FROM `dev_agent_proposals` WHERE proposal_id = ? LIMIT 1",
        [proposal_id]
      );
      return rows[0] ? { proposal: rows[0] } : { error: "proposal_not_found" };
    }

    case "dev_agent_confirm_proposal": {
      const { proposal_id, confirmed_by, implementation_notes } = args;
      if (!proposal_id) return { error: "proposal_id required" };
      const [result] = await getPool().query(
        `UPDATE \`dev_agent_proposals\`
           SET status = 'confirmed', confirmed_by = ?, confirmed_at = NOW(),
               implementation_notes = COALESCE(?, implementation_notes)
         WHERE proposal_id = ? AND status IN ('pending','in_discussion')`,
        [confirmed_by || null, implementation_notes || null, proposal_id]
      );
      if (!result.affectedRows) return { error: "proposal_not_found_or_already_actioned" };
      return { ok: true, proposal_id, status: "confirmed" };
    }

    case "dev_agent_dismiss_proposal": {
      const { proposal_id, dismissed_by } = args;
      if (!proposal_id) return { error: "proposal_id required" };
      const [result] = await getPool().query(
        `UPDATE \`dev_agent_proposals\`
           SET status = 'dismissed', dismissed_by = ?, dismissed_at = NOW()
         WHERE proposal_id = ? AND status IN ('pending','in_discussion')`,
        [dismissed_by || null, proposal_id]
      );
      if (!result.affectedRows) return { error: "proposal_not_found_or_already_actioned" };
      return { ok: true, proposal_id, status: "dismissed" };
    }

    case "dev_agent_list_session_summaries": {
      const { tenant_id, analyzed, limit = 20 } = args;
      const where = ["1=1"], params = [];
      if (tenant_id)          { where.push("tenant_id = ?"); params.push(tenant_id); }
      if (analyzed !== undefined) { where.push("analyzed = ?"); params.push(analyzed ? 1 : 0); }
      const [rows] = await getPool().query(
        `SELECT summary_id, session_id, tenant_id, workspace_key, summary_text,
                tasks_completed, blockers, feature_requests, integration_needs,
                complexity, turn_count, analyzed, created_at
         FROM \`session_summaries\`
         WHERE ${where.join(" AND ")}
         ORDER BY created_at DESC LIMIT ?`,
        [...params, Math.min(parseInt(limit) || 20, 100)]
      );
      return { summaries: rows, count: rows.length };
    }

    case "list_app_connections": {
      const { tenant_id, app_key } = args;
      if (!tenant_id) return { error: "tenant_id required" };
      const where = ["uac.tenant_id = ?", "uac.status = 'active'"];
      const params = [tenant_id];
      if (app_key) { where.push("uac.app_key = ?"); params.push(app_key); }
      const [rows] = await getPool().query(
        `SELECT uac.connection_id, uac.app_key, ai.display_name AS app_name,
                uac.account_label, uac.is_primary, uac.last_used_at, uac.created_at
         FROM \`user_app_connections\` uac
         JOIN \`app_integrations\` ai ON ai.app_key = uac.app_key
         WHERE ${where.join(" AND ")}
         ORDER BY uac.app_key, uac.is_primary DESC`,
        params
      ).catch(() => [[]]);
      return { connections: rows, count: rows.length };
    }

    case "execute_action":
      return { status: "execute_action routed to governed execution engine", args };

    default:
      return { error: `Unknown tool: ${name}` };
  }
}

export function buildMcpHandlers(deps = {}) {
  return {
    mcpInitialize: async (_req, res) => res.json({
      protocolVersion: "2024-11-05",
      capabilities: { tools: { listChanged: true } },
      serverInfo: { name: "multi-business-growth-intelligence-os", version: "1.0.0" },
    }),

    mcpToolsList: async (_req, res) => res.json({ tools: TOOL_DEFINITIONS }),

    mcpToolsCall: async (req, res) => {
      const { name, arguments: args = {} } = req.body || {};
      if (!name) return res.status(400).json({ error: "name required" });
      try {
        const result = await dispatchTool(name, args, deps);
        res.json({ content: [{ type: "text", text: JSON.stringify(result) }] });
      } catch (err) {
        res.status(500).json({
          content: [{ type: "text", text: JSON.stringify({ error: err.message }) }],
        });
      }
    },
  };
}
