-- Growth OS Database Schema
-- Migrated from Google Sheets → MySQL (Hostinger srv1343)
-- Generated: 2026-05-04

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ── 1. Brand Registry ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `brands` (
  `id`                            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_name`                    VARCHAR(255),
  `normalized_brand_name`         VARCHAR(255),
  `brand_domain`                  VARCHAR(255),
  `target_key`                    VARCHAR(255),
  `site_aliases_json`             TEXT,
  `base_url`                      VARCHAR(500),
  `transport_action_key`          VARCHAR(255),
  `auth_type`                     VARCHAR(100),
  `credential_resolution`         VARCHAR(255),
  `username`                      VARCHAR(255),
  `application_password`          TEXT,
  `default_headers_json`          TEXT,
  `write_allowed`                 VARCHAR(20),
  `destructive_allowed`           VARCHAR(20),
  `transport_enabled`             VARCHAR(20),
  `target_resolution_mode`        VARCHAR(100),
  `hosting_provider`              VARCHAR(100),
  `hosting_account_key`           VARCHAR(255),
  `hostinger_api_target_key`      VARCHAR(255),
  `server_environment_label`      VARCHAR(255),
  `server_environment_type`       VARCHAR(100),
  `server_region_or_datacenter`   VARCHAR(255),
  `server_primary_domain`         VARCHAR(255),
  `server_panel_reference`        VARCHAR(255),
  `hosting_account_registry_ref`  VARCHAR(255),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_target_key` (`target_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 2. Brand Core Registry ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `brand_core` (
  `id`                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_key`           VARCHAR(255),
  `asset_key`           VARCHAR(255),
  `doc_key`             VARCHAR(255),
  `doc_id`              VARCHAR(255),
  `file_id`             VARCHAR(255),
  `google_doc_id`       VARCHAR(255),
  `brand_core_docs_json` TEXT,
  `status`              VARCHAR(100),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_brand_key` (`brand_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 3. Actions Registry ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `actions` (
  `id`                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `action_key`                  VARCHAR(255),
  `action_id`                   VARCHAR(255),
  `action_title`                VARCHAR(255),
  `status`                      VARCHAR(100),
  `module_binding`              VARCHAR(255),
  `connector_family`            VARCHAR(255),
  `action_class`                VARCHAR(100),
  `action_scope`                VARCHAR(100),
  `endpoint_group`              VARCHAR(255),
  `route_target`                VARCHAR(255),
  `execution_layer`             VARCHAR(255),
  `logging_target`              VARCHAR(255),
  `inventory_role`              VARCHAR(255),
  `admin_only`                  VARCHAR(20),
  `client_allowed`              VARCHAR(20),
  `team_allowed`                VARCHAR(20),
  `review_required`             VARCHAR(20),
  `provider_agnostic`           VARCHAR(20),
  `request_envelope_required`   VARCHAR(20),
  `structured_api_supported`    VARCHAR(20),
  `writeback_scope`             VARCHAR(100),
  `api_key_mode`                VARCHAR(100),
  `api_key_param_name`          VARCHAR(255),
  `api_key_header_name`         VARCHAR(255),
  `api_key_value`               TEXT,
  `api_key_storage_mode`        VARCHAR(100),
  `secret_store_ref`            VARCHAR(255),
  `openai_schema_file_id`       VARCHAR(255),
  `openai_schema_file_name`     VARCHAR(255),
  `openai_schema_ref`            VARCHAR(255),
  `openai_schema_storage_surface` VARCHAR(100),
  `oauth_config_file_id`        VARCHAR(255),
  `oauth_config_file_name`      VARCHAR(255),
  `oauth_config_ref`            VARCHAR(255),
  `oauth_client_id_ref`         VARCHAR(255),
  `oauth_client_secret_ref`     VARCHAR(255),
  `oauth_binding_status`        VARCHAR(100),
  `runtime_binding_profile`     LONGTEXT,
  `runtime_capability_class`    VARCHAR(255),
  `runtime_callable`            VARCHAR(255),
  `primary_executor`            VARCHAR(255),
  `schema_json`                 LONGTEXT,
  `import_job_id`               VARCHAR(36),
  `schema_imported_at`          DATETIME,
  `notes`                       TEXT,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_action_key` (`action_key`),
  KEY `idx_action_id` (`action_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 4. API Actions Endpoint Registry ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `endpoints` (
  `id`                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endpoint_id`                 VARCHAR(255),
  `parent_action_key`           VARCHAR(255),
  `endpoint_key`                VARCHAR(255),
  `endpoint_operation`          VARCHAR(255),
  `provider_domain`             VARCHAR(255),
  `method`                      VARCHAR(20),
  `endpoint_path_or_function`   TEXT,
  `route_target`                VARCHAR(255),
  `openai_action_name`          VARCHAR(255),
  `child_openai_schema_file_id` VARCHAR(255),
  `module_binding`              VARCHAR(255),
  `connector_family`            VARCHAR(255),
  `status`                      VARCHAR(100),
  `spec_validation_status`      VARCHAR(100),
  `auth_validation_status`      VARCHAR(100),
  `privacy_validation_status`   VARCHAR(100),
  `execution_readiness`         VARCHAR(100),
  `endpoint_role`               VARCHAR(100),
  `execution_mode`              VARCHAR(100),
  `transport_required`          VARCHAR(20),
  `fallback_allowed`            VARCHAR(20),
  `fallback_match_basis`        VARCHAR(255),
  `fallback_provider_domain`    VARCHAR(255),
  `fallback_connector_family`   VARCHAR(255),
  `fallback_action_name`        VARCHAR(255),
  `fallback_route_target`       VARCHAR(255),
  `fallback_notes`              TEXT,
  `inventory_role`              VARCHAR(100),
  `inventory_source`            VARCHAR(255),
  `notes`                       TEXT,
  `brand_resolution_source`     VARCHAR(255),
  `transport_action_key`        VARCHAR(255),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_endpoint_key` (`endpoint_key`),
  KEY `idx_parent_action_key` (`parent_action_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 5. Platform Endpoint Tool Exports ──────────────────────────────────────────
-- Baseline prerequisite for migration 062 and platform export runtime reads.
-- Export rows contain contract metadata only; no secret payloads are stored here.
CREATE TABLE IF NOT EXISTS `platform_endpoint_tool_exports` (
  `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `export_key`            VARCHAR(255) NOT NULL,
  `parent_action_key`     VARCHAR(255) NOT NULL,
  `endpoint_key`          VARCHAR(255) NOT NULL,
  `tool_name`             VARCHAR(255) NOT NULL,
  `scope_class`           VARCHAR(32) NOT NULL DEFAULT 'admin',
  `tenant_id`             VARCHAR(36) NULL,
  `status`                VARCHAR(32) NOT NULL DEFAULT 'active',
  `source_endpoint_id`    BIGINT UNSIGNED NULL,
  `import_policy_json`    JSON NULL,
  `input_schema_json`     JSON NULL,
  `output_schema_json`    JSON NULL,
  `auth_policy_json`      JSON NULL,
  `execution_policy_json` JSON NULL,
  `notes`                 TEXT NULL,
  `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_platform_endpoint_tool_export_key` (`export_key`),
  KEY `idx_platform_endpoint_tool_export_action_endpoint` (`parent_action_key`, `endpoint_key`),
  KEY `idx_platform_endpoint_tool_export_tool_status` (`tool_name`, `status`),
  KEY `idx_platform_endpoint_tool_export_source_status` (`source_endpoint_id`, `status`),
  KEY `idx_platform_endpoint_tool_export_tenant_scope` (`tenant_id`, `scope_class`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 6. Execution Policy Registry ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `execution_policies` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `policy_group`    VARCHAR(255),
  `policy_key`      VARCHAR(255),
  `policy_value`    TEXT,
  `active`          VARCHAR(20),
  `execution_scope` VARCHAR(255),
  `affects_layer`   VARCHAR(255),
  `blocking`        VARCHAR(20),
  `notes`           TEXT,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_policy_group_key` (`policy_group`, `policy_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 6. Hosting Account Registry ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `hosting_accounts` (
  `id`                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hosting_account_key`         VARCHAR(255),
  `hosting_provider`            VARCHAR(100),
  `account_identifier`          VARCHAR(255),
  `api_auth_mode`               VARCHAR(100),
  `api_key_reference`           TEXT,
  `api_key_storage_mode`        VARCHAR(100),
  `plan_label`                  VARCHAR(255),
  `plan_type`                   VARCHAR(100),
  `account_scope_notes`         TEXT,
  `status`                      VARCHAR(100),
  `last_reviewed_at`            VARCHAR(100),
  `brand_sites_json`            TEXT,
  `resolver_target_keys_json`   TEXT,
  `auth_validation_status`      VARCHAR(100),
  `endpoint_binding_status`     VARCHAR(100),
  `resolver_execution_ready`    VARCHAR(20),
  `last_runtime_check_at`       VARCHAR(100),
  `ssh_available`               VARCHAR(20),
  `wp_cli_available`            VARCHAR(20),
  `shared_access_enabled`       VARCHAR(20),
  `account_mode`                VARCHAR(100),
  `ssh_host`                    VARCHAR(255),
  `ssh_port`                    VARCHAR(20),
  `ssh_username`                VARCHAR(255),
  `ssh_auth_mode`               VARCHAR(100),
  `ssh_credential_reference`    TEXT,
  `ssh_runtime_notes`           TEXT,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hosting_account_key` (`hosting_account_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 7. Site Runtime Inventory Registry ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `site_runtime_inventory` (
  `id`                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `target_key`                  VARCHAR(255),
  `brand_name`                  VARCHAR(255),
  `brand_domain`                VARCHAR(255),
  `base_url`                    VARCHAR(500),
  `site_type`                   VARCHAR(100),
  `supported_cpts`              TEXT,
  `supported_taxonomies`        TEXT,
  `generated_endpoint_support`  TEXT,
  `runtime_validation_status`   VARCHAR(100),
  `last_runtime_validated_at`   VARCHAR(100),
  `active_status`               VARCHAR(20),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_target_key` (`target_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 8. Site Settings Inventory Registry ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS `site_settings_inventory` (
  `id`                            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `target_key`                    VARCHAR(255),
  `brand_name`                    VARCHAR(255),
  `brand_domain`                  VARCHAR(255),
  `base_url`                      VARCHAR(500),
  `site_type`                     VARCHAR(100),
  `permalink_structure`           VARCHAR(255),
  `timezone_string`               VARCHAR(100),
  `site_language`                 VARCHAR(50),
  `active_theme`                  VARCHAR(255),
  `settings_validation_status`    VARCHAR(100),
  `last_settings_validated_at`    VARCHAR(100),
  `active_status`                 VARCHAR(20),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_target_key` (`target_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 9. Plugin Inventory Registry ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `plugins` (
  `id`                        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `target_key`                VARCHAR(255),
  `brand_name`                VARCHAR(255),
  `brand_domain`              VARCHAR(255),
  `base_url`                  VARCHAR(500),
  `site_type`                 VARCHAR(100),
  `active_plugins`            TEXT,
  `plugin_versions_json`      TEXT,
  `plugin_owned_tables`       TEXT,
  `plugin_owned_entities`     TEXT,
  `plugin_validation_status`  VARCHAR(100),
  `last_plugin_validated_at`  VARCHAR(100),
  `active_status`             VARCHAR(20),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_target_key` (`target_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 10. Task Routes ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `task_routes` (
  `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_key`              VARCHAR(255),
  `trigger_terms`         TEXT,
  `route_modules`         TEXT,
  `execution_layer`       VARCHAR(255),
  `priority`              VARCHAR(100),
  `enabled`               VARCHAR(20),
  `output_focus`          TEXT,
  `notes`                 TEXT,
  `entry_sources`         TEXT,
  `linked_starter_titles` TEXT,
  `active_starter_count`  VARCHAR(50),
  `route_key_match_status` VARCHAR(100),
  `row_id`                VARCHAR(255),
  `route_id`              VARCHAR(255),
  `active`                VARCHAR(20),
  `intent_key`            VARCHAR(255),
  `brand_scope`           VARCHAR(255),
  `request_type`          VARCHAR(100),
  `route_mode`            VARCHAR(100),
  `target_module`         VARCHAR(255),
  `workflow_key`          VARCHAR(255),
  `lifecycle_mode`        VARCHAR(100),
  `memory_required`       VARCHAR(20),
  `logging_required`      VARCHAR(20),
  `review_required`       VARCHAR(20),
  `allowed_states`        TEXT,
  `degraded_action`       VARCHAR(255),
  `blocked_action`        VARCHAR(255),
  `match_rule`            TEXT,
  `route_source`          VARCHAR(255),
  `last_validated_at`     VARCHAR(100),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_route_id` (`route_id`),
  KEY `idx_workflow_key` (`workflow_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 11. Workflow Registry ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `workflows` (
  `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `workflow_id`           VARCHAR(255),
  `workflow_name`         VARCHAR(255),
  `module_mode`           VARCHAR(100),
  `trigger_source`        VARCHAR(255),
  `input_type`            VARCHAR(100),
  `primary_objective`     TEXT,
  `mapped_engines`        TEXT,
  `engine_order`          TEXT,
  `workflow_type`         VARCHAR(100),
  `primary_output`        TEXT,
  `input_detection_rules` TEXT,
  `output_template`       TEXT,
  `priority`              VARCHAR(100),
  `route_key`             VARCHAR(255),
  `execution_mode`        VARCHAR(100),
  `user_facing`           VARCHAR(20),
  `parent_layer`          VARCHAR(255),
  `status`                VARCHAR(100),
  `linked_workflows`      TEXT,
  `linked_engines`        TEXT,
  `notes`                 TEXT,
  `entry_priority_weight` VARCHAR(50),
  `dependency_type`       VARCHAR(100),
  `output_artifact_type`  VARCHAR(100),
  `workflow_key`          VARCHAR(255),
  `active`                VARCHAR(20),
  `target_module`         VARCHAR(255),
  `execution_class`       VARCHAR(255),
  `lifecycle_mode`        VARCHAR(100),
  `route_compatibility`   TEXT,
  `memory_required`       VARCHAR(20),
  `logging_required`      VARCHAR(20),
  `review_required`       VARCHAR(20),
  `allowed_states`        TEXT,
  `degraded_action`       VARCHAR(255),
  `blocked_action`        VARCHAR(255),
  `registry_source`       VARCHAR(255),
  `last_validated_at`     VARCHAR(100),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_workflow_key` (`workflow_key`),
  KEY `idx_route_key` (`route_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 12. Registry Surfaces Catalog ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `registry_surfaces_catalog` (
  `id`                                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `surface_id`                            VARCHAR(255),
  `surface_name`                          VARCHAR(255),
  `worksheet_name`                        VARCHAR(255),
  `worksheet_gid`                         VARCHAR(100),
  `active_status`                         VARCHAR(20),
  `authority_status`                      VARCHAR(100),
  `required_for_execution`                VARCHAR(20),
  `schema_ref`                            VARCHAR(255),
  `schema_version`                        VARCHAR(50),
  `header_signature`                      TEXT,
  `expected_column_count`                 INT,
  `binding_mode`                          VARCHAR(100),
  `sheet_role`                            VARCHAR(100),
  `audit_mode`                            VARCHAR(100),
  `legacy_surface_containment_required`   VARCHAR(20),
  `repair_candidate_types`                TEXT,
  `repair_priority`                       VARCHAR(100),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_surface_id` (`surface_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 13. Platform Contract Surfaces Registry ───────────────────────────────────
-- Baseline prerequisite for migration 041 and knowledge-surface runtime reads.
-- business_type_scope is intentionally added by migration 041 after this baseline.
CREATE TABLE IF NOT EXISTS `platform_contract_surfaces` (
  `id`                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `surface_id`                 VARCHAR(255) NOT NULL,
  `surface_name`               VARCHAR(255),
  `surface_type`               VARCHAR(100),
  `file_id`                    VARCHAR(255),
  `folder_id`                  VARCHAR(255),
  `surface_scope`              VARCHAR(100),
  `active_status`              VARCHAR(20),
  `authority_status`           VARCHAR(100),
  `runtime_consumption_status` VARCHAR(100),
  `current_runtime_adapter`    VARCHAR(255),
  `created_at`                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_platform_contract_surface_id` (`surface_id`),
  KEY `idx_platform_contract_surface_runtime` (`runtime_consumption_status`, `active_status`),
  KEY `idx_platform_contract_surface_type` (`surface_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 14. Validation & Repair Registry ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `validation_repair` (
  `id`                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `validation_id`       VARCHAR(255),
  `entity_key`          VARCHAR(255),
  `surface_id`          VARCHAR(255),
  `validation_target`   VARCHAR(255),
  `target_surface_id`   VARCHAR(255),
  `validation_type`     VARCHAR(100),
  `validation_status`    VARCHAR(100),
  `repair_action`       VARCHAR(255),
  `repair_status`       VARCHAR(100),
  `priority`            VARCHAR(50),
  `readiness_state`     VARCHAR(100),
  `repair_required`     VARCHAR(20),
  `status`              VARCHAR(100),
  `last_validated_at`   VARCHAR(100),
  `notes`               TEXT,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_validation_id` (`validation_id`),
  KEY `idx_surface_id` (`surface_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 14. JSON Asset Registry ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `json_assets` (
  `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `asset_id`          VARCHAR(255),
  `brand_name`        VARCHAR(255),
  `asset_key`         VARCHAR(255),
  `asset_type`        VARCHAR(100),
  `cpt_slug`          VARCHAR(255),
  `mapping_status`    VARCHAR(100),
  `mapping_version`   VARCHAR(50),
  `storage_format`    VARCHAR(100),
  `google_drive_link` TEXT,
  `source_mode`       VARCHAR(100),
  `source_asset_ref`  VARCHAR(255),
  `json_payload`      MEDIUMTEXT,
  `transport_status`  VARCHAR(100),
  `validation_status` VARCHAR(100),
  `last_validated_at` VARCHAR(100),
  `notes`             TEXT,
  `active_status`     VARCHAR(20),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_id` (`asset_id`),
  KEY `idx_brand_asset` (`brand_name`, `asset_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 15. Execution Log Unified (append-only, write-heavy) ──────────────────────
CREATE TABLE IF NOT EXISTS `execution_log` (
  `id`                                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_date`                              VARCHAR(50),
  `start_time`                            VARCHAR(100),
  `end_time`                              VARCHAR(100),
  `duration_seconds`                      VARCHAR(50),
  `entry_type`                            VARCHAR(100),
  `execution_class`                       VARCHAR(255),
  `source_layer`                          VARCHAR(255),
  `user_input`                            TEXT,
  `matched_aliases`                       TEXT,
  `route_keys`                            TEXT,
  `selected_workflows`                    TEXT,
  `engine_chain`                          TEXT,
  `execution_mode`                        VARCHAR(100),
  `decision_trigger`                      TEXT,
  `score_before`                          VARCHAR(50),
  `score_after`                           VARCHAR(50),
  `performance_delta`                     VARCHAR(50),
  `execution_status`                      VARCHAR(100),
  `output_summary`                        MEDIUMTEXT,
  `recovery_status`                       VARCHAR(100),
  `recovery_score`                        VARCHAR(50),
  `recovery_notes`                        TEXT,
  `route_id`                              VARCHAR(255),
  `route_status`                          VARCHAR(100),
  `route_source`                          VARCHAR(255),
  `matched_row_id`                        VARCHAR(255),
  `intake_validation_status`              VARCHAR(100),
  `execution_ready_status`                VARCHAR(100),
  `failure_reason`                        TEXT,
  `recovery_action`                       TEXT,
  `artifact_json_asset_id`               VARCHAR(255),
  `target_module_writeback`              VARCHAR(255),
  `target_workflow_writeback`            VARCHAR(255),
  `execution_trace_id_writeback`         VARCHAR(255),
  `log_source_writeback`                 VARCHAR(255),
  `monitored_row_writeback`              VARCHAR(255),
  `performance_impact_row_writeback`     VARCHAR(255),
  `used_logic_id`                         VARCHAR(255),
  `used_logic_name`                       VARCHAR(255),
  `resolved_logic_doc_id`                VARCHAR(255),
  `resolved_logic_mode`                  VARCHAR(100),
  `logic_pointer_resolution_status`      VARCHAR(100),
  `logic_knowledge_status`               VARCHAR(100),
  `logic_rollback_status`                VARCHAR(100),
  `logic_association_status`             VARCHAR(100),
  `used_engine_names`                    TEXT,
  `used_engine_registry_refs`            TEXT,
  `used_engine_file_ids`                 TEXT,
  `engine_resolution_status`             VARCHAR(100),
  `engine_association_status`            VARCHAR(100),
  `retired_shadow_target_module`         VARCHAR(255),
  `retired_shadow_target_workflow`       VARCHAR(255),
  `retired_shadow_execution_trace_id`    VARCHAR(255),
  `retired_shadow_log_source`            VARCHAR(255),
  `retired_shadow_monitored_row`         VARCHAR(255),
  `retired_shadow_performance_impact_row` VARCHAR(255),
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_run_date`         (`run_date`),
  KEY `idx_execution_class`  (`execution_class`),
  KEY `idx_execution_status` (`execution_status`),
  KEY `idx_entry_type`       (`entry_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 16. Business Activity Type Registry ────────────────────────────────────────
-- This table is a baseline prerequisite for migration 1043 and the runtime census.
CREATE TABLE IF NOT EXISTS `business_activity_types` (
  `id`                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_activity_type_key`     VARCHAR(255) NOT NULL,
  `activity_key`                   VARCHAR(255),
  `business_type_key`              VARCHAR(255),
  `label`                          VARCHAR(255),
  `parent_activity_type`           VARCHAR(255),
  `default_knowledge_profile_key`  VARCHAR(255),
  `supported_engine_categories`    TEXT,
  `supported_route_keys`           TEXT,
  `supported_workflows`             TEXT,
  `brand_core_required`             VARCHAR(20),
  `status`                          VARCHAR(100),
  `notes`                           TEXT,
  `active`                          VARCHAR(20),
  `created_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_business_activity_type_key` (`business_activity_type_key`),
  KEY `idx_business_activity_type_business_type` (`business_type_key`),
  KEY `idx_business_activity_type_active` (`active`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 17. Business Type Knowledge Profiles ───────────────────────────────────────
-- This table is a baseline prerequisite for migration 039 and context resolution.
CREATE TABLE IF NOT EXISTS `business_type_profiles` (
  `id`                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_type_key`              VARCHAR(255) NOT NULL,
  `knowledge_profile_key`           VARCHAR(255),
  `supported_engine_categories`     TEXT,
  `authoritative_read_home`         VARCHAR(255),
  `business_type_specific_read_home` VARCHAR(255),
  `shared_knowledge_read_home`      VARCHAR(255),
  `compatible_route_keys`           TEXT,
  `compatible_workflows`            TEXT,
  `profile_status`                  VARCHAR(100),
  `notes`                           TEXT,
  `active`                          VARCHAR(20),
  `created_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_business_type_profile_key` (`business_type_key`),
  KEY `idx_business_type_profile_knowledge` (`knowledge_profile_key`),
  KEY `idx_business_type_profile_active` (`active`, `profile_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 18. Brand Path Resolver Registry ────────────────────────────────────────────
-- This table is a baseline prerequisite for migration 039 and brand/path readback.
CREATE TABLE IF NOT EXISTS `brand_paths` (
  `id`                              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_key`                       VARCHAR(255) NOT NULL,
  `normalized_brand_name`           VARCHAR(255),
  `business_type_key`               VARCHAR(255),
  `knowledge_profile_key`           VARCHAR(255),
  `brand_folder_id`                 VARCHAR(255),
  `brand_folder_path`               VARCHAR(500),
  `brand_core_docs_json`            TEXT,
  `target_key`                      VARCHAR(255),
  `base_url`                        VARCHAR(500),
  `status`                          VARCHAR(100),
  `active`                          VARCHAR(20),
  `created_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_brand_path_brand_key` (`brand_key`),
  KEY `idx_brand_path_target_key` (`target_key`),
  KEY `idx_brand_path_business_type` (`business_type_key`),
  KEY `idx_brand_path_active` (`active`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 19. Tenant Secret Slots ────────────────────────────────────────────────────
-- Baseline prerequisites for migration 058 and tenant-scoped credential resolution.
-- Values are provisioned separately; this schema contains no secret payloads.
CREATE TABLE IF NOT EXISTS `tenant_secrets` (
  `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id`         VARCHAR(36) NOT NULL,
  `secret_key`        VARCHAR(128) NOT NULL,
  `secret_type`       VARCHAR(64) NOT NULL,
  `storage_backend`   ENUM('gcp_secret_manager','mounted_file','external_vault','env_ref','manual','db_encrypted') NOT NULL DEFAULT 'manual',
  `secret_ref`        VARCHAR(255) NULL,
  `value_sha256`      CHAR(64) NULL,
  `value_ciphertext`  LONGTEXT NULL,
  `metadata_json`     LONGTEXT NULL,
  `status`            VARCHAR(64) NOT NULL DEFAULT 'active',
  `created_by`        VARCHAR(64) NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tenant_secret_key` (`tenant_id`, `secret_key`),
  KEY `idx_tenant_secrets_status` (`tenant_id`, `status`),
  KEY `idx_tenant_secrets_storage` (`storage_backend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── 20. Platform Secret Slots ──────────────────────────────────────────────────
-- Baseline prerequisite for migration 058 and platform-scoped credential resolution.
CREATE TABLE IF NOT EXISTS `platform_secrets` (
  `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `secret_key`        VARCHAR(128) NOT NULL,
  `secret_type`       VARCHAR(64) NOT NULL,
  `storage_backend`   ENUM('gcp_secret_manager','mounted_file','external_vault','env_ref','manual','db_encrypted') NOT NULL DEFAULT 'manual',
  `secret_ref`        VARCHAR(255) NULL,
  `value_sha256`      CHAR(64) NULL,
  `value_ciphertext`  LONGTEXT NULL,
  `metadata_json`     LONGTEXT NULL,
  `status`            VARCHAR(64) NOT NULL DEFAULT 'active',
  `created_by`        VARCHAR(64) NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_platform_secret_key` (`secret_key`),
  KEY `idx_platform_secrets_status` (`status`),
  KEY `idx_platform_secrets_storage` (`storage_backend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_credentials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(36) NOT NULL,
  `auth_provider` ENUM('platform', 'google') NOT NULL,
  `provider_id` VARCHAR(255) NULL,
  `password_hash` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_provider` (`user_id`, `auth_provider`),
  KEY `idx_provider_id` (`auth_provider`, `provider_id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
