import { createHash, randomUUID } from "node:crypto";
import { RECOVERY_READINESS_EVIDENCE_CONTRACT, evaluateExternalStagingEvidence } from "./recoveryReadinessEvidence.js";
import { verifyStagingRecoverySignedCertificationRecord } from "./stagingRecoveryCertificationPublicTrust.js";

export const STAGING_RECOVERY_CANARY_EVIDENCE_CONTRACT = "mad4b.staging-recovery-genuine-canary-evidence.v1";
export const STAGING_RECOVERY_CERTIFICATION_CONTRACT = "mad4b.recovery-staging-certification.v1";
export const STAGING_RECOVERY_GITHUB_VERIFICATION_CONTRACT = "mad4b.staging-recovery-github-verification.v2";
const SHA40 = /^[a-f0-9]{40}$/u; const SHA256 = /^[a-f0-9]{64}$/u; const SAFE_ID = /^[A-Za-z0-9._:-]{8,160}$/u;
const PHASES = ["created", "planned", "awaiting_approval", "approval_granted", "locked", "executing", "provider_acknowledged", "readback_pending", "verifying", "verified", "recovered"];
const SECRET_KEY = /(password|secret|credential|authorization|private[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret)/u;
const stable = (v) => Array.isArray(v) ? v.map(stable) : v && typeof v === "object" ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, stable(v[k])])) : v;
export const stagingRecoveryCertificationCanonicalJson = (v) => JSON.stringify(stable(v));
export const stagingRecoveryCertificationHash = (v) => createHash("sha256").update(stagingRecoveryCertificationCanonicalJson(v)).digest("hex");
function fail(code, message) { throw Object.assign(new Error(message), { code, status: 409, details: { secrets_included: false } }); }
function noSecrets(value, at = "evidence") { if (!value || typeof value !== "object") return; for (const [key, child] of Object.entries(value)) { const negativeAttestation = key === "caller_credentials_accepted" && child === false; if (key !== "secrets_included" && !negativeAttestation && SECRET_KEY.test(key.toLowerCase())) fail("RECOVERY_CANARY_SECRET_FIELD_FORBIDDEN", `Forbidden field: ${at}.${key}`); noSecrets(child, `${at}.${key}`); } }
function fresh(generatedAt, expiresAt, now = Date.now()) { const g = Date.parse(generatedAt); const e = Date.parse(expiresAt); if (!Number.isFinite(g) || !Number.isFinite(e) || g > now + 60_000 || e <= now || e <= g || e - g > 86_400_000) fail("RECOVERY_CANARY_EVIDENCE_EXPIRED", "Evidence freshness window is invalid."); }

function kernelArtifacts({ plan, approval, ticket, receipt, run }) {
  if (plan?.contract !== "mad4b.recovery-remediation-plan.v1" || !SHA256.test(plan.plan_hash || "")) fail("RECOVERY_CANARY_PLAN_INVALID", "A Kernel plan is required.");
  const step = plan.steps?.find((v) => v.step_id === receipt?.step_id);
  if (!step || !SHA256.test(step.step_hash || "") || step.operation !== "staging.certification.canary") fail("RECOVERY_CANARY_OPERATION_DENIED", "Only the registered Staging canary is allowed.");
  if (approval?.contract !== "mad4b.recovery-approval-challenge.v1" || approval.plan_hash !== plan.plan_hash || approval.step_id !== step.step_id || approval.step_hash !== step.step_hash) fail("RECOVERY_CANARY_APPROVAL_BINDING_INVALID", "Approval binding is invalid.");
  if (!SAFE_ID.test(ticket?.ticket_id || "") || !SHA256.test(ticket?.ticket_hash || "") || ticket.plan_hash !== plan.plan_hash || ticket.step_id !== step.step_id || ticket.step_hash !== step.step_hash || ticket.approval_id !== approval.approval_id) fail("RECOVERY_CANARY_TICKET_BINDING_INVALID", "Ticket binding is invalid.");
  if (receipt?.contract !== "mad4b.recovery-remediation-execution-receipt.v1" || receipt.plan_hash !== plan.plan_hash || receipt.step_id !== step.step_id || receipt.ticket_id !== ticket.ticket_id || receipt.run_id !== run?.run_id || receipt.phase !== "recovered" || receipt.status !== "recovered") fail("RECOVERY_CANARY_RECEIPT_INVALID", "A recovered Kernel receipt is required.");
  if (!SAFE_ID.test(run?.run_id || "") || run.plan_hash !== plan.plan_hash || run.step_id !== step.step_id || run.phase !== "recovered" || run.status !== "recovered" || !Array.isArray(run.events)) fail("RECOVERY_CANARY_RUN_INVALID", "The durable Kernel run is invalid.");
  const phases = run.events.map((v) => v.phase); if (phases.length !== PHASES.length || phases.some((v, i) => v !== PHASES[i])) fail("RECOVERY_CANARY_LIFECYCLE_INVALID", "The full Kernel state machine was not observed.");
  if (run.events.some((v) => !SHA256.test(v.evidence_hash || ""))) fail("RECOVERY_CANARY_EVENT_CHAIN_INVALID", "Kernel event evidence hash missing.");
  if (receipt.database_mutation_performed !== false || receipt.provider_mutation_performed !== false || receipt.production_mutation_performed === true || receipt.secrets_included !== false) fail("RECOVERY_CANARY_SAFETY_BOUNDARY_INVALID", "Forbidden mutation or secret boundary crossed.");
  return step;
}

export function produceGenuineStagingRecoveryCanaryEvidence({ deploymentAttestation, targetIdentity, plan, approval, ticket, receipt, run, workerDeploymentEvidence, ingressBuildIdentity, registrationEvidence, oauthEvidence, networkEvidence, artifactIntegrity, nonce = `nonce:${randomUUID()}`, certificationRunId = `cert-run:${randomUUID()}`, generatedAt = new Date().toISOString(), expiresAt = new Date(Date.now() + 3_600_000).toISOString() } = {}) {
  if (deploymentAttestation?.environment !== "staging" || !SHA40.test(deploymentAttestation.sha || "") || targetIdentity?.environment !== "staging" || !SHA256.test(targetIdentity.target_fingerprint || "") || deploymentAttestation.target_fingerprint !== targetIdentity.target_fingerprint) fail("RECOVERY_CANARY_TARGET_BINDING_INVALID", "Exact Staging SHA/target binding is required.");
  if (!SAFE_ID.test(nonce) || !SAFE_ID.test(certificationRunId)) fail("RECOVERY_CANARY_RUN_BINDING_INVALID", "Run ID and nonce are invalid."); fresh(generatedAt, expiresAt);
  const step = kernelArtifacts({ plan, approval, ticket, receipt, run });
  for (const evidence of [registrationEvidence, oauthEvidence, networkEvidence, workerDeploymentEvidence]) if (evidence?.deployment_sha !== deploymentAttestation.sha || evidence?.target_fingerprint !== targetIdentity.target_fingerprint || !SHA256.test(evidence?.evidence_hash || "")) fail("RECOVERY_CANARY_EXTERNAL_BINDING_INVALID", "External evidence binding is invalid.");
  if (ingressBuildIdentity?.deployment_sha !== deploymentAttestation.sha) fail("RECOVERY_CANARY_INGRESS_BINDING_INVALID", "Ingress build binding is invalid.");
  if (artifactIntegrity?.valid !== true || !SHA256.test(artifactIntegrity.manifest_sha256 || "")) fail("RECOVERY_CANARY_ARTIFACT_INTEGRITY_INVALID", "Artifact integrity proof is invalid.");
  const base = { contract: STAGING_RECOVERY_CANARY_EVIDENCE_CONTRACT, environment: "staging", deployment_sha: deploymentAttestation.sha, target_fingerprint: targetIdentity.target_fingerprint, certification_run_id: certificationRunId, nonce, generated_at: generatedAt, expires_at: expiresAt, kernel: { contract: "mad4b.recovery-kernel.v1", plan_id: plan.plan_id, plan_hash: plan.plan_hash, step_id: step.step_id, step_hash: step.step_hash, operation: step.operation, approval_id: approval.approval_id, approval_hash: approval.approval_hash, approval_version: approval.approval_version, ticket_id: ticket.ticket_id, ticket_hash: ticket.ticket_hash, run_id: run.run_id, receipt_hash: stagingRecoveryCertificationHash(receipt), event_chain_hash: stagingRecoveryCertificationHash(run.events), lifecycle_phases: run.events.map((v) => v.phase) }, registrationEvidence, oauthEvidence, networkEvidence, workerDeploymentEvidence, ingressBuildIdentity, artifactIntegrity, safety: { production_live_enabled: false, production_mutation_performed: false, database_mutation_performed: false, provider_mutation_performed: false, local_connector_production_authority: false }, secrets_included: false };
  noSecrets(base); return Object.freeze({ ...base, evidence_envelope_sha256: stagingRecoveryCertificationHash(base) });
}

export async function independentlyVerifyStagingRecoveryCanaryEvidence(envelope, { expectedSha, expectedTargetFingerprint, workflowSourceSha, now = Date.now(), loadKernelArtifacts } = {}) {
  if (envelope?.contract !== STAGING_RECOVERY_CANARY_EVIDENCE_CONTRACT) fail("RECOVERY_CANARY_EVIDENCE_CONTRACT_INVALID", "Unknown evidence contract.");
  const unsigned = { ...envelope }; delete unsigned.evidence_envelope_sha256;
  if (!SHA256.test(envelope.evidence_envelope_sha256 || "") || stagingRecoveryCertificationHash(unsigned) !== envelope.evidence_envelope_sha256) fail("RECOVERY_CANARY_EVIDENCE_HASH_MISMATCH", "Evidence envelope hash mismatch.");
  if (envelope.environment !== "staging" || envelope.deployment_sha !== expectedSha || envelope.target_fingerprint !== expectedTargetFingerprint || workflowSourceSha !== expectedSha) fail("RECOVERY_CANARY_EXACT_TARGET_MISMATCH", "Exact SHA/target mismatch.");
  fresh(envelope.generated_at, envelope.expires_at, now); noSecrets(envelope);
  if (typeof loadKernelArtifacts !== "function") fail("RECOVERY_CANARY_KERNEL_READBACK_UNAVAILABLE", "Independent Kernel readback is required.");
  const artifacts = await loadKernelArtifacts({ plan_id: envelope.kernel.plan_id, approval_id: envelope.kernel.approval_id, ticket_id: envelope.kernel.ticket_id, run_id: envelope.kernel.run_id }); const step = kernelArtifacts(artifacts);
  if (artifacts.plan.plan_hash !== envelope.kernel.plan_hash || step.step_hash !== envelope.kernel.step_hash || artifacts.approval.approval_hash !== envelope.kernel.approval_hash || artifacts.ticket.ticket_hash !== envelope.kernel.ticket_hash || stagingRecoveryCertificationHash(artifacts.receipt) !== envelope.kernel.receipt_hash || stagingRecoveryCertificationHash(artifacts.run.events) !== envelope.kernel.event_chain_hash) fail("RECOVERY_CANARY_KERNEL_BINDING_MISMATCH", "Independent Kernel bindings mismatch.");
  const external = await evaluateExternalStagingEvidence({ candidateSha: envelope.deployment_sha, candidateTargetFingerprint: envelope.target_fingerprint, authenticity_verified: true, registrationEvidence: envelope.registrationEvidence, oauthEvidence: envelope.oauthEvidence, networkEvidence: envelope.networkEvidence, workerDeploymentEvidence: envelope.workerDeploymentEvidence }, envelope.ingressBuildIdentity);
  if (!external.ready) fail("RECOVERY_CANARY_EXTERNAL_EVIDENCE_INVALID", external.blocking_failures.join(","));
  if (envelope.artifactIntegrity?.valid !== true || envelope.safety?.production_live_enabled !== false || envelope.safety?.production_mutation_performed !== false) fail("RECOVERY_CANARY_BOUNDARY_INVALID", "Safety boundary invalid.");
  const checks = { exact_main: true, workflow_source_same_sha: true, evidence_envelope_hash: true, target_binding: true, run_nonce_binding: SAFE_ID.test(envelope.certification_run_id) && SAFE_ID.test(envelope.nonce), worker_provenance: external.checks.deployed_worker_provenance && external.checks.gateway_request_build_binding, artifact_integrity: true, evidence_freshness: true, external_evidence: external.ready, production_boundary: true, secret_scan: true };
  const base = { contract: STAGING_RECOVERY_GITHUB_VERIFICATION_CONTRACT, verified: Object.values(checks).every(Boolean), evidence_envelope_sha256: envelope.evidence_envelope_sha256, deployment_sha: envelope.deployment_sha, target_fingerprint: envelope.target_fingerprint, certification_run_id: envelope.certification_run_id, nonce: envelope.nonce, checks, secrets_included: false };
  return Object.freeze({ ...base, verification_report_sha256: stagingRecoveryCertificationHash(base) });
}

export function buildRecoveryReadinessSigningPayload(envelope, report, { issuer, keyId } = {}) {
  if (report?.verified !== true || report.evidence_envelope_sha256 !== envelope?.evidence_envelope_sha256) fail("RECOVERY_CANARY_VERIFICATION_REPORT_INVALID", "Verified report required.");
  const stagingCertification = { contract: STAGING_RECOVERY_CERTIFICATION_CONTRACT, certification_id: `cert:staging:${envelope.certification_run_id}`, status: "passed", result: "pass", environment_key: "staging", branch: "main", deployment_sha: envelope.deployment_sha, runtime_sha: envelope.deployment_sha, target_fingerprint: envelope.target_fingerprint, provider_environment: "staging", authority_graph: { ready: true, test_or_mock_adapter_detected: false }, lifecycle_trace: { source: "recovery_kernel", run_id: envelope.kernel.run_id, event_chain_hash: envelope.kernel.event_chain_hash, phases: envelope.kernel.lifecycle_phases }, audit_evidence: { durable: true, evidence_hash: envelope.evidence_envelope_sha256, canonical_payload_hash: report.verification_report_sha256 }, artifact_integrity: envelope.artifactIntegrity, expires_at: envelope.expires_at, safety: { ...envelope.safety, caller_credentials_accepted: false }, secrets_included: false };
  return Object.freeze({ contract: RECOVERY_READINESS_EVIDENCE_CONTRACT, issuer, key_id: keyId, environment: "staging", branch: "main", deployment_sha: envelope.deployment_sha, target_fingerprint: envelope.target_fingerprint, certification_run_id: envelope.certification_run_id, nonce: envelope.nonce, evidence_envelope_sha256: envelope.evidence_envelope_sha256, verification_report_sha256: report.verification_report_sha256, generated_at: envelope.generated_at, expires_at: envelope.expires_at, production_live_enabled: false, production_mutation_performed: false, local_connector_production_authority: false, stagingCertification, registrationEvidence: envelope.registrationEvidence, oauthEvidence: envelope.oauthEvidence, networkEvidence: envelope.networkEvidence, workerDeploymentEvidence: envelope.workerDeploymentEvidence, unresolvedRecoveryIncidents: [], secrets_included: false });
}

export async function publishVerifiedStagingRecoveryCertification({ signedRecord, trust, evidenceStore, expectedSha, expectedTargetFingerprint, expectedRunId, expectedNonce } = {}) {
  const verified = verifyStagingRecoverySignedCertificationRecord(signedRecord, { trust, expectedSha, expectedTargetFingerprint, expectedRunId, expectedNonce });
  if (!verified.valid) fail("RECOVERY_CERTIFICATION_PUBLICATION_SIGNATURE_INVALID", "Public trust verification failed.");
  if (typeof evidenceStore?.putCertification !== "function" || typeof evidenceStore?.setCurrentCertification !== "function") fail("RECOVERY_CERTIFICATION_STORE_UNAVAILABLE", "Persistent evidence store unavailable.");
  const id = await evidenceStore.putCertification(signedRecord); await evidenceStore.setCurrentCertification(id);
  return Object.freeze({ published: true, certification_record_id: id, deployment_sha: expectedSha, target_fingerprint: expectedTargetFingerprint, secrets_included: false });
}
