import { randomUUID } from "node:crypto";
import { getPool } from "./db.js";
import {
  buildActivationOperationalSummary,
  buildActivationDashboardManifest,
  buildActivationTabManifest,
} from "./activationAwarenessService.js";

const PRODUCT_TAB_TO_OPERATIONAL_TAB = Object.freeze({
  tenant_today: "container_overview",
  tenant_growth_plan: "container_growth_signals",
  tenant_customers_leads: "container_growth_signals",
  tenant_sales_bookings: "container_growth_signals",
  tenant_content_seo: "container_knowledge",
  tenant_campaigns: "container_growth_signals",
  tenant_reputation: "container_growth_signals",
  tenant_tasks: "container_tasks",
  tenant_operations: "container_readiness_quality",
  tenant_integrations: "container_connectors",
  tenant_knowledge_brand: "container_knowledge",
  tenant_reports: "container_evidence_activity",
});

const DEFAULT_PRODUCT_TABS = Object.freeze([
  "tenant_today",
  "tenant_growth_plan",
  "tenant_customers_leads",
  "tenant_sales_bookings",
  "tenant_content_seo",
  "tenant_campaigns",
  "tenant_tasks",
  "tenant_operations",
  "tenant_integrations",
  "tenant_knowledge_brand",
]);

const ALLOWED_EVENT_TYPES = new Set([
  "shown",
  "opened",
  "accepted",
  "dismissed",
  "executed",
  "failed",
  "result_observed",
]);

function parseJson(value, fallback = null) {
  if (value === null || value === undefined || value === "") return fallback;
  if (typeof value === "object") return value;
  try { return JSON.parse(String(value)); } catch { return fallback; }
}
function safeNumber(value) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function safeText(value, max = 500) { const text = String(value || "").trim(); return text ? text.slice(0, max) : null; }
function normalizeKey(value, fallback = null) {
  const normalized = String(value || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized || fallback;
}
function booleanLike(value) { return ["1","true","yes","ready","active","enabled"].includes(String(value || "").trim().toLowerCase()); }
function uniq(values = []) { return [...new Set(values.filter(Boolean))]; }
async function safeRows(sql, params = []) {
  try { const [rows] = await getPool().query(sql, params); return { ok: true, rows: Array.isArray(rows) ? rows : [] }; }
  catch (error) { return { ok: false, rows: [], error: { code: error?.code || "tenant_growth_dashboard_query_failed", message: error?.message || String(error) } }; }
}

export function normalizeDashboardPreferences(input = {}) {
  const density = ["compact","comfortable","detailed"].includes(String(input.dashboard_density || "")) ? String(input.dashboard_density) : "comfortable";
  return {
    active_container_key: safeText(input.active_container_key, 220),
    active_tab_key: safeText(input.active_tab_key, 160),
    pinned_tabs: uniq(Array.isArray(input.pinned_tabs) ? input.pinned_tabs.map((value) => safeText(value, 160)) : []),
    hidden_tabs: uniq(Array.isArray(input.hidden_tabs) ? input.hidden_tabs.map((value) => safeText(value, 160)) : []),
    preferred_date_range: safeText(input.preferred_date_range, 80) || "last_30_days",
    saved_filters: input.saved_filters && typeof input.saved_filters === "object" ? input.saved_filters : {},
    dismissed_alerts: uniq(Array.isArray(input.dismissed_alerts) ? input.dismissed_alerts.map((value) => safeText(value, 180)) : []),
    favorite_metrics: uniq(Array.isArray(input.favorite_metrics) ? input.favorite_metrics.map((value) => safeText(value, 180)) : []),
    dashboard_density: density,
    language: safeText(input.language, 32), currency: safeText(input.currency, 16), timezone: safeText(input.timezone, 80),
    notification_preferences: input.notification_preferences && typeof input.notification_preferences === "object" ? input.notification_preferences : {},
  };
}
function rowToPreferences(row = {}) {
  return normalizeDashboardPreferences({ ...row, pinned_tabs: parseJson(row.pinned_tabs_json, []), hidden_tabs: parseJson(row.hidden_tabs_json, []), saved_filters: parseJson(row.saved_filters_json, {}), dismissed_alerts: parseJson(row.dismissed_alerts_json, []), favorite_metrics: parseJson(row.favorite_metrics_json, []), notification_preferences: parseJson(row.notification_preferences_json, {}) });
}
export async function readTenantDashboardPreferences({ tenantId, userId } = {}) {
  const result = await safeRows("SELECT * FROM tenant_dynamic_dashboard_preferences WHERE tenant_id = ? AND user_id = ? LIMIT 1", [tenantId, userId]);
  return { ok: result.ok, preferences: result.rows[0] ? rowToPreferences(result.rows[0]) : normalizeDashboardPreferences({}), degraded: result.ok === false, error: result.error || null };
}
export async function upsertTenantDashboardPreferences({ tenantId, userId, preferences = {} } = {}) {
  const normalized = normalizeDashboardPreferences(preferences);
  await getPool().query(`INSERT INTO tenant_dynamic_dashboard_preferences
    (preference_id, tenant_id, user_id, active_container_key, active_tab_key, pinned_tabs_json, hidden_tabs_json, preferred_date_range, saved_filters_json, dismissed_alerts_json, favorite_metrics_json, dashboard_density, language, currency, timezone, notification_preferences_json, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UTC_TIMESTAMP(), UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE active_container_key=VALUES(active_container_key), active_tab_key=VALUES(active_tab_key), pinned_tabs_json=VALUES(pinned_tabs_json), hidden_tabs_json=VALUES(hidden_tabs_json), preferred_date_range=VALUES(preferred_date_range), saved_filters_json=VALUES(saved_filters_json), dismissed_alerts_json=VALUES(dismissed_alerts_json), favorite_metrics_json=VALUES(favorite_metrics_json), dashboard_density=VALUES(dashboard_density), language=VALUES(language), currency=VALUES(currency), timezone=VALUES(timezone), notification_preferences_json=VALUES(notification_preferences_json), updated_at=UTC_TIMESTAMP()`,
    [randomUUID(), tenantId, userId, normalized.active_container_key, normalized.active_tab_key, JSON.stringify(normalized.pinned_tabs), JSON.stringify(normalized.hidden_tabs), normalized.preferred_date_range, JSON.stringify(normalized.saved_filters), JSON.stringify(normalized.dismissed_alerts), JSON.stringify(normalized.favorite_metrics), normalized.dashboard_density, normalized.language, normalized.currency, normalized.timezone, JSON.stringify(normalized.notification_preferences)]);
  return { ok: true, preferences: normalized, secrets_included: false };
}

async function loadContainers(tenantId) { return safeRows(`SELECT workspace_id, tenant_id, workspace_key, display_name, workspace_type, bootstrap_status, linked_brand_key, linked_system_ids, config_json, updated_at FROM workspace_registry WHERE tenant_id = ? AND bootstrap_status <> 'error' ORDER BY FIELD(bootstrap_status, 'ready','in_progress','degraded','not_started'), updated_at DESC LIMIT 100`, [tenantId]); }
function publicContainer(row = {}) { return { container_key: `workspace:${row.workspace_id}`, workspace_id: row.workspace_id, workspace_key: row.workspace_key, display_name: row.display_name, workspace_type: row.workspace_type, bootstrap_status: row.bootstrap_status, linked_brand_key: row.linked_brand_key || null, updated_at: row.updated_at || null }; }

async function loadBusinessContext({ tenantId, workspace }) {
  const [tenantResult, brandResult] = await Promise.all([
    safeRows("SELECT tenant_type, display_name, metadata_json FROM tenants WHERE tenant_id = ? LIMIT 1", [tenantId]),
    workspace?.linked_brand_key ? safeRows("SELECT brand_name, target_key, brand_core_ready, maturity, growth_velocity, next_auto_action, status, updated_at FROM brands WHERE target_key = ? LIMIT 1", [workspace.linked_brand_key]) : Promise.resolve({ ok: true, rows: [] }),
  ]);
  const tenant = tenantResult.rows[0] || {}; const tenantMetadata = parseJson(tenant.metadata_json, {}) || {}; const workspaceConfig = parseJson(workspace?.config_json, {}) || {}; const businessProfile = tenantMetadata.business_profile || {}; const onboarding = tenantMetadata.onboarding_preferences || {};
  const goals = uniq([...(Array.isArray(onboarding.goals) ? onboarding.goals : []), ...(Array.isArray(tenantMetadata.growth_goals) ? tenantMetadata.growth_goals : []), workspaceConfig.primary_goal].map((value) => normalizeKey(value)).filter(Boolean));
  const businessTypeKey = normalizeKey(workspaceConfig.business_type_key || businessProfile.business_type_key || businessProfile.bizType, "general_business");
  const activityCandidate = normalizeKey(workspaceConfig.business_activity_type_key || businessProfile.business_activity_type_key || businessProfile.industry, null);
  const activityResult = activityCandidate ? await safeRows(`SELECT business_activity_type_key, activity_key, business_type_key, label, parent_activity_type, default_knowledge_profile_key, supported_engine_categories, supported_route_keys, supported_workflows, brand_core_required FROM business_activity_types WHERE business_activity_type_key = ? OR activity_key = ? ORDER BY CASE WHEN business_activity_type_key = ? THEN 0 ELSE 1 END LIMIT 1`, [activityCandidate, activityCandidate, activityCandidate]) : { ok: true, rows: [] };
  const activity = activityResult.rows[0] || null; const brand = brandResult.rows[0] || null;
  return { tenant: { tenant_type: tenant.tenant_type || null, display_name: tenant.display_name || null }, business_type_key: activity?.business_type_key || businessTypeKey, business_activity_type_key: activity?.business_activity_type_key || activityCandidate, business_activity_label: activity?.label || businessProfile.industry || null, parent_activity_type: activity?.parent_activity_type || null, growth_stage: normalizeKey(workspaceConfig.growth_stage || brand?.maturity || tenantMetadata.growth_stage, "growth"), primary_goal: goals[0] || "grow_revenue", goals: goals.length ? goals : ["grow_revenue"], brand: brand ? { brand_name: brand.brand_name, brand_key: brand.target_key, brand_core_ready: booleanLike(brand.brand_core_ready), maturity: brand.maturity || null, growth_velocity: brand.growth_velocity || null, next_auto_action: brand.next_auto_action || null, status: brand.status || null, updated_at: brand.updated_at || null } : { brand_name: workspace?.display_name || null, brand_key: workspace?.linked_brand_key || null, brand_core_ready: false, maturity: null, growth_velocity: null, next_auto_action: null, status: null, updated_at: null }, activity_registry: activity ? { default_knowledge_profile_key: activity.default_knowledge_profile_key || null, supported_engine_categories: activity.supported_engine_categories || null, supported_route_keys: activity.supported_route_keys || null, supported_workflows: activity.supported_workflows || null, brand_core_required: booleanLike(activity.brand_core_required) } : null, source_readiness: { tenant_metadata: tenantResult.ok, workspace_config: Boolean(workspace), brand_core: Boolean(brand), business_activity_registry: activityResult.ok } };
}

async function loadProductTabRegistry() { return safeRows("SELECT tab_key, display_name, description, icon_key, mobile_label, renderer_key, default_pinned, goal_tags_json, empty_state_template_key, instruction_template_key, mobile_priority, tab_group, priority_order FROM activation_dynamic_tab_registry WHERE status = 'active' AND tab_key LIKE 'tenant_%' ORDER BY mobile_priority ASC, priority_order ASC, tab_key ASC"); }
async function loadTabProfiles() { return safeRows("SELECT profile_key, business_type_key, business_activity_type_key, tab_key, priority_order, default_pinned, goal_tags_json FROM growth_dashboard_tab_profile_registry WHERE status = 'active' ORDER BY priority_order ASC, tab_key ASC"); }
export function resolveProductTabKeys({ businessContext = {}, profileRows = [], preferences = {} } = {}) {
  const businessType = normalizeKey(businessContext.business_type_key, "general_business"); const activityType = normalizeKey(businessContext.business_activity_type_key, null); const hidden = new Set(preferences.hidden_tabs || []); const pinned = new Set(preferences.pinned_tabs || []);
  const matching = profileRows.filter((row) => activityType && row.business_activity_type_key === activityType || row.business_type_key === businessType || row.profile_key === "default" || row.business_type_key === "general_business");
  const specificity = (row) => activityType && row.business_activity_type_key === activityType ? 0 : row.business_type_key === businessType ? 1 : 2;
  matching.sort((a,b) => specificity(a)-specificity(b) || safeNumber(a.priority_order)-safeNumber(b.priority_order));
  const selected = uniq([...(preferences.pinned_tabs || []), ...matching.map((row) => row.tab_key), ...DEFAULT_PRODUCT_TABS]).filter((tabKey) => !hidden.has(tabKey));
  selected.sort((a,b) => pinned.has(a)!==pinned.has(b) ? pinned.has(a)?-1:1 : safeNumber(matching.find((row)=>row.tab_key===a)?.priority_order || 999)-safeNumber(matching.find((row)=>row.tab_key===b)?.priority_order || 999));
  return selected.slice(0,12);
}
async function loadInstructions(businessContext) {
  const result = await safeRows("SELECT instruction_key, business_type_key, business_activity_type_key, goal_key, headline, guidance_template, quick_commands_json, empty_state_actions_json, priority_order FROM growth_dashboard_instruction_registry WHERE status = 'active' ORDER BY priority_order ASC, instruction_key ASC");
  const businessType=normalizeKey(businessContext.business_type_key,null), activityType=normalizeKey(businessContext.business_activity_type_key,null), goal=normalizeKey(businessContext.primary_goal,null);
  const scored=result.rows.map((row)=>{let score=0;if(activityType&&row.business_activity_type_key===activityType)score+=100;if(businessType&&row.business_type_key===businessType)score+=60;if(goal&&row.goal_key===goal)score+=30;if(!row.business_type_key&&!row.business_activity_type_key&&!row.goal_key)score+=1;return{row,score};}).filter((item)=>item.score>0).sort((a,b)=>b.score-a.score||safeNumber(a.row.priority_order)-safeNumber(b.row.priority_order));
  return { result, instruction: scored[0]?.row || { instruction_key:"tenant_growth_generic_fallback", headline:"Your growth cockpit is ready.", guidance_template:"Turn platform data into clear business outcomes and prioritize the highest-impact next action.", quick_commands_json:JSON.stringify(["Show today's growth opportunities","Create this week's growth plan","Review tasks and blockers","Show what the platform can do for my business"]), empty_state_actions_json:JSON.stringify(["Complete business profile","Connect a data source","Choose a growth goal"]) } };
}
async function loadMetricDefinitions(){return safeRows("SELECT metric_key, display_name, description, unit, aggregation_mode, comparison_mode, source_surface, freshness_sla_seconds, interpretation_template_key FROM growth_dashboard_metric_registry WHERE status = 'active'");}
async function loadProductActions(tabKeys=[]){
  const result=await safeRows("SELECT action_ref_key, tab_key, provider_family, connector_family, runtime_action_key, endpoint_selector, label, action_mode, requires_confirmation, required_capability_key, input_schema_json, preview_template_key, confirmation_template_key, success_readback_tool_key, failure_recovery_key, undo_action_key, expected_impact_metric_key, analytics_event_key, mobile_action_style, priority_order FROM activation_section_action_registry WHERE status='active' AND (tab_key IN (?) OR tab_key IS NULL) ORDER BY priority_order ASC, action_ref_key ASC LIMIT 100",[tabKeys.length?tabKeys:["tenant_today"]]);
  const runtimeKeys=uniq(result.rows.map((row)=>row.runtime_action_key).filter(Boolean)); const runtimeResult=runtimeKeys.length?await safeRows("SELECT action_key, runtime_callable, status FROM actions WHERE action_key IN (?)",[runtimeKeys]):{ok:true,rows:[]}; const runtimeMap=new Map(runtimeResult.rows.map((row)=>[row.action_key,row]));
  return {ok:result.ok&&runtimeResult.ok,actions:result.rows.map((row)=>{const runtime=row.runtime_action_key?runtimeMap.get(row.runtime_action_key):null;const runtimeReady=!row.runtime_action_key||(runtime&&booleanLike(runtime.runtime_callable)&&String(runtime.status||"active").toLowerCase()!=="archived");return{action_ref_key:row.action_ref_key,tab_key:row.tab_key,provider_family:row.provider_family||null,connector_family:row.connector_family||null,label:row.label,mode:row.action_mode,ready:runtimeReady,requires_confirmation:Boolean(row.requires_confirmation),required_capability_key:row.required_capability_key||null,runtime_action_key:row.runtime_action_key||null,endpoint_selector:row.endpoint_selector||null,input_schema:parseJson(row.input_schema_json,{}),preview_template_key:row.preview_template_key||null,confirmation_template_key:row.confirmation_template_key||null,success_readback_tool_key:row.success_readback_tool_key||null,failure_recovery_key:row.failure_recovery_key||null,undo_action_key:row.undo_action_key||null,expected_impact_metric_key:row.expected_impact_metric_key||null,analytics_event_key:row.analytics_event_key||null,mobile_action_style:row.mobile_action_style||"secondary",blocked_reason:runtimeReady?null:"runtime_action_not_ready"};}),degraded_surfaces:[result,runtimeResult].filter((item)=>item.ok===false).map((item)=>item.error)};
}

function cardDataStatus({sourceSystem="platform_registry",freshness="unknown",observedAt=null,partialData=false,confidence=.85}={}){return{freshness,observed_at:observedAt||new Date().toISOString(),source_system:sourceSystem,source_scope:"tenant_authorized",confidence,partial_data:partialData};}
function typedCard({id,type,title,value=null,unit=null,status="ready",interpretation,tabKey,metricKey=null,change=null,actions=[],dataStatus=null,detailsRef=null,emptyState=null}={}){return{card_id:id,card_type:type,title,value,unit,status,change,metric_key:metricKey,interpretation,tab_key:tabKey,actions,data_status:dataStatus||cardDataStatus(),details_ref:detailsRef,empty_state:emptyState};}
function actionsForTab(actions,tabKey,limit=3){return actions.filter((action)=>action.tab_key===tabKey||action.tab_key==="tenant_today").slice(0,limit);}
export function buildDashboardCards({businessContext,operationalSummary,dashboardManifest,metrics=[],actions=[],activeTab="tenant_today"}={}){
  const definitions=new Map(metrics.map((row)=>[row.metric_key,row])); const badges=operationalSummary?.tab_badges||{}; const connectorActive=safeNumber(badges.connectors?.active), connectorPending=safeNumber(badges.connectors?.pending), connectorError=safeNumber(badges.connectors?.error), openTasks=safeNumber(badges.tasks?.open), blockedTasks=safeNumber(badges.tasks?.blocked), activeAgents=safeNumber(badges.agents?.active), activeSkills=safeNumber(badges.skills?.active_grants), freshness=operationalSummary?.freshness_status||"unknown", brandReady=Boolean(businessContext?.brand?.brand_core_ready);
  const readinessScore=Math.max(0,Math.min(100,(brandReady?25:5)+Math.min(connectorActive*8,25)+(connectorError===0?15:0)+(blockedTasks===0?15:Math.max(0,15-blockedTasks*3))+(freshness==="fresh"?20:freshness==="unknown"?8:0))); const tabActions=actionsForTab(actions,activeTab); const cards=[];
  cards.push(typedCard({id:"business_growth_readiness",type:"score",title:definitions.get("dashboard_health_score")?.display_name||"Business Growth Readiness",value:readinessScore,unit:"score",status:readinessScore>=80?"strong":readinessScore>=55?"improving":"attention",metricKey:"dashboard_health_score",tabKey:"tenant_today",interpretation:readinessScore>=80?"Your core growth setup is ready for execution.":readinessScore>=55?"The foundation is usable, with a few gaps limiting growth execution.":"Complete the highest-priority setup gaps before scaling campaigns or automation.",actions:actionsForTab(actions,"tenant_growth_plan",2),dataStatus:cardDataStatus({freshness,sourceSystem:"tenant_growth_dashboard",confidence:.9})}));
  cards.push(typedCard({id:"active_integrations",type:"kpi",title:definitions.get("connected_systems_active")?.display_name||"Active Integrations",value:connectorActive,unit:"count",status:connectorError>0?"attention":connectorPending>0?"pending":connectorActive>0?"active":"not_connected",metricKey:"connected_systems_active",tabKey:"tenant_integrations",interpretation:connectorError>0?`${connectorError} integration${connectorError===1?"":"s"} need attention before the platform can use all available data.`:connectorActive>0?`${connectorActive} integration${connectorActive===1?" is":"s are"} ready to support analysis and actions.`:"Connect at least one business data source to unlock personalized growth insights.",actions:actionsForTab(actions,"tenant_integrations",2),dataStatus:cardDataStatus({freshness:"fresh",sourceSystem:"connected_systems"}),emptyState:connectorActive===0?{title:"No active integrations yet",steps:["Choose the first data source","Complete secure connection","Return to Today for refreshed guidance"]}:null}));
  cards.push(typedCard({id:"open_growth_tasks",type:"task",title:definitions.get("open_tasks")?.display_name||"Open Tasks",value:openTasks,unit:"count",status:blockedTasks>0?"attention":openTasks>0?"active":"clear",metricKey:"open_tasks",tabKey:"tenant_tasks",interpretation:blockedTasks>0?`${blockedTasks} task${blockedTasks===1?" is":"s are"} blocked and may delay growth execution.`:openTasks>0?`${openTasks} task${openTasks===1?" is":"s are"} available to move the growth plan forward.`:"No urgent tasks are currently blocking progress.",actions:actionsForTab(actions,"tenant_tasks",2),dataStatus:cardDataStatus({freshness:"fresh",sourceSystem:"v_activation_pending_tasks"})}));
  cards.push(typedCard({id:"automation_capacity",type:"kpi",title:"Available Automation Capacity",value:activeAgents+activeSkills,unit:"capabilities",status:activeAgents>0?"active":"limited",tabKey:"tenant_operations",interpretation:activeAgents>0?`${activeAgents} active agents and ${activeSkills} active skill grants can support research, planning, monitoring, and governed execution.`:"Automation capacity is limited until agents and skills are activated for this workspace.",actions:actionsForTab(actions,"tenant_operations",2),dataStatus:cardDataStatus({freshness:"fresh",sourceSystem:"agent_and_skill_registry"})}));
  cards.push(typedCard({id:"data_freshness",type:"status",title:definitions.get("data_freshness_score")?.display_name||"Data Freshness",value:freshness,unit:"status",status:freshness==="fresh"?"active":freshness==="unknown"?"unknown":"attention",metricKey:"data_freshness_score",tabKey:"tenant_operations",interpretation:freshness==="fresh"?"Connected data is fresh enough for current recommendations.":freshness==="unknown"?"Freshness has not been confirmed for all sources; recommendations will identify partial-data assumptions.":"Some connected data is stale and should be refreshed before high-impact decisions.",actions:tabActions,dataStatus:cardDataStatus({freshness,sourceSystem:"activation_freshness_ledger",partialData:freshness==="unknown"})}));
  for(const tile of (dashboardManifest?.tiles||[]).filter((tile)=>tile.status!=="not_connected").slice(0,4)){cards.push(typedCard({id:`integration_${tile.tile_key}`,type:"connector_status",title:tile.display_name,value:safeNumber(tile.counts?.active),unit:"active",status:tile.status,tabKey:"tenant_integrations",interpretation:tile.status==="attention"?`${tile.display_name} has an issue that can reduce data coverage or action readiness.`:`${tile.display_name} is available to support the dashboard.`,actions:actions.filter((action)=>[tile.provider_family,tile.connector_family].includes(action.provider_family)).slice(0,2),dataStatus:cardDataStatus({freshness:"fresh",sourceSystem:tile.provider_family||tile.connector_family||"integration"}),detailsRef:tile.details_ref||null}));}
  return cards.filter((card)=>activeTab==="tenant_today"||card.tab_key===activeTab).slice(0,activeTab==="tenant_today"?10:8);
}
function chooseTopIssue({businessContext,operationalSummary}){const badges=operationalSummary?.tab_badges||{},blocked=safeNumber(badges.tasks?.blocked),connectorErrors=safeNumber(badges.connectors?.error),connectorPending=safeNumber(badges.connectors?.pending),freshness=operationalSummary?.freshness_status||"unknown";if(!businessContext?.brand?.brand_core_ready)return{code:"brand_core_incomplete",headline:"Complete the business and brand foundation",why:"The platform needs a resolved Brand Core to create reliable customer-facing content and growth recommendations.",action_ref_key:"growth_plan_create",impact:"high",effort:"medium",confidence:.96};if(blocked>0)return{code:"blocked_growth_tasks",headline:`Resolve ${blocked} blocked growth task${blocked===1?"":"s"}`,why:"Blocked tasks prevent planned growth work from reaching execution or measurement.",action_ref_key:"task_review_blockers",impact:"high",effort:"low",confidence:.93};if(connectorErrors>0||connectorPending>0)return{code:"integration_readiness_gap",headline:"Improve data and integration readiness",why:"Incomplete integrations reduce visibility and prevent the platform from using all available growth signals.",action_ref_key:"growth_today_review",impact:"high",effort:"medium",confidence:.9};if(["stale","failed"].includes(freshness))return{code:"stale_growth_data",headline:"Refresh stale growth data",why:"Current decisions may be based on outdated performance or operational signals.",action_ref_key:"growth_today_review",impact:"medium",effort:"low",confidence:.9};return{code:"growth_opportunity_ready",headline:"Turn the strongest current signal into a focused growth experiment",why:"The core setup is ready, so the next value comes from prioritizing one measurable business outcome.",action_ref_key:businessContext?.business_type_key==="destination_or_travel_business"?"travel_destination_opportunity_review":"growth_plan_create",impact:"high",effort:"medium",confidence:.82};}
function buildAssistantGuidance({businessContext,instruction,navigation}){return{role:"tenant_growth_copilot",objective:"Help the customer understand platform capabilities and use them to grow the business.",headline:instruction.headline,business_guidance:instruction.guidance_template,behavior:["Start with business outcomes, not technical registry terminology.","Use the Today tab to summarize what changed, what matters, and the next best action.","Explain which platform capability can help and whether it is ready, requires connection, or requires confirmation.","Prioritize no more than three actions at a time and identify impact, effort, confidence, and missing data.","Do not treat missing data as zero; label unavailable, stale, or partial data explicitly.","Never execute consequential actions without governed confirmation and capability checks."],business_context:{business_type_key:businessContext.business_type_key,business_activity_type_key:businessContext.business_activity_type_key,growth_stage:businessContext.growth_stage,primary_goal:businessContext.primary_goal,brand_core_ready:Boolean(businessContext.brand?.brand_core_ready)},navigation_policy:{start_tab:navigation.active_tab,available_tabs:navigation.tabs.map((tab)=>tab.tab_key),use_progressive_disclosure:true,details_are_loaded_on_demand:true}};}
function buildNavigation({tabKeys,registryRows,profileRows,preferences,activeTab,operationalManifest}){const registryMap=new Map(registryRows.map((row)=>[row.tab_key,row])),profileMap=new Map(profileRows.map((row)=>[row.tab_key,row])),pinned=new Set(preferences.pinned_tabs||[]),operationalTabs=new Map((operationalManifest?.containers?.[0]?.tabs||[]).map((tab)=>[tab.tab_key,tab]));const tabs=tabKeys.map((tabKey,index)=>{const row=registryMap.get(tabKey)||{},profile=profileMap.get(tabKey)||{},operational=operationalTabs.get(PRODUCT_TAB_TO_OPERATIONAL_TAB[tabKey]);return{tab_key:tabKey,label:row.display_name||row.mobile_label||tabKey.replace(/^tenant_/,"").replaceAll("_"," "),mobile_label:row.mobile_label||row.display_name||null,description:row.description||null,icon_key:row.icon_key||"layout-dashboard",renderer_key:row.renderer_key||"growth_dashboard_default",group:row.tab_group||"custom",pinned:pinned.has(tabKey)||Boolean(profile.default_pinned)||Boolean(row.default_pinned),active:tabKey===activeTab,status:operational?.status||"ready",badge:safeNumber(operational?.attention_count||operational?.item_count),hydration_state:tabKey===activeTab||tabKey==="tenant_today"?"summary_loaded":"manifest_only",priority:safeNumber(profile.priority_order||row.mobile_priority||row.priority_order||index+1),details_ref:operational?.details_ref||null};});tabs.sort((a,b)=>a.pinned===b.pinned?a.priority-b.priority:a.pinned?-1:1);return{active_tab:tabs.some((tab)=>tab.tab_key===activeTab)?activeTab:tabs[0]?.tab_key||"tenant_today",tabs,mobile_tab_count:tabs.length,progressive_disclosure:true};}

export async function buildTenantGrowthDashboard({tenantId,userId,containerKey=null,tabKey=null,dateRange=null,filters={},mode="dashboard"}={}){
  if(!tenantId||!userId){const error=new Error("Tenant dashboard requires tenant_id and user_id from a signed user JWT.");error.status=401;error.code="tenant_dashboard_principal_required";throw error;}
  const [preferencesResult,containersResult,tabRegistryResult,profileResult,metricResult]=await Promise.all([readTenantDashboardPreferences({tenantId,userId}),loadContainers(tenantId),loadProductTabRegistry(),loadTabProfiles(),loadMetricDefinitions()]); const preferences=preferencesResult.preferences,containers=containersResult.rows,requestedContainerKey=containerKey||preferences.active_container_key,activeWorkspace=containers.find((row)=>`workspace:${row.workspace_id}`===requestedContainerKey)||containers.find((row)=>row.bootstrap_status==="ready")||containers[0]||null;
  const businessContext=await loadBusinessContext({tenantId,workspace:activeWorkspace}),instructionResult=await loadInstructions(businessContext),tabKeys=resolveProductTabKeys({businessContext,profileRows:profileResult.rows,preferences}),requestedTab=tabKey||preferences.active_tab_key||"tenant_today",activeTab=tabKeys.includes(requestedTab)?requestedTab:tabKeys[0]||"tenant_today",sessionContext={subject:{is_admin:false,tenant_id:tenantId,user_id:userId},platform_access:{principal:{is_admin:false,tenant_id:tenantId,user_id:userId}}};
  const [operationalSummary,dashboardManifest,operationalManifest,actionResult]=await Promise.all([buildActivationOperationalSummary({sessionContext,attentionLimit:mode==="activation"?5:12}),buildActivationDashboardManifest({sessionContext}),buildActivationTabManifest({sessionContext}),loadProductActions(tabKeys)]);
  const navigation=buildNavigation({tabKeys,registryRows:tabRegistryResult.rows,profileRows:profileResult.rows,preferences,activeTab,operationalManifest}),cards=buildDashboardCards({businessContext,operationalSummary,dashboardManifest,metrics:metricResult.rows,actions:actionResult.actions,activeTab:navigation.active_tab}),topIssue=chooseTopIssue({businessContext,operationalSummary});
  const nextBestActions=uniq([topIssue.action_ref_key,...actionResult.actions.filter((action)=>action.ready).map((action)=>action.action_ref_key)]).slice(0,3).map((actionRef,index)=>{const action=actionResult.actions.find((item)=>item.action_ref_key===actionRef);return{recommendation_id:`${activeWorkspace?.workspace_id||tenantId}:${actionRef}:${index}`,action_ref_key:actionRef,label:action?.label||topIssue.headline,why_it_matters:index===0?topIssue.why:"This action supports the current business goal and available platform capabilities.",impact:index===0?topIssue.impact:"medium",effort:index===0?topIssue.effort:"low",confidence:index===0?topIssue.confidence:.75,ready:action?.ready!==false,requires_confirmation:Boolean(action?.requires_confirmation),blocked_reason:action?.blocked_reason||null,expected_impact_metric_key:action?.expected_impact_metric_key||null,preview:{available:true,template_key:action?.preview_template_key||"growth_action_preview"}};});
  const instruction=instructionResult.instruction,quickCommands=parseJson(instruction.quick_commands_json,[])||[],emptyStateActions=parseJson(instruction.empty_state_actions_json,[])||[]; const degradedSurfaces=[preferencesResult.degraded?{surface:"tenant_dynamic_dashboard_preferences",error:preferencesResult.error}:null,containersResult.ok===false?{surface:"workspace_registry",error:containersResult.error}:null,tabRegistryResult.ok===false?{surface:"activation_dynamic_tab_registry",error:tabRegistryResult.error}:null,profileResult.ok===false?{surface:"growth_dashboard_tab_profile_registry",error:profileResult.error}:null,metricResult.ok===false?{surface:"growth_dashboard_metric_registry",error:metricResult.error}:null,instructionResult.result.ok===false?{surface:"growth_dashboard_instruction_registry",error:instructionResult.result.error}:null,...(actionResult.degraded_surfaces||[]).map((error)=>({surface:"activation_section_action_registry",error})),...(operationalSummary.degraded_surfaces||[]).map((error)=>({surface:"activation_operational_summary",error}))].filter(Boolean);
  const response={ok:degradedSurfaces.length===0,product_layer:"tenant_growth_dashboard",product_version:"1.0",mode,subject:{tenant_id:tenantId,user_id:userId,scope:"tenant_user"},active_container:activeWorkspace?publicContainer(activeWorkspace):null,available_containers:containers.map(publicContainer),business_context:businessContext,dashboard_state:{date_range:dateRange||preferences.preferred_date_range,filters:filters&&typeof filters==="object"?filters:preferences.saved_filters,density:preferences.dashboard_density,language:preferences.language||null,currency:preferences.currency||null,timezone:preferences.timezone||null},navigation,today:{headline:topIssue.headline,why_it_matters:topIssue.why,attention_count:safeNumber(operationalSummary.summary?.attention_count),critical_attention_count:safeNumber(operationalSummary.summary?.critical_attention_count),changed_since_last_visit:operationalSummary.attention_items?.slice(0,5)||[]},cards,growth_guidance:{headline:topIssue.headline,why_it_matters:topIssue.why,primary_goal:businessContext.primary_goal,next_best_action:nextBestActions[0]||null,missing_data:[!businessContext.business_activity_type_key?"business_activity_type":null,!businessContext.brand?.brand_core_ready?"brand_core":null,safeNumber(operationalSummary.summary?.connected_system_count)===0?"connected_business_data":null].filter(Boolean)},next_best_actions:nextBestActions,available_actions:actionResult.actions,assistant_guidance:buildAssistantGuidance({businessContext,instruction,navigation}),quick_commands:quickCommands,empty_state:activeWorkspace?null:{title:"Create or select a workspace to start the growth dashboard.",actions:emptyStateActions},data_contract:{typed_cards:true,metric_definitions:metricResult.rows,freshness_and_provenance_required:true,missing_data_is_not_zero:true,details_are_cursor_loaded:true,customer_safe:true,secrets_included:false},detail_refs:{activation_awareness:{path:"/tenant/activation/awareness",profile:"summary"},dynamic_tab_detail:activeWorkspace?{path:"/tenant/activation/dynamic-tabs/detail",container_key:`workspace:${activeWorkspace.workspace_id}`,tab_key:PRODUCT_TAB_TO_OPERATIONAL_TAB[navigation.active_tab]||"container_overview"}:null,preferences:{path:"/tenant/dashboard/preferences"},feedback:{path_template:"/tenant/dashboard/recommendations/{recommendation_id}/feedback"}},degraded_surfaces:degradedSurfaces,secrets_included:false};
  if(mode==="activation")return{ok:response.ok,product_layer:response.product_layer,product_version:response.product_version,active_container:response.active_container,business_context:response.business_context,navigation:response.navigation,today:response.today,growth_guidance:response.growth_guidance,next_best_actions:response.next_best_actions,assistant_guidance:response.assistant_guidance,quick_commands:response.quick_commands,detail_refs:response.detail_refs,degraded_surfaces:response.degraded_surfaces,secrets_included:false}; return response;
}
export async function buildTenantDashboardDigest({tenantId,userId,containerKey=null}={}){const dashboard=await buildTenantGrowthDashboard({tenantId,userId,containerKey,mode:"activation"});return{ok:dashboard.ok,product_layer:"tenant_growth_digest",generated_at:new Date().toISOString(),active_container:dashboard.active_container,headline:dashboard.today?.headline||"Growth dashboard update",summary:{attention_count:dashboard.today?.attention_count||0,critical_attention_count:dashboard.today?.critical_attention_count||0,primary_goal:dashboard.business_context?.primary_goal||null},opportunities:dashboard.next_best_actions||[],quick_commands:dashboard.quick_commands||[],delivery_policy:{channels_supported:["in_app","email_digest","notification_adapter"],external_delivery_requires_configured_channel_and_consent:true},secrets_included:false};}
export async function recordTenantGrowthRecommendationEvent({tenantId,userId,recommendationId,eventType,reasonCode=null,workspaceId=null,recommendationKey=null,tabKey=null,cardId=null,resultMetricKey=null,resultValue=null,context={}}={}){if(!ALLOWED_EVENT_TYPES.has(String(eventType||""))){const error=new Error("Unsupported recommendation event type.");error.status=400;error.code="tenant_growth_recommendation_event_type_invalid";throw error;}const eventId=randomUUID();await getPool().query("INSERT INTO tenant_growth_recommendation_events (event_id, tenant_id, user_id, workspace_id, recommendation_id, recommendation_key, tab_key, card_id, event_type, reason_code, result_metric_key, result_value_json, context_json, occurred_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UTC_TIMESTAMP())",[eventId,tenantId,userId,safeText(workspaceId,36),safeText(recommendationId,180),safeText(recommendationKey,180),safeText(tabKey,160),safeText(cardId,180),eventType,safeText(reasonCode,120),safeText(resultMetricKey,180),resultValue===null?null:JSON.stringify(resultValue),JSON.stringify(context&&typeof context==="object"?context:{})]);return{ok:true,event_id:eventId,event_type:eventType,secrets_included:false};}
export async function buildTenantDashboardActionPreview({tenantId,userId,actionRefKey,containerKey=null}={}){const dashboard=await buildTenantGrowthDashboard({tenantId,userId,containerKey,mode:"activation"});const action=dashboard.next_best_actions?.find((item)=>item.action_ref_key===actionRefKey)||(await loadProductActions(dashboard.navigation?.tabs?.map((tab)=>tab.tab_key)||[])).actions.find((item)=>item.action_ref_key===actionRefKey);if(!action){const error=new Error("Growth dashboard action was not found in the caller scope.");error.status=404;error.code="tenant_growth_dashboard_action_not_found";throw error;}return{ok:true,product_layer:"tenant_growth_action_preview",action,active_container:dashboard.active_container,business_context:dashboard.business_context,preview:{will_execute:false,expected_business_outcome:action.expected_impact_metric_key||null,required_confirmation:Boolean(action.requires_confirmation),readiness:action.ready===false?"blocked":"ready_for_governed_resolution",blocked_reason:action.blocked_reason||null},policy:{preview_only:true,no_provider_call:true,no_write:true,execution_requires_runtime_authority_and_confirmation:true},secrets_included:false};}
export const _testingTenantGrowthDashboard={parseJson,safeNumber,normalizeKey,booleanLike,publicContainer,chooseTopIssue,typedCard,cardDataStatus,PRODUCT_TAB_TO_OPERATIONAL_TAB,DEFAULT_PRODUCT_TABS};
